% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{amsmath}
\usepackage{mathtools}
\usepackage{amsthm}
\usepackage{multirow}
\usepackage{booktabs}
\usepackage{minted}
\usepackage{color}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Regression Analysis - STAT482 - HW \#1},
  pdfauthor={Alex Towell (atowell@siue.edu)},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Regression Analysis - STAT482 - HW \#1}
\author{Alex Towell
(\href{mailto:atowell@siue.edu}{\nolinkurl{atowell@siue.edu}})}
\date{}

\begin{document}
\maketitle

\newcommand{\var}{\operatorname{Var}}
\newcommand{\expect}{\operatorname{E}}
\newcommand{\corr}{\operatorname{Corr}}
\newcommand{\cov}{\operatorname{Cov}}
\newcommand{\ssr}{\operatorname{SSR}}
\newcommand{\se}{\operatorname{SE}}
\newcommand{\mat}[1]{\mathbf{#1}}
\newcommand{\RR}{\operatorname{RR}}
\newcommand{\eval}[2]{\left. #1 \right\vert_{#2}}

Refer to the data from Exercise 1.27

A person's muscle mass is expected to decrease with age. To explore this
relationship in women, a nutritionist randomly selected \(15\) women for
each \(10\) year age group, beginning with \(40\) and ending with age
\(79\). The input variable \(x\) is age (in years), and the response
variable \(y\) is muscle mass (in muscle mass units).

\hypertarget{part-1}{%
\section{Part (1)}\label{part-1}}

\fbox{State the simple linear regression model.}

The data is given by \((x_1,y_1),\ldots,(x_n,y_n)\) and, we assume, it
at least approximately comes from the model given by \[
  Y_i = \beta_0 + \beta_1 x_i + \epsilon_i
\] for \(i=1,\ldots,n\) where
\(\epsilon_i \stackrel{\text{iid}}{\sim} N(0,\sigma^2)\).

Therefore, \(Y_1,\ldots,Y_n\) are independently distributed with a
variance \(\sigma^2\) and a conditional expectation \[
  E(Y_i|x_i) = \beta_0 + \beta_1 x_i
\] at the given input level \(x_i\) for \(i=1,\ldots,n\).

\hypertarget{part-2}{%
\section{Part (2)}\label{part-2}}

\fbox{Provide an interpretation for the regression parameter $\beta_1$, stated
in the context of the problem.}

\(\beta_1\) is the difference in the mean muscle mass from a \(1\) year
increase in age. In other words, for every \(1\) year increase in age
\((x)\), the mean muscle mass decreases by \(\beta_1\) units. (Note that
since we expect a negative correlation between age and muscle mass,
\(\beta_1\) is expected to be negative.)

\hypertarget{part-3}{%
\section{Part (3)}\label{part-3}}

\fbox{Compute the estimated regression line.}

We populate the data frame for exercise 1.27 with the following:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# the tabulated data is provided by the file accompanying file named \textquotesingle{}CH01PR27.txt\textquotesingle{}.}
\CommentTok{\# the original URL for this data is:}
\CommentTok{\#     http://users.stat.ufl.edu/\textasciitilde{}rrandles/sta4210/Rclassnotes/data/textdatasets/KutnerData/Chapter\%20\%201\%20Data\%20Sets/CH01PR27.txt}
\NormalTok{mass.data }\OtherTok{=} \FunctionTok{read.table}\NormalTok{(}\StringTok{\textquotesingle{}CH01PR27.txt\textquotesingle{}}\NormalTok{)}
\FunctionTok{colnames}\NormalTok{(mass.data)}\OtherTok{=}\FunctionTok{c}\NormalTok{(}\StringTok{"mass"}\NormalTok{,}\StringTok{"age"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

We use R's built-in function \(\operatorname{lm}\) to perform the simple
linear regression.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# the model for muscle mass, mass[i] = beta0 + beta1 * age[i] + e[i]}
\CommentTok{\# where e[i] \textasciitilde{} N(0,sigma2).}
\NormalTok{mass.mod }\OtherTok{=} \FunctionTok{lm}\NormalTok{(mass }\SpecialCharTok{\textasciitilde{}}\NormalTok{ age, }\AttributeTok{data=}\NormalTok{mass.data)}
\NormalTok{mass.mod}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = mass ~ age, data = mass.data)
## 
## Coefficients:
## (Intercept)          age  
##      156.35        -1.19
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{b0 }\OtherTok{=} \FunctionTok{round}\NormalTok{(mass.mod}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{1}\NormalTok{],}\AttributeTok{digits=}\DecValTok{2}\NormalTok{); }\FunctionTok{names}\NormalTok{(b0) }\OtherTok{=} \ConstantTok{NULL}
\NormalTok{b1 }\OtherTok{=} \FunctionTok{round}\NormalTok{(mass.mod}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{2}\NormalTok{],}\AttributeTok{digits=}\DecValTok{2}\NormalTok{); }\FunctionTok{names}\NormalTok{(b1) }\OtherTok{=} \ConstantTok{NULL}
\FunctionTok{c}\NormalTok{(}\StringTok{"b0"}\OtherTok{=}\NormalTok{b0,}\StringTok{"b1"}\OtherTok{=}\NormalTok{b1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     b0     b1 
## 156.35  -1.19
\end{verbatim}

We see that \(b_0 = 156.35\) and \(b_1 = -1.19\), and thus our estimate
of \(E(Y|x)\) is given by \[
  \hat{Y}_i = 156.35 - 1.19 x_i.
\]

\hypertarget{part-4}{%
\section{Part (4)}\label{part-4}}

\fbox{Compute the estimated variance and standard deviation.}

We show two methods to obtain the variance and standard deviation.

\hypertarget{method-1}{%
\subsection{Method 1}\label{method-1}}

First, we may use R's built-in method:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sigma.hat }\OtherTok{=} \FunctionTok{summary}\NormalTok{(mass.mod)}\SpecialCharTok{$}\NormalTok{sigma}
\NormalTok{sigma2.hat }\OtherTok{=}\NormalTok{ sigma.hat}\SpecialCharTok{\^{}}\DecValTok{2}
\FunctionTok{c}\NormalTok{(}\StringTok{"sigma.hat"}\OtherTok{=}\NormalTok{sigma.hat,}\StringTok{"sigma.hat\^{}2"}\OtherTok{=}\NormalTok{sigma2.hat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   sigma.hat sigma.hat^2 
##    8.173177   66.800819
\end{verbatim}

We see that \(\hat\sigma^2 = 66.8008189\) and
\(\hat\sigma = 8.1731768\). Thus, an estimate of the conditional
generative model for \(Y_i\) given \(x_i\) is given by \[
  \hat{Y}_i = 156.35 - 1.19 x_i + \hat\epsilon_i
\] where
\(\hat\epsilon_i \stackrel{\text{iid}}{\sim} \mathcal{N}(0,66.8008189)\)
whose expectation is \(E(\hat{Y_i}|x_i) = 156.35 - 1.19 x_i\).

\hypertarget{method-2}{%
\subsection{Method 2}\label{method-2}}

A second approach to estimating \(\sigma^2\) and \(\sigma\) is given by
the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{resid }\OtherTok{=}\NormalTok{ mass.mod}\SpecialCharTok{$}\NormalTok{residuals}
\NormalTok{n }\OtherTok{=} \FunctionTok{length}\NormalTok{(resid)}
\NormalTok{sse }\OtherTok{=} \FunctionTok{sum}\NormalTok{(resid}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{mse }\OtherTok{=}\NormalTok{ sse }\SpecialCharTok{/}\NormalTok{ (n}\DecValTok{{-}2}\NormalTok{) }\CommentTok{\# df = n{-}2 }
\NormalTok{sigma2.hat }\OtherTok{=}\NormalTok{ mse }\CommentTok{\# estimate of sigma\^{}2}
\NormalTok{sigma.hat }\OtherTok{=} \FunctionTok{sqrt}\NormalTok{(sigma2.hat) }\CommentTok{\# estimate of sigma}
\FunctionTok{c}\NormalTok{(}\StringTok{"sigma.hat"}\OtherTok{=}\NormalTok{sigma.hat,}\StringTok{"sigma.hat\^{}2"}\OtherTok{=}\NormalTok{sigma2.hat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   sigma.hat sigma.hat^2 
##    8.173177   66.800819
\end{verbatim}

\hypertarget{part-5}{%
\section{Part (5)}\label{part-5}}

\fbox{Create a scatterplot with the least squares line included.}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}\AttributeTok{x=}\NormalTok{mass.data}\SpecialCharTok{$}\NormalTok{age,}
     \AttributeTok{y=}\NormalTok{mass.data}\SpecialCharTok{$}\NormalTok{mass,}
     \AttributeTok{pch=}\DecValTok{20}\NormalTok{,}
     \AttributeTok{type=}\StringTok{"p"}\NormalTok{,}
     \AttributeTok{xlab=}\StringTok{"age"}\NormalTok{,}
     \AttributeTok{ylab=}\StringTok{"muscle mass"}\NormalTok{,}
     \AttributeTok{main=}\StringTok{"age vs muscle mass"}\NormalTok{)}

\FunctionTok{abline}\NormalTok{(mass.mod,}\AttributeTok{col=}\StringTok{"blue"}\NormalTok{)}

\FunctionTok{legend}\NormalTok{(}\AttributeTok{x=}\DecValTok{40}\NormalTok{, }\AttributeTok{y=}\DecValTok{64}\NormalTok{,}
       \AttributeTok{legend=}\FunctionTok{c}\NormalTok{(}\StringTok{"data"}\NormalTok{,}\StringTok{"least{-}squares"}\NormalTok{),}
       \AttributeTok{col=}\FunctionTok{c}\NormalTok{(}\StringTok{"black"}\NormalTok{,}\StringTok{"blue"}\NormalTok{), }\AttributeTok{lty=}\FunctionTok{c}\NormalTok{(}\StringTok{"dotted"}\NormalTok{,}\StringTok{"solid"}\NormalTok{),}
       \AttributeTok{cex=}\FloatTok{0.8}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1_files/figure-latex/unnamed-chunk-7-1.pdf}

\hypertarget{part-6}{%
\section{Part (6)}\label{part-6}}

\fbox{Comment on the appropriateness of the simple linear regression model for this example.}

From a visual inspection of the scatterplot, the amount of muscle mass
shows a general linear (decreasing) trend as a function of age. Thus, a
linear regression model is appropriate.

\hypertarget{time-series-analysis}{%
\subsection{Time series analysis}\label{time-series-analysis}}

Feel free to ignore this subsection, since I explore the topic with
insights from a time series class taught by Dr.~Qiang, where some of the
assumptions in the regression model are relaxed, e.g., the random errors
term may be correlated.

We see that the data points are randomly scattered around the regression
line, such that the deviations from the conditional expectation have no
obvious patterns, suggesting the model has captured all significant
patterns in the data leaving a white noise process as the only remaining
source of uncertainty.

We show a histogram of the residuals, a scatterplot of residuals vs age,
and the autocorrelation of the residuals:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{3}\NormalTok{))}
\FunctionTok{hist}\NormalTok{(mass.mod}\SpecialCharTok{$}\NormalTok{residuals,}\AttributeTok{xlab=}\StringTok{"residual"}\NormalTok{,}\AttributeTok{main=}\StringTok{"histogram of residuals"}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(}\AttributeTok{x=}\NormalTok{mass.data}\SpecialCharTok{$}\NormalTok{age,}\AttributeTok{y=}\NormalTok{mass.mod}\SpecialCharTok{$}\NormalTok{residuals,}\AttributeTok{xlab=}\StringTok{"age"}\NormalTok{,}\AttributeTok{ylab=}\StringTok{"residuals"}\NormalTok{,}\AttributeTok{main=}\StringTok{"residuals vs age"}\NormalTok{)}
\FunctionTok{acf}\NormalTok{(mass.mod}\SpecialCharTok{$}\NormalTok{residuals,}\AttributeTok{main=}\StringTok{"acf of residuals"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1_files/figure-latex/unnamed-chunk-8-1.pdf}

The histogram appears compatible with the normality assumption, the
scatterplot indicates the residuals are centered around \(0\) with a
constant variance, and the ACF plot indicates the residuals are
uncorrelated.

If, say, the ACF demonstrated autocorrelation, then while the estimated
regression model used previously would still provide for a good fit, the
estimate of the variance would be larger than necessary compared to,
say, an ARIMA model.

\end{document}
