% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{amsmath}
\usepackage{mathtools}
\usepackage{amsthm}
\usepackage{multirow}
\usepackage{booktabs}
\usepackage{minted}
\usepackage{color}
\usepackage{xcolor}
\usepackage{tcolorbox}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Regression Analysis - STAT 482 - HW \#5},
  pdfauthor={Alex Towell (atowell@siue.edu)},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Regression Analysis - STAT 482 - HW \#5}
\author{Alex Towell
(\href{mailto:atowell@siue.edu}{\nolinkurl{atowell@siue.edu}})}
\date{}

\begin{document}
\maketitle

\newcommand{\sse}{\operatorname{SS_E}}
\newcommand{\sspe}{\operatorname{SS_{PE}}}
\newcommand{\sslf}{\operatorname{SS_{LF}}}
\newcommand{\mspe}{\operatorname{MS_{PE}}}
\newcommand{\mslf}{\operatorname{MS_{LF}}}
\newcommand{\ssto}{\operatorname{SSTO}}
\newcommand{\ssx}{\operatorname{SS_X}}
\newcommand{\ssr}{\operatorname{SS_R}}
\newcommand{\msr}{\operatorname{MS_R}}
\newcommand{\mse}{\operatorname{MS_E}}
\newcommand{\var}{\operatorname{V}}
\newcommand{\sd}{\operatorname{sd}}
\newcommand{\expect}{\operatorname{E}}
\newcommand{\corr}{\operatorname{cor}}
\newcommand{\cov}{\operatorname{cov}}
\newcommand{\se}{\operatorname{se}}
\newcommand{\mat}[1]{\mathbf{#1}}
\newcommand{\eval}[2]{\left. #1 \right\vert_{#2}}
\newcommand{\dfe}{\operatorname{df_E}}

Refer to the data from Exercise 3.15

A designed experiment is conducted to study the concentration of a
solution (\(y\)) over time (\(x\)) in hours.

\hypertarget{problem-1}{%
\section{Problem 1}\label{problem-1}}

\begin{tcolorbox}[split=\f]
Part (a)
\tcblower
Compute the estimated regression line.
\end{tcolorbox}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#setwd("/home/spinoza/filetopia/gdrive/alex/college/grad\_math\_classes/stat482\_regression\_analysis\_fa2021/hw/hw5")}

\NormalTok{data }\OtherTok{=} \FunctionTok{read.table}\NormalTok{(}\StringTok{\textquotesingle{}CH03PR15.txt\textquotesingle{}}\NormalTok{)}
\FunctionTok{names}\NormalTok{(data) }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"conc"}\NormalTok{,}\StringTok{"hours"}\NormalTok{)}
\FunctionTok{head}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   conc hours
## 1 0.07     9
## 2 0.09     9
## 3 0.08     9
## 4 0.16     7
## 5 0.17     7
## 6 0.21     7
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{reg.mod }\OtherTok{=} \FunctionTok{lm}\NormalTok{(conc }\SpecialCharTok{\textasciitilde{}}\NormalTok{ hours, }\AttributeTok{data=}\NormalTok{data)}
\NormalTok{reg.mod}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = conc ~ hours, data = data)
## 
## Coefficients:
## (Intercept)        hours  
##       2.575       -0.324
\end{verbatim}

Our estimate of the linear regression function is given by \[
  \hat{Y} = 2.575 - 0.324 x.
\]

\hypertarget{additional-analysis}{%
\subsubsection{Additional analysis}\label{additional-analysis}}

A simple visual analysis shows that this first-order linear regression
model is unable to capture the variability in the concentration with
respect to hours.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(}\AttributeTok{xlab=}\StringTok{"hour"}\NormalTok{,}\AttributeTok{ylab=}\StringTok{"concentration"}\NormalTok{,data}\SpecialCharTok{$}\NormalTok{hours,data}\SpecialCharTok{$}\NormalTok{conc,}\AttributeTok{col=}\StringTok{"blue"}\NormalTok{,}\AttributeTok{pch=}\StringTok{\textquotesingle{}*\textquotesingle{}}\NormalTok{)}
\FunctionTok{lines}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{hours,reg.mod}\SpecialCharTok{$}\NormalTok{fitted.values,}\AttributeTok{col=}\StringTok{"red"}\NormalTok{)}
\FunctionTok{legend}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{3}\NormalTok{,}\AttributeTok{legend=}\FunctionTok{c}\NormalTok{(}\StringTok{"data"}\NormalTok{,}\StringTok{"regression"}\NormalTok{),}\AttributeTok{col=}\FunctionTok{c}\NormalTok{(}\StringTok{"blue"}\NormalTok{,}\StringTok{"red"}\NormalTok{),}\AttributeTok{pch=}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}*\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}{-}\textquotesingle{}}\NormalTok{))}

\FunctionTok{plot}\NormalTok{(reg.mod}\SpecialCharTok{$}\NormalTok{residuals,}\AttributeTok{pch=}\StringTok{\textquotesingle{}*\textquotesingle{}}\NormalTok{,}\AttributeTok{xlab=}\StringTok{"hour"}\NormalTok{,}\AttributeTok{ylab=}\StringTok{"residual"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw5_files/figure-latex/unnamed-chunk-3-1.pdf}

A plot of the regression function versus the data shows that it is
biased. A plot of the residuals shows a clear pattern, suggesting that
we could do better with a more complex model that is able to capture the
systemic variability in the data.

\begin{tcolorbox}[split=\f]
Part (b)
\tcblower
Compute a point estimate for $\mu_5$, the mean concentration for $x=5$ hours.
\end{tcolorbox}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{u5.hat }\OtherTok{=} \FunctionTok{predict}\NormalTok{(reg.mod, }\AttributeTok{newdata=}\FunctionTok{data.frame}\NormalTok{(}\AttributeTok{hours=}\DecValTok{5}\NormalTok{))}
\NormalTok{u5.hat}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         1 
## 0.9553333
\end{verbatim}

We see that \(\hat{\mu}_5 = \hat{\operatorname{E}}(Y|X=5) = 0.9553333\).
We note that this estimate is not compatible with the datam, and thus we
would not predict that the mean concentration of the solution at \(5\)
hours is 0.9553333.

\begin{tcolorbox}[split=\f]
Part (c)
\tcblower
Explain an advantage of using the regression estimate $\hat{\mu}_5$
instead of the sample mean $\bar{y}_5$, and explain when this advantage will
lead to a more accurate estimator.
\end{tcolorbox}

\hypertarget{variance}{%
\subsection{Variance}\label{variance}}

A measure of the precision of an estimator is give by its variance. A
primary advantage of the linear regression estimator of the mean \[
  \hat{\mu}_5 = b_0 + 5 b_1,
\] compared to the saturated model estimator \[
  \bar{y}_5 = \operatorname{avg}\left(\{y_i : x_i=5\}\right)
\] is that \(\hat{\mu}_5\) has smaller variance,
\(\operatorname{V}(\hat{\mu}_5) < \operatorname{V}(\bar{y}_5)\), i.e.,
it is a more precise estimator.

\hypertarget{information}{%
\subsubsection{Information}\label{information}}

The variance of an estimator of \(\operatorname{E}(Y|X=5)\) decreases as
the information we have about \(\operatorname{E}(Y|X=5)\) increases. One
way in which the information increases is by increasing the sample size.
In the case of \(\hat{y}_5\), we are only using the information in the
subset \(\{(x_i,y_i) : x_i = 5\}\), but in the case of \(\hat{\mu}_5\),
we are using the information in the entire sample \(\{(x_i,y_i)\}\).

\hypertarget{bias}{%
\subsection{Bias}\label{bias}}

A measure of the accuracy of an estimator is its bias. If the linear
regression model is an appropriate model for the data generating
process, it will have a small bias. Moreover, if the true data
generating process is given by \[
  Y_i | x_i \overset{\text{indep}}{\sim} \mathcal{N}(\beta_0 + \beta_1 x_i, \sigma^2)
\] then the estimator of the mean response \[
  \hat{\operatorname{E}}(Y|x) = b_0 + b_1 x
\] is the UMVU estimator for the mean response of the data generating
process.

\hypertarget{additional-commentary}{%
\subsubsection{Additional commentary}\label{additional-commentary}}

This is not strictly related to the question posed by this problem set
but is rather for my own instruction. Feel free to ignore, but any
feedback is quite welcome.

This has to do with a distinction between estimating the data generating
process and performing forecasts or predictions with appropriate
confidence intervals.

Assuming \[
  Y_i|x_i \overset{\text{iid}}{\sim} \mathcal{N}(\beta_0+\beta_1 x_i, \sigma^2),
\] the UMVU estimator of the data generating process \(Y|x\) is given by
\[
  \widehat{Y|x} \sim \mathcal{N}(b_0 + b_1 x, \hat{\sigma}^2)
\] where \(\hat{\sigma}^2 = \operatorname{MS_E}\) and \((b_0,b_1)'\) is
the least squares estimator of \((\beta_0,\beta_1)\).

Observe that \(\widehat{Y|x}\) has a sampling distribution since
\(b_0\), \(b_1\), and \(\hat{\sigma}^2\) are functions of the random
sample \(\{(x_i,Y_i) : i=1,\ldots,n\}\). Thus, if we wished to, say,
perform an individual forecast of \(Y|x\), confidence intervals must
incorporate this sampling variance as described in a previous homework.
However, the estimator \(\widehat{Y|x}\) remains the most accurate and
precise estimator for the conditional random variable \(Y|x\).

The prediction problem \(Y_{h(\text{new})}|x_h\) and the estimator of
the conditional distribution \(Y|x\) answer different questions whose
distinction, at first glance, may not even be recognized. Even now, I am
still not convinced my analysis is correct. It seems a bit slippery.
Tread carefully!

\hypertarget{problem-2}{%
\section{Problem 2}\label{problem-2}}

\begin{tcolorbox}[split=\f]
Part (a)
\tcblower
State the full model (saturated model) in testing for regression model fit.
\end{tcolorbox}

In the saturated model, the mean response is \emph{unconstrained}, but
we require at least one of the inputs to have \emph{replications}.

There are \(c=5\) levels of the input variable,
\(x_1=1,x_2=3,x_3=5,x_4=7,x_5=9\), where the \(i\)-th input variable has
\(n_i=3\) replications for a total of
\(n=\sum_{i=1}^{c} n_i = 3(5) = 15\) observations.

The saturated model is given by \[
  Y_{i j} = \mu_i + \epsilon_{i j}
\] where
\(\epsilon_{i j} \overset{\text{iid}}{\sim} \mathcal{N}(0,\sigma^2)\)
for \(i=1,\ldots,5\) and \(j=1,\ldots,3\).

We may also write the reduced model, the linear regression model, as \[
  Y_{i j} = \beta_0 + \beta_1 x_i + \epsilon_{i j}.
\]

\begin{tcolorbox}[split=\f]
Part (b)
\tcblower
Compute $\operatorname{SS_{PE}}$ and $\operatorname{SS_{LF}}$ for testing the fit of the linear regression model.
State the respective degrees of freedom.
\end{tcolorbox}

The sum of squared errors with respect to the full (saturated) model is
given by \[
  \operatorname{SS_{PE}}= \operatorname{SS_E}(F) = \sum_{i=1}^{c}\sum_{j=1}^{n_i} (Y_{i j} - \bar{Y}_i)^2
\] which simplifies to \[
  \operatorname{SS_{PE}}= \sum_{i=1}^{c} (n_i-1) s_i^2,
\] where \(\operatorname{SS_{PE}}\) is called the
\emph{pure error some of squares}, which has
\(\operatorname{df_E}(F) = \sum_{i=1}^{c} (n_i-1) = n-c = 15-5 = 10\)
degrees of freedom.

The sum of squared errors with respect to the reduced (linear
regression) model is given by \[
  \operatorname{SS_E}(R) = \sum_{i=1}^{c}\sum_{j=1}^{n_i} (Y_{i j} - \hat{Y}_i)^2
\] where \(\hat{Y}_i = b_0 + b_1 x_i\). This is the sum of squares
\(\operatorname{SS_E}\) as previously defined, which has
\(\operatorname{df_E}(R) = n-2 = 15-2 = 13\) degrees of freedom.

The sum of squares lack of fit is given by \[
  \operatorname{SS_{LF}}= \operatorname{SS_E}(R) - \operatorname{SS_E}(F) = \sum_{i=1}^{c} n_i(\bar{Y}_i - \hat{Y}_i)^2,
\] which has
\(\operatorname{df_E}(R) - \operatorname{df_E}(F) = (n-2) - (n-c) = c-2 = 3\)
degrees of freedom.

\begin{tcolorbox}[split=\f]
Part (c)
\tcblower
Compute $F_{\operatorname{LF}}^*$ and the $p$-value.
Provide an interpretation of your result.
\end{tcolorbox}

Intuitively, if \(\operatorname{SS_{LF}}\) is small, the difference
between the saturated model and the reduced model is small, which
suggests that reduced model is a good fit. Since the reduced model, the
linear regression model, uses more of the information in the sample, we
prefer it over the saturated model for previously stated reasons.

We formalize this intuition with the hypothesis test \begin{align*}
  H_0 &: \operatorname{E}(Y|x) = \beta_0 + \beta_1 x\\
  H_A &: \operatorname{E}(Y|x) \neq \beta_0 + \beta_1 x
\end{align*} and the general linear test statistic \begin{align*}
  F_{\text{LF}}^*
    &= \frac{\operatorname{SS_{LF}}/ (\operatorname{df_E}(R)-\operatorname{df_E}(F))}{\operatorname{SS_{PE}}/\operatorname{df_E}(F)}\\
    &= \frac{\operatorname{SS_{LF}}/ (c-2)}{\operatorname{SS_{PE}}/(n-c)}\\
    &= \frac{\operatorname{MS_{LF}}}{\operatorname{MS_{PE}}},
\end{align*} which under the null hypothesis is distributed as
\(F(c-2,n-c)\). The \(p\)-value of the test statistic is thus given by
\[
  \Pr\{F(c-2,n-c) \geq F_{\operatorname{LF}}^*\}.
\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data}\SpecialCharTok{$}\NormalTok{fact.hours }\OtherTok{=} \FunctionTok{as.factor}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{hours)}
\NormalTok{full.mod }\OtherTok{=} \FunctionTok{lm}\NormalTok{(conc }\SpecialCharTok{\textasciitilde{}}\NormalTok{ fact.hours }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{, }\AttributeTok{data=}\NormalTok{data)}
\FunctionTok{anova}\NormalTok{(reg.mod,full.mod)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Model 1: conc ~ hours
## Model 2: conc ~ fact.hours - 1
##   Res.Df    RSS Df Sum of Sq      F    Pr(>F)    
## 1     13 2.9247                                  
## 2     10 0.1574  3    2.7673 58.603 1.194e-06 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

We see that the ANOVA table provides all the necessary information. We
represent the information in the more familiar form with the following
table:

\begin{table}[ht]
\caption{Generalized linear test statistic (ANOVA)}
\centering
\begin{tabular}{|l|l|l||l|l|}
\hline
model                                                      & $\operatorname{df_E}$   & $\operatorname{SS_E}$   & loss fit            & \textbf{test statistic}\\
\hline
\hline
(R) $Y_{i j} = \beta_0 + \beta_1 x_i + \epsilon_{i j}$ & $n-2=13$ & $2.9247$ & $\operatorname{SS_{LF}}= 2.7673$                    & $F_{\operatorname{LF}}^*=58.603$\\
(F) $Y_{i j} = \mu_i + \epsilon_{i j}$                 & $n-c=10$ & $0.1573$ & $\operatorname{df_E}(\operatorname{LF}) = c-2 = 3$ & $p \approx .000$\\
\hline
\end{tabular}
\end{table}

We see that \(F_{\operatorname{LF}}^*=58.603\) which has a \(p\)-value
under the null hypothesis of \(.000\).

\hypertarget{interpretation}{%
\subsubsection{Interpretation}\label{interpretation}}

At a \(p\)-value \(\approx .000\), the data is not compatible with the
linear regression model given any reasonable significance level. We will
need a more flexible model.

\begin{tcolorbox}[split=\f]
Part (d)
\tcblower
Create a plot comparing the fitted values from the regression model with the
fitted values from the saturated model.
\end{tcolorbox}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{fact.hours,}
\NormalTok{     full.mod}\SpecialCharTok{$}\NormalTok{fitted.values,}
     \AttributeTok{type =} \StringTok{"b"}\NormalTok{,}
     \AttributeTok{ylab =} \StringTok{"concentration"}\NormalTok{,}
     \AttributeTok{xlab =} \StringTok{"hours"}\NormalTok{,}
     \AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\FunctionTok{min}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{conc),}\FunctionTok{max}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{conc)))}

\FunctionTok{abline}\NormalTok{(reg.mod}\SpecialCharTok{$}\NormalTok{coefficients,}\AttributeTok{col=}\StringTok{"red"}\NormalTok{)}
\FunctionTok{points}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{fact.hours,data}\SpecialCharTok{$}\NormalTok{conc,}\AttributeTok{pch=}\DecValTok{16}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw5_files/figure-latex/unnamed-chunk-6-1.pdf}

\end{document}
