% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
  \usepackage{amssymb}
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Regression Analysis - STAT 482 - Probem Set 8},
  pdfauthor={Alex Towell (atowell@siue.edu)},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{amsmath}
\usepackage{mathtools}
\usepackage{amsthm}
\usepackage{multirow}
\usepackage{booktabs}
\usepackage{minted}
\usepackage{color}
\usepackage{xcolor}
\usepackage{tcolorbox}
\usepackage{enumerate}
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Regression Analysis - STAT 482 - Probem Set 8}
\author{Alex Towell
(\href{mailto:atowell@siue.edu}{\nolinkurl{atowell@siue.edu}})}
\date{}

\begin{document}
\maketitle

\newcommand{\sos}[1]{\mathrm{SS_{#1}}}
\newcommand{\ms}[1]{\mathrm{MS_{#1}}}
\newcommand{\sd}{\operatorname{sd}}
\newcommand{\var}{\operatorname{var}}
\newcommand{\expect}{\operatorname{E}}
\newcommand{\corr}{\operatorname{cor}}
\newcommand{\cov}{\operatorname{cov}}
\newcommand{\se}{\operatorname{se}}
\newcommand{\eval}[2]{\left. #1 \right\vert_{#2}}
\newcommand{\degf}[1]{\mathrm{df_{#1}}}
\newcommand{\entropy}{\operatorname{H}}

\hypertarget{problem-1}{%
\section{Problem 1}\label{problem-1}}

\begin{quote}
We are interested in modeling the relationship among the predictor
variables for the body fat example. Specifically, we wish to model
midarm circumference (\(w\)) as a function of triceps skinfold thickness
(\(x_1\)) and thigh circumference (\(x_2\)). Refer to the data from
Table 7.1. The data for \(x_1\) is listed in the first column, \(x_2\)
is listed in the second column, and \(w\) is listed in the third column.
We are not interested in the body fat measurements, listed in the fourth
column, for this problem.
\end{quote}

\hypertarget{part-a}{%
\subsection{Part (a)}\label{part-a}}

\begin{quote}
Compute the correlation matrix for \(w\), \(x_1\), \(x_2\).
\end{quote}

We drop the last column of data, body fat, from the data set since we
are strictly looking at the relations between \(w\) (midarm), \(x_1\)
(triceps), and \(x_2\) (thigh).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{=} \FunctionTok{read.csv}\NormalTok{(}\StringTok{\textquotesingle{}TABLE0701.csv\textquotesingle{}}\NormalTok{)[,}\DecValTok{1}\SpecialCharTok{:}\DecValTok{3}\NormalTok{]}
\FunctionTok{head}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}rrr@{}}
\toprule
triceps & thigh & midarm\tabularnewline
\midrule
\endhead
19.5 & 43.1 & 29.1\tabularnewline
24.7 & 49.8 & 28.2\tabularnewline
30.7 & 51.9 & 37.0\tabularnewline
29.8 & 54.3 & 31.1\tabularnewline
19.1 & 42.2 & 30.9\tabularnewline
25.6 & 53.9 & 23.7\tabularnewline
\bottomrule
\end{longtable}

Here is the correlation matrix:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data.cor }\OtherTok{=} \FunctionTok{cor}\NormalTok{(data)}
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(}\FunctionTok{round}\NormalTok{(data.cor,}\AttributeTok{digits=}\DecValTok{3}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrrr@{}}
\toprule
& triceps & thigh & midarm\tabularnewline
\midrule
\endhead
triceps & 1.000 & 0.924 & 0.458\tabularnewline
thigh & 0.924 & 1.000 & 0.085\tabularnewline
midarm & 0.458 & 0.085 & 1.000\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{part-b}{%
\subsection{Part (b)}\label{part-b}}

\begin{quote}
Test for a marginal effect of \(x_2\) on \(w\) against a model which
includes no other input variables. (Compute the test statistic and
\(p\)-value.) Provide an interpretation of the result, stated in the
context of the problem.
\end{quote}

We test for a marginal effect of \(x_2\) on \(w\) by comparing the
effects model \(m_2\) with the no effects models \(m_0\) where

\begin{align*}
    m_0 &: w_i = \beta_0 + \epsilon_i\\
    m_2 &: w_i = \beta_0 + \beta_1 x_{2 i} + \epsilon_i.
\end{align*}

We compute the statistics with:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{names}\NormalTok{(data) }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"x1"}\NormalTok{,}\StringTok{"x2"}\NormalTok{,}\StringTok{"w"}\NormalTok{)}
\NormalTok{m0 }\OtherTok{=} \FunctionTok{lm}\NormalTok{(w}\SpecialCharTok{\textasciitilde{}}\DecValTok{1}\NormalTok{,  }\AttributeTok{data=}\NormalTok{data)}
\NormalTok{m2 }\OtherTok{=} \FunctionTok{lm}\NormalTok{(w}\SpecialCharTok{\textasciitilde{}}\NormalTok{x2, }\AttributeTok{data=}\NormalTok{data)}
\FunctionTok{print}\NormalTok{(}\FunctionTok{anova}\NormalTok{(m0,m2))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Model 1: w ~ 1
## Model 2: w ~ x2
##   Res.Df    RSS Df Sum of Sq    F Pr(>F)
## 1     19 252.73                         
## 2     18 250.92  1    1.8117 0.13 0.7227
\end{verbatim}

We see that \(F^*_2 = .130\) with \(p\)-value \(.723\).

This is a very large \(p\)-value, and so \(x_2\) (thigh) is not adding
much explanatory power compared to the model \(m_0\) with no explanatory
inputs. In other words, \(x_2\) provides very little predictive power of
\(w\) (midarm).

\hypertarget{interpretation}{%
\subsubsection{Interpretation}\label{interpretation}}

The observed data is compatible with the reduced (no effects) model
\(m_0\). It is not necessary to add thigh measurement (\(x_2\)) to the
no effects model for predicting midarm measurement (\(w\)).

\hypertarget{part-c}{%
\subsection{Part (c)}\label{part-c}}

\begin{quote}
Test for a partial effect of \(x_2\) on \(w\) against a model which
includes \(x_1\). (Compute the test statistic and \(p\)-value.) Provide
an interpretation of the result, stated in the context of the problem.
\end{quote}

We test for a partial effect of \(x_2\) on \(w\) given that \(x_1\) is
already in the model by comparing models \(m_1\) and \(m_{1 2}\) where

\begin{align*}
  m_1     &: w_i = \beta_0 + \beta_1 x_{i 1} + \epsilon_i,\\
  m_{1 2} &: w_i = \beta_0 + \beta_1 x_{i 1} + \beta_2 x_{2 i} + \epsilon_i.
\end{align*}

We compute the statistics with:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m1 }\OtherTok{=} \FunctionTok{lm}\NormalTok{(w}\SpecialCharTok{\textasciitilde{}}\NormalTok{x1, }\AttributeTok{data=}\NormalTok{data)}
\NormalTok{m12 }\OtherTok{=} \FunctionTok{lm}\NormalTok{(w}\SpecialCharTok{\textasciitilde{}}\NormalTok{x1}\SpecialCharTok{+}\NormalTok{x2, }\AttributeTok{data=}\NormalTok{data)}
\FunctionTok{anova}\NormalTok{(m1,m12)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}rrrrrr@{}}
\toprule
Res.Df & RSS & Df & Sum of Sq & F & Pr(\textgreater F)\tabularnewline
\midrule
\endhead
18 & 199.769500 & NA & NA & NA & NA\tabularnewline
17 & 2.416037 & 1 & 197.3535 & 1388.641 & 0\tabularnewline
\bottomrule
\end{longtable}

We see that \(F^*_{2|1} = 1388.641\) with a \(p\)-value \(.000\).

\hypertarget{interpretation-1}{%
\subsubsection{Interpretation}\label{interpretation-1}}

The observed data is not compatible with the reduced model \(m_1\). We
accept the addition of thigh circumference (\(x_2\)) as a predictor for
midarm circumference (\(w\)) to the model which already includes triceps
(\(x_1\)).

\hypertarget{part-d}{%
\subsection{Part (d)}\label{part-d}}

\begin{quote}
Fit the regression model for \(w\) which includes both \(x_1\) and
\(x_2\).
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m12}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = w ~ x1 + x2, data = data)
## 
## Coefficients:
## (Intercept)           x1           x2  
##      62.331        1.881       -1.608
\end{verbatim}

We estimate that \[
  \hat{w} = 62.331 + 1.881 x_1 - 1.608 x_2,
\] or using more descriptive names, \[
    \widehat{\texttt{\color{olive}midarm}} = 62.331 + 1.881 \times \texttt{\color{olive}triceps} - 1.608 \times \texttt{\color{olive}thigh}.
\]

\hypertarget{part-e}{%
\subsection{Part (e)}\label{part-e}}

\begin{quote}
What feature of multidimensional modeling is illustrated in this
problem?
\end{quote}

Multicollinearity, i.e., highly correlated inputs. Specifically, observe
that \(x_1\) and \(x_2\) are strongly positively correlated,
\(r_{1 2} = 0.9238425\), but \(x_1\) and \(x_2\) have, respectively, a
positive and negative partial effect on \(w\). The combination of these
partial effects and the correlation of \(x_1\) and \(x_2\) cancels out
their total effect on \(w\).

Deceptively, if we look at the scatterplots of \(x_1\) versus \(w\) and
\(x_2\) vs \(w\), they seem relatively uncorrelated. Investigating
relationships in higher dimensions requires higher level statistical
methods, such as regression analysis, rather than two-dimensional
methods and graphs.

\hypertarget{additional-comments}{%
\subsubsection{Additional comments}\label{additional-comments}}

Much of the data in science, e.g., astronomy, comes from observational
studies. Suppose we make an observation of the random sample
\(\mathcal{D} = \{(X_{i 1},X_{i 2},X_{i 3})\}_{i=1}^{n}\). If we are
interested in \(X_1\) and wish to, say, estimate its mean response, then
\(\expect(X_1|X_2,X_3)\) is better than \(\expect(X_1)\) since
\(\var(X_1|X_2,X_3) \leq \var(X_1)\).

A controlled experimental design can tell us much more, of course, but
we often must make do with what data we already have.

A question one might have is, should we take a sub-sample of
\(\mathcal{D}\) such that we better approximate an orthogonal design?
Honestly, this question seems a bit silly -- unless the data is garbage
(garbage in, garbage out), we should rarely throw away data. We are
generally better off being aware of the issues with multicollinearity
and doing our analysis based off the complete sample.

\hypertarget{problem-2}{%
\section{Problem 2}\label{problem-2}}

\begin{quote}
A small scale experiment is conducted to investigate the relationship
between crew productivity (\(y\)) and crew size (\(x_1\)) and bonus pay
(\(x_2\)). Refer to the data from Table 7.6.
\end{quote}

\hypertarget{part-a-1}{%
\subsection{Part (a)}\label{part-a-1}}

\begin{quote}
Provide a definition for an orthogonal design. Discuss an advantage to
using an orthogonal design.
\end{quote}

A design is orthogonal if \(X'X\) is diagonal.

Since \(X'X\) is diagonal, the covariance matrix \(\cov(b)\) is
diagonal, and thus the components of
\(b=(b_0 \; b_1 \; \ldots \; b_p)'\) are uncorrelated.

Since \(b\) is normally distributed, the mean vector and covariance
matrix of any subset of components may be obtained by simply dropping
the component indexes to be averaged over. Thus, for orthogonal designs,
regression coefficient estimates and variation explained by an input do
not depend on which other inputs are included in the model.

Finally, in orthogonal designs, marginal effects and partial effects are
the same.

\hypertarget{part-b-1}{%
\subsection{Part (b)}\label{part-b-1}}

\begin{quote}
Fit a multiple regression model using coded inputs. Compute the
coefficient estimate \(b_l\), the standard error \(\se(b_l)\), the
\(t\)-statistic, and the \(p\)-value, for each of the coded input
variables.
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{=} \FunctionTok{read.table}\NormalTok{(}\StringTok{\textquotesingle{}CH07TA06.txt\textquotesingle{}}\NormalTok{)}
\FunctionTok{names}\NormalTok{(data) }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"x1"}\NormalTok{,}\StringTok{"x2"}\NormalTok{,}\StringTok{"y"}\NormalTok{)}
\FunctionTok{attach}\NormalTok{(data)}

\NormalTok{c1 }\OtherTok{=} \DecValTok{2}\SpecialCharTok{*}\NormalTok{(x1}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(x1))}\SpecialCharTok{/}\NormalTok{(}\FunctionTok{range}\NormalTok{(x1)[}\DecValTok{2}\NormalTok{]}\SpecialCharTok{{-}}\FunctionTok{range}\NormalTok{(x1)[}\DecValTok{1}\NormalTok{])}
\NormalTok{c2 }\OtherTok{=} \DecValTok{2}\SpecialCharTok{*}\NormalTok{(x2}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(x2))}\SpecialCharTok{/}\NormalTok{(}\FunctionTok{range}\NormalTok{(x2)[}\DecValTok{2}\NormalTok{]}\SpecialCharTok{{-}}\FunctionTok{range}\NormalTok{(x2)[}\DecValTok{1}\NormalTok{])}

\NormalTok{orthog.mod }\OtherTok{=} \FunctionTok{lm}\NormalTok{(y}\SpecialCharTok{\textasciitilde{}}\NormalTok{c1}\SpecialCharTok{+}\NormalTok{c2)}
\FunctionTok{summary}\NormalTok{(orthog.mod)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = y ~ c1 + c2)
## 
## Residuals:
##      1      2      3      4      5      6      7      8 
##  1.625 -1.375 -1.625  1.375 -2.125  1.875  0.625 -0.375 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  50.3750     0.6638  75.889 7.53e-09 ***
## c1            5.3750     0.6638   8.097 0.000466 ***
## c2            4.6250     0.6638   6.968 0.000937 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.877 on 5 degrees of freedom
## Multiple R-squared:  0.958,  Adjusted R-squared:  0.9412 
## F-statistic: 57.06 on 2 and 5 DF,  p-value: 0.000361
\end{verbatim}

Both inputs are statistically significant, and so we select the full
additive model.

The computed values for the statistics may be read of the table. For
instance, we see that \(b_0 = 50.375\), \(b_1 = 5.375\), and
\(b_2 = 4.6250\).

\end{document}
