% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{amsmath}
\usepackage{mathtools}
\usepackage{amsthm}
\usepackage{multirow}
\usepackage{booktabs}
\usepackage{minted}
\usepackage{color}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Discrete Multivariate Analysis - 579 - Exam 2},
  pdfauthor={Alex Towell (atowell@siue.edu)},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Discrete Multivariate Analysis - 579 - Exam 2}
\author{Alex Towell
(\href{mailto:atowell@siue.edu}{\nolinkurl{atowell@siue.edu}})}
\date{}

\begin{document}
\maketitle

\newcommand{\var}{\operatorname{Var}}
\newcommand{\expect}{\operatorname{E}}
\newcommand{\corr}{\operatorname{Corr}}
\newcommand{\cov}{\operatorname{Cov}}
\newcommand{\ssr}{\operatorname{SSR}}
\newcommand{\se}{\operatorname{SE}}
\newcommand{\mat}[1]{\mathbf{#1}}
\newcommand{\RR}{\operatorname{RR}}
\newcommand{\eval}[2]{\left. #1 \right\vert_{#2}}

\hypertarget{problem-1}{%
\section{Problem 1}\label{problem-1}}

A genetic model predicts the ratio of green seedlings to yellow
seedlings to be \(3:1\). Consider data from a sample of \(n=1100\)
seedlings, where \(n_1 = 860\) is the number of green and \(n_2 = 240\)
is the number of yellow.

\hypertarget{part-a}{%
\subsection{Part (a)}\label{part-a}}

\fbox{Compute the statistic $X^2$ for testing the proposed model.}

The observed data models the binomial distribution \[
  n_g \sim \operatorname{BIN}(n, \pi_g)
\] where \(n_g\) and \(n_y = n - n_g\) are respectively the number of
green and yellow seedlings and \(\pi_g\) and \(\pi_y=1-\pi_g\) are
respectively the probability of a green and yellow seedling.

Under the null model, the odds of green seedlings to yellow seedlings is
\(3:1\), thus \[
  H_0 : \pi_{g 0} = 0.75 \;\; (\pi_{y 0} = 0.25).
\]

We perform a chi-squared test for goodness of fit whose test statistic
is given by \[
  X^2 = \frac{(n_g - \hat{m}_g}{\hat{m}_g} + \frac{(n_y - \hat{m}_y)^2}{\hat{m}_y}
\] where \(\hat{m}_g = n \pi_{g 0}\) and \(\hat{m}_y = \pi_{y 0}\).

The parameter space of the unconstrained binomial model is given by \[
  \vec{\pi}(\pi_g) = (\pi_g, 1-\pi_g)',
\] which has a dimension of \(\dim \vec{\pi} = 1\).

The \emph{null model}, which is the specified binomial
\(\pi_{g 0} = 0.75\), has the parameter space
\(\vec{\pi}_0 = (0.75,0.25)'\), which is just a \emph{point} with a
dimension of \(\dim \vec{\pi}_0 = 0\).

Thus, under the null model, \(X^2\) is distributed \(\chi^2\) with \[
  \operatorname{df} = \dim \vec{\pi} - \dim \vec{\pi}_0 = 1 - 0 = 1
\] degrees of freedom, denoted by \(\chi^2(1)\).

\hypertarget{answer}{%
\subsubsection{ANSWER}\label{answer}}

We compute the observed \(X^2\) statistic with:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{  obs }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\AttributeTok{ng=}\DecValTok{860}\NormalTok{,}\AttributeTok{ny=}\DecValTok{240}\NormalTok{)}
\NormalTok{  pi}\FloatTok{.0} \OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\AttributeTok{pi.g0=}\NormalTok{.}\DecValTok{75}\NormalTok{,}\AttributeTok{pi.y0=}\NormalTok{.}\DecValTok{25}\NormalTok{)}
\NormalTok{  x2\_test }\OtherTok{\textless{}{-}} \FunctionTok{multinomial\_goodness\_of\_fit}\NormalTok{(obs, pi}\FloatTok{.0}\NormalTok{)}\SpecialCharTok{$}\NormalTok{X2}
\NormalTok{  x2\_test}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $stat
## [1] 5.939394
## 
## $p
## [1] 0.01480611
## 
## $df
## [1] 1
\end{verbatim}

We see that \(X^2\) realizes the value \(X_0^2 = 5.939\).

\hypertarget{part-b}{%
\subsection{Part (b)}\label{part-b}}

\fbox{Determine the upper 10th percentile for the reference distribution.}

Assuming \(X^2 \sim \chi^2(1)\), the \((1-\alpha) \times 100 \%\)
percentile, denoted by \(\chi_{\alpha}^2(1)\), is given by solving the
equation \[
  \Pr[X^2 \geq \chi_{\alpha}^2(1)] = \alpha
\] for \(\chi_{\alpha}^2\).

We compute the \(10\)-th percentile with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{alpha }\OtherTok{\textless{}{-}} \FloatTok{0.10}
\NormalTok{q }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(}\FunctionTok{qchisq}\NormalTok{(}\AttributeTok{p=}\NormalTok{alpha,}\AttributeTok{df=}\NormalTok{x2\_test}\SpecialCharTok{$}\NormalTok{df,}\AttributeTok{lower.tail=}\ConstantTok{FALSE}\NormalTok{),}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{answer-1}{%
\subsubsection{ANSWER}\label{answer-1}}

We see that the \(10\)-th percentile is \(\chi^2_{0.1}(1) = 2.706\).

\hypertarget{part-c}{%
\subsection{Part (c)}\label{part-c}}

\fbox{Provide an interpretation of your result, stated in the context of the problem.}

\hypertarget{answer-2}{%
\subsubsection{ANSWER}\label{answer-2}}

We say that any observed statistic \(X_0^2\) with
\(\operatorname{df}=1\) greater than \(\chi^2_{0.1}(1) = 2.706\) is not
compatible with the null model at significance level \(\alpha = 0.1\).

Since the observed statistic \(X_0^2 = 5.939 > 2.706\), the null model,
which is the genetic theory where the ratio of green to yellow is
\(3:1\), is not compatible with the data.

\hypertarget{part-d}{%
\subsection{Part (d)}\label{part-d}}

\fbox{What are the shortcomings of hypothesis testing as a measure of evidence?}

\hypertarget{answer-3}{%
\subsubsection{ANSWER}\label{answer-3}}

Hypothesis testing, as a dichotomous measure of evidence, does not
provide as much information as a more quantitative evidence measure. For
instance, it does not provide information about effect size.

\hypertarget{part-e}{%
\subsection{Part (e)}\label{part-e}}

\fbox{Compute a $90\%$ confidence interval for $\pi_1$.}

The MLE of \(\pi_g\) is given by \(\hat{\pi}_g = \frac{n_g}{n}\). A
\((1-\alpha) \times 100 \%\) confidence interval for \(\pi_g\) is given
by \[
  \hat{\pi}_g \pm z_{\alpha/2} \hat\sigma_{\hat\pi_g}.
\] where
\(\hat\sigma_{\hat\pi_g} = \sqrt{\frac{\hat{\pi}_g (1-\hat{\pi}_g)}{n}}\).

\hypertarget{answer-4}{%
\subsubsection{ANSWER}\label{answer-4}}

Letting \(\alpha = 0.10\), the MLE and \(90\%\) confidence interval for
\(\pi_g\) is computed with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(obs)}
\NormalTok{mle }\OtherTok{\textless{}{-}}\NormalTok{ obs[}\DecValTok{1}\NormalTok{]}\SpecialCharTok{/}\NormalTok{n}

\NormalTok{alpha }\OtherTok{\textless{}{-}} \FloatTok{0.1}
\NormalTok{s2 }\OtherTok{\textless{}{-}}\NormalTok{ mle}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{mle)}\SpecialCharTok{/}\NormalTok{n}
\NormalTok{q }\OtherTok{\textless{}{-}} \FunctionTok{qnorm}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{alpha}\SpecialCharTok{/}\DecValTok{2}\NormalTok{)  }\CommentTok{\# should be around 1.645}
\NormalTok{conf }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(mle }\SpecialCharTok{{-}}\NormalTok{ q }\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(s2),}
\NormalTok{          mle }\SpecialCharTok{+}\NormalTok{ q }\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(s2))}
\end{Highlighting}
\end{Shaded}

We see that \(\hat{\pi}_g = 0.782\) and a \(90\%\) confidence interval
is \((0.761, 0.802)\).

\hypertarget{part-f}{%
\subsection{Part (f)}\label{part-f}}

\fbox{Provide an interpretation of your result, stated in the context of the problem.}

\hypertarget{answer-5}{%
\subsubsection{ANSWER}\label{answer-5}}

Based on the observed data, we estimate that the probability \(\pi_g\)
of a green strain is between 0.761 and 0.802.

As expected, the null model specifies a value for \(\pi_g\) (\(0.75\))
that is not contained in the computed confidence interval.

\hypertarget{part-g}{%
\subsection{Part (g)}\label{part-g}}

\fbox{Compute the statistic $G^2$ for testing the proposed model.}

The same reasoning as in part (a), except we use a different statistic
called the likelihood ratio statistic, \[
  G^2 = - 2 \log \Lambda
\] where \[
  \Lambda = \frac{l(\pi_{g 0})}{l(\hat{\pi}_g)}.
\] where \(\hat{\pi}_g\) is the maximum likelihood estimate \(n_g / n\).

This may be rewritten as \[
  G^2 = 2 \sum_{j=1}^{c} \log\left(\frac{n_j}{n \pi_{j 0}}\right).
\]

Under the null model, \(G^2\) is distributed \(\chi^2\) with \(1\)
degree of freedom.

\hypertarget{answer-6}{%
\subsubsection{ANSWER}\label{answer-6}}

We compute the observed \(G_2\) statistic with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{G2\_test }\OtherTok{\textless{}{-}} \FunctionTok{multinomial\_goodness\_of\_fit}\NormalTok{(obs,pi}\FloatTok{.0}\NormalTok{)}\SpecialCharTok{$}\NormalTok{G2}
\NormalTok{G2\_test}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $stat
## [1] 6.120841
## 
## $p
## [1] 0.01335972
## 
## $df
## [1] 1
\end{verbatim}

We see that \(G^2\) realizes the value 6.121.

\hypertarget{part-h}{%
\subsection{Part (h)}\label{part-h}}

\fbox{Compute the $p$-value for the proposed model.}

\hypertarget{answer-7}{%
\subsubsection{ANSWER}\label{answer-7}}

The reference distribution is the chi-squared distribution with \(1\)
degrees of freedom.

The \(p\)-value given \(1\) degree of freedom is defined as \[
  \text{$p$-value} = \operatorname{P}(G^2 > \chi^2(1)),
\] which was computed to be \(0.013\). (For comparison, the \(p\)-value
for the \(X^2\) test was \(0.015\).)

\hypertarget{part-i}{%
\subsection{Part (i)}\label{part-i}}

\fbox{Provide an interpretation of your result, stated in the context of the problem.}

\hypertarget{answer-8}{%
\subsubsection{ANSWER}\label{answer-8}}

According to the Fisher scale for interpreting \(p\)-values, a
\(p\)-value of \(0.01\) is considered \emph{strong} evidence against the
null model.

Since we obtained a \(p\)-value of slightly larger, the data provides
\emph{strong} evidence against the genetic theory positing that the
ratio of green to yellow seedlings is \(3:1\).

\hypertarget{part-j}{%
\subsection{Part (j)}\label{part-j}}

\fbox{What are the shortcomings of using a $p$-value as a measure of evidence?}

\hypertarget{answer-9}{%
\subsubsection{ANSWER}\label{answer-9}}

The \(p\)-value overstates evidence against the null model by comparing
the null model to the alternative model that is best supported by the
data.

\hypertarget{problem-2}{%
\section{Problem 2}\label{problem-2}}

Consider the results from a study on the relationship between dose level
and the severity of side effects. (Larger y values correspond to a more
severe response.)

Data:

\begin{longtable}[]{@{}llllll@{}}
\toprule\noalign{}
& \(y = 0\) & \(y = 1\) & \(y = 2\) & \(y = 3\) & \(y = 4\) \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
low dose & 6 & 9 & 6 & 3 & 1 \\
medium dose & 2 & 5 & 6 & 6 & 6 \\
high dose & 1 & 4 & 6 & 8 & 8 \\
\end{longtable}

\hypertarget{preliminary-analysis}{%
\subsection{Preliminary analysis}\label{preliminary-analysis}}

We model the cross-sectional data as being an observation of a
\(3 \times 5\) random matrix where the row levels, denoted by \(X\),
correspond to dosage level and the column levels, denoted by \(Y\),
correspond to severity of side effects. The elements (cells) of the
random matrix are jointly sampled from the multinomial distribution \[
  \{n_{i j}\} \sim \operatorname{MULT}(n, \{\pi_{i j}\}).
\] where \(n_{i j}\) denotes the \((i,j)\)-th element of the random
matrix, \(\pi_{i j}\) denotes the parameter that specifies the joint
probability \(\Pr(X=i,Y=j)\), and \(n\) denotes the number of trials.

The full model has a parameter space of dimension
\(3 \times 5 - 1 = 14\).

\hypertarget{part-a-1}{%
\subsection{Part (a)}\label{part-a-1}}

\fbox{\begin{minipage}{.95\columnwidth}
Compute the statistic $X^2$ and the $p$-value for testing the model with
independence between dose level and response severity.
Provide an interpretation, stated in the context of the problem.
\end{minipage}}

We consider a simpler model than the full model where \(X\) and \(Y\)
are independent, i.e.,
\(\pi_{i j\,0} = \Pr(X=i)\Pr(Y=j) = \pi_{i+}\pi_{+j}\). Since we are
only free to specify \(\pi_{i+}\) and \(\pi_{+j}\), the parameter space
of the independence model is of dimension \((3-1) + (5-1) = 6\).

To decide whether the observed data is compatible with \(X\) and \(Y\)
being independent, we perform the hypothesis test \[
  H_0 : \{\pi_{i j}\} = \{\pi_{i j\,0}\}.
\]

An estimator of \(\pi_{i+}\) is \(\hat{\pi}_{i+} = n_{i+}/n\) and an
estimator of \(\hat{\pi}_{+j}\) is \(n_{+j}/n\), therefore an estimator
of \(\pi_{i j\,0}\) is given by \[
  \hat{\pi}_{i j\,0} = \hat{\pi}_{i+} \hat{\pi}_{+j} = \frac{n_{i+}n_{+j}}{n^2}.
\] We perform a chi-square test for independence. The test statistic is
given by \[
  X^2 = \sum_{i=1}^{4} \frac{(n_{i j} - \hat{m}_{i j})^2}{\hat{m}_{i j}}
\] where \(\hat{m}_{i j} = n \hat{\pi}_{i j\,0}\). Asymptotically,
\(X^2\) is distributed \(\chi^2\) with \(14 - 6 = 8\) degrees of
freedom.

\hypertarget{answer-10}{%
\subsubsection{ANSWER}\label{answer-10}}

We compute the observed value of \(X^2\) and its \(p\)-value with the
following R code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{obs }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{6}\NormalTok{,}\DecValTok{9}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{1}\NormalTok{,}
                \DecValTok{2}\NormalTok{,}\DecValTok{5}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{6}\NormalTok{,}
                \DecValTok{1}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{8}\NormalTok{,}\DecValTok{8}\NormalTok{), }\AttributeTok{nrow=}\DecValTok{3}\NormalTok{, }\AttributeTok{byrow=}\ConstantTok{TRUE}\NormalTok{)}
\FunctionTok{colnames}\NormalTok{(obs) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"y=0"}\NormalTok{,}\StringTok{"y=1"}\NormalTok{,}\StringTok{"y=2"}\NormalTok{,}\StringTok{"y=3"}\NormalTok{,}\StringTok{"y=4"}\NormalTok{)}
\FunctionTok{rownames}\NormalTok{(obs) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"low dose"}\NormalTok{,}\StringTok{"medimum dose"}\NormalTok{,}\StringTok{"high dose"}\NormalTok{)}
\NormalTok{ind\_test }\OtherTok{\textless{}{-}} \FunctionTok{multinomial\_goodness\_of\_fit\_independence\_test}\NormalTok{(obs)}\SpecialCharTok{$}\NormalTok{X2}
\NormalTok{ind\_test}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $stat
## [1] 14.35678
## 
## $p
## [1] 0.07292708
## 
## $df
## [1] 8
\end{verbatim}

The test statistic \(X^2\) realizes the value \(14.357\) whose
\(p\)-value is 0.073. We consider this \(p\)-value to be moderate
evidence against the null model. Stated differently, the observed data
is moderately incompatible with the independence model.

\hypertarget{part-b-1}{%
\subsection{Part (b)}\label{part-b-1}}

\fbox{\begin{minipage}{.95\columnwidth}
Now compute the statistic $Z$ and the $p$-value for testing the independence
model using the correlation estimate $\hat\gamma$.
Provide an interpretation, stated in the context of the problem.
\end{minipage}}

Under the assumption of a monotonic association between \(X\) and \(Y\),
if \(X\) and \(Y\) are independent then their \(\gamma\) correlation is
zero. To decide whether the observed data is compatible with \(X\) and
\(Y\) being independent, we perform the hypothesis test \[
  H_0 : \gamma = 0.
\]

The test statistic is given by \[
  Z^* = \frac{\hat\gamma-0}{\hat\sigma(\hat\gamma)},
\] which is normally distributed \(\mathcal{N}(0,1)\) under the null
model.

\hypertarget{answer-11}{%
\subsubsection{ANSWER}\label{answer-11}}

We compute \(Z^*\) and \(p\)-value with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gamma\_test }\OtherTok{\textless{}{-}} \FunctionTok{independence\_test\_monotonic\_association}\NormalTok{(obs)}
\end{Highlighting}
\end{Shaded}

The observed \(Z^*\) is 4.402 and its \(p\)-value is less than
\(0.001\), which we consider to be very strong evidence against the
independence model.

That is, the observed data provides very strong evidence against the
independence model under the assumption of a monotonic association.

\hypertarget{part-c-1}{%
\subsection{Part (c)}\label{part-c-1}}

\fbox{\begin{minipage}{.8\textwidth}
Explain why a monotonic association model is better than a general association
model in this example.
\end{minipage}}

\hypertarget{answer-12}{%
\subsubsection{ANSWER}\label{answer-12}}

Estimates for simpler models have smaller variances than for estimates
from more complicated models.

\hypertarget{problem-3}{%
\section{Problem 3}\label{problem-3}}

Consider the results from a prospective study on the relationship
between sex and hair color.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{obs }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{75}\NormalTok{,}\DecValTok{16}\NormalTok{,}\DecValTok{9}\NormalTok{,}\DecValTok{120}\NormalTok{,}\DecValTok{64}\NormalTok{,}\DecValTok{16}\NormalTok{),}\AttributeTok{nrow=}\DecValTok{2}\NormalTok{,}\AttributeTok{byrow=}\ConstantTok{TRUE}\NormalTok{)}
\FunctionTok{dimnames}\NormalTok{(obs) }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{(}\AttributeTok{sex=}\FunctionTok{c}\NormalTok{(}\StringTok{"male"}\NormalTok{,}\StringTok{"female"}\NormalTok{),}
                      \AttributeTok{hc.level=}\FunctionTok{c}\NormalTok{(}\StringTok{"dark"}\NormalTok{,}\StringTok{"blonde"}\NormalTok{,}\StringTok{"red"}\NormalTok{))}
\FunctionTok{print}\NormalTok{(obs)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         hc.level
## sex      dark blonde red
##   male     75     16   9
##   female  120     64  16
\end{verbatim}

\hypertarget{part-a-2}{%
\subsection{Part (a)}\label{part-a-2}}

\fbox{\begin{minipage}{.95\columnwidth}
State the likelihood function for data from a product multinomial sample.
State the equation for the maximum likelihood estimate $\hat{\pi}^{(F)}_{j|i}$
under the full model.
State the equation for the maximum likelihood estimate $\hat{\pi}^{(I)}_{j|i}$
under the independence model.
\end{minipage}}

\hypertarget{answer-13}{%
\subsubsection{ANSWER}\label{answer-13}}

In a prospective study, each row of the table represents an independent
multinomial. Thus, the data model is given by \[
\{n_{i j}\} \sim \operatorname{PROD\_MULT}(\{n_{i+}\},\{\pi_{j|i}\}).
\]

We are given a table of \(I=2\) rows and \(J=3\) columns, and thus we
have \(I\) independent multinomials. Therefore, the likelihood function
is given by \[
  l(\{\pi_{j|i}\}) = \prod_{i=1}^{I} \frac{n_{i+}!}{\prod_{j=1}^{J} n_{i j}!}
    \prod_{j=1}^{J} \pi_{j|i}^{n_{i j}}.
\] Observe that \[
  l(\{\pi_{j|i}\}) \propto \prod_{i=1}^{I} \prod_{j=1}^{J} \pi_{j|i}^{n_{i j}}.
\]

Under the full model, the maximum likelihood of \(\pi_{j|i}\) is given
by \[
  \hat{\pi}_{j | i}^{(F)} = \frac{n_{i j}}{n_{i+}}
\] and under the independence model it is given by \[
  \hat{\pi}_{j | i}^{(I)} = \frac{n_{+j}}{n}
\] for \(i \in \{1,2\}\) and \(j \in \{1,2,3\}\).

\hypertarget{part-b-2}{%
\subsection{Part (b)}\label{part-b-2}}

\fbox{Compute the table of expected counts $\hat{m}$ under the independence model.}

The expected count \(\hat{m}_{i j}\) under the independence model is
given by \[
  \hat{m}_{i j} = \frac{n_{i+}n_{+j}}{n} = n_{i+} \hat{\pi}_{j|i}^{(I)}.
\]

\hypertarget{answer-14}{%
\subsubsection{ANSWER}\label{answer-14}}

We use the R function \(\operatorname{chisq.test}\) to compute the
expected cell counts \(\{\hat{m}_{i j}\}\):

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m.hat }\OtherTok{\textless{}{-}} \FunctionTok{chisq.test}\NormalTok{(obs,}\AttributeTok{correct =} \ConstantTok{FALSE}\NormalTok{)}\SpecialCharTok{$}\NormalTok{expected}
\FunctionTok{print}\NormalTok{(}\FunctionTok{round}\NormalTok{(m.hat,}\DecValTok{3}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         hc.level
## sex      dark blonde    red
##   male     65 26.667  8.333
##   female  130 53.333 16.667
\end{verbatim}

\hypertarget{part-c-2}{%
\subsection{Part (c)}\label{part-c-2}}

\fbox{\begin{minipage}{.95\columnwidth}
Compute the statistic $G^2$ and the $p$-value for testing the independence model.
Provide an interpretation of your result, stated in the context of the problem.
\end{minipage}}

In the full model, the paramter space is given by \[
  \vec{\pi}^{(F)}(\theta_1,\theta_2, \theta_3, \theta_4) =
  \begin{pmatrix}
    \pi_{1|1} = \theta_1  &  \pi_{2|1} = \theta_2 &   \pi_{3|1} = 1-\theta_1-\theta_2\\
    \pi_{1|2} = \theta_3  &  \pi_{2|2} = \theta_4 &   \pi_{3|2} = 1-\theta_3-\theta_4
  \end{pmatrix}
\] which is of dimension \(I(J-1) = 4\) and under the independence
model, the parameter space is \[
  \vec{\pi}^{(I)}(\theta_1,\theta_2) =
  \begin{pmatrix}
    \pi_{1|1} = \theta_1  &  \pi_{2|1} = \theta_2 &   \pi_{3|1} = 1-\theta_1-\theta_2\\
    \pi_{1|2} = \theta_1  &  \pi_{2|2} = \theta_2 &   \pi_{3|2} = 1-\theta_1-\theta_2
  \end{pmatrix}
\] which is of dimension \(J-1=2\). Thus, under the independence model,
\(G^2\) is distributed \(\chi^2\) with
\(\operatorname{df} = I(J-1) - (J-1) = (J-1)(I-1) = 2\)

\hypertarget{answer-15}{%
\subsubsection{ANSWER}\label{answer-15}}

We compute \(G^2\) from the observed counts \(\{n_{i j}\}\) and the
expected counts \(\{\hat{m}_{i j}\}\):

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{I }\OtherTok{\textless{}{-}} \FunctionTok{dim}\NormalTok{(obs)[}\DecValTok{1}\NormalTok{]}
\NormalTok{J }\OtherTok{\textless{}{-}} \FunctionTok{dim}\NormalTok{(obs)[}\DecValTok{2}\NormalTok{]}
\NormalTok{G2 }\OtherTok{\textless{}{-}} \DecValTok{2}\SpecialCharTok{*}\FunctionTok{sum}\NormalTok{(obs}\SpecialCharTok{*}\FunctionTok{log}\NormalTok{(obs}\SpecialCharTok{/}\NormalTok{m.hat))}
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ (I}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{*}\NormalTok{(J}\DecValTok{{-}1}\NormalTok{)}
\NormalTok{p.value }\OtherTok{\textless{}{-}} \FunctionTok{pchisq}\NormalTok{(G2,df,}\AttributeTok{lower.tail =} \ConstantTok{FALSE}\NormalTok{)}

\FunctionTok{print}\NormalTok{(}\FunctionTok{round}\NormalTok{(G2,}\DecValTok{3}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9.325
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{round}\NormalTok{(p.value,}\DecValTok{3}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.009
\end{verbatim}

We obtain a \(p\)-value around \(0.01\), which we consider to be strong
evidence against the independence model (the data supports the general
association model). That is to say, the conditional distribution \[
  \Pr(\text{hair color} \,|\, \text{sex} = \text{male})
\] and \[
  \Pr(\text{hair color} \,|\, \text{sex} = \text{female}).
\] are different.

\hypertarget{part-d-1}{%
\subsection{Part (d)}\label{part-d-1}}

\fbox{\begin{minipage}{.95\columnwidth}
Provide an interpretation of the association, stated in the context of the problem,
by comparing the observed counts with the expected counts.
\end{minipage}}

\hypertarget{answer-16}{%
\subsubsection{ANSWER}\label{answer-16}}

We display a table comparing expected and observed such that if the
observed is less than the expected, display \(-1\), and if observed is
greater than expected, display a \(1\):

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{sign}\NormalTok{(obs}\SpecialCharTok{{-}}\NormalTok{m.hat))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         hc.level
## sex      dark blonde red
##   male      1     -1   1
##   female   -1      1  -1
\end{verbatim}

The observed data is compatible with a model where males are more likely
to have dark or red hair (and less likely to have blonde hair) and
females are more likely to have blonde hair (and less likely to have
dark or red hair).

\hypertarget{problem-4}{%
\section{Problem 4}\label{problem-4}}

According to the Hardy-Weinberg model, the number of flies resulting
from a crossing of genetic traits are in categories \(1\), \(2\), \(3\)
with probabilities \begin{align*}
  \pi_{1 o}(\theta) &= (1-\theta)^2\\
  \pi_{2 o}(\theta) &= 2\theta(1-\theta)\\
  \pi_{3 o}(\theta) &= \theta^2
\end{align*}

\hypertarget{part-a-3}{%
\subsection{Part (a)}\label{part-a-3}}

\fbox{\begin{minipage}{.95\columnwidth}
Show that the maximum likelihood estimator of $\theta$ from data $(n_1,n_2,n_3) \sim \operatorname{MULT}(n,\pi_1,\pi_2,\pi_3)$ is
$$
  \hat\theta = \frac{n_2 + 2 n_3}{2n}.
$$
\end{minipage}}

We assume the data model is given by \[
  (n_1,n_2,n_3) \sim \operatorname{MULT}(n, \pi_1, \pi_2, \pi_3)
\] where \(n_j\) denotes the number of flies in category \(j\) and
\(\pi_j\) denotes the probability a fly is in category \(j\).

Under the specified model, the likelihood function is given by \[
  \operatorname{L}(\theta) \propto \prod_{j=1}^{3} \pi_{j o}(\theta)^{n_j}
\] and the kernel of the log-likelihood function is given by
\begin{align*}
  l(\theta)
    &= \sum_{j=1}^{3} n_j \log \pi_{j o}(\theta)\\
    &= n_1 \log \pi_{1 o}(\theta) +
       n_2 \log \pi_{2 o}(\theta) +
       n_3 \log \pi_{3 o}(\theta)\\
    &= n_1 \log (1-\theta)^2 +
       n_2 \log 2 \theta(1-\theta) +
       n_3 \log \theta^2\\
    &= 2 n_1 \log (1-\theta) + n_2 \log \theta + n_2 \log(1-\theta)
      + 2 n_3 \log \theta + \rm{const}\\
    &= (2 n_1 + n_2) \log (1-\theta) + ( n_2 + 2 n_3)\log \theta + \rm{const}.
\end{align*}

The derivative of the log-likelihood is thus given by \[
  \frac{d l}{d \theta} =
    -\frac{2 n_1 + n_2}{1-\theta} + 
    \frac{n_2 + 2 n_3}{\theta}.
\]

The ML estimate of \(\theta\) is given by \[
  \left. \frac{d l}{d \theta} \right\vert_{\hat\theta} = 0.
\] Solving for \(\hat\theta\), we see that \[
  \frac{2 n_1 + n_2}{1-\hat\theta} = \frac{n_2 + 2 n_3}{\hat\theta}.
\] Next, we take the reciprocal of both sides, \[
  \frac{1-\hat\theta}{2 n_1 + n_2} = \frac{\hat\theta}{n_2 + 2 n_3}.
\] Expanding the LHS, we get \[
  \frac{1}{2 n_1 + n_2} - \frac{\hat\theta}{2 n_1 + n_2} = \frac{\hat\theta}{n_2 + 2 n_3}
\] which may be rewritten as \[
  \hat\theta \left(\frac{1}{2 n_1 + n_2} + \frac{1}{n_2 + 2 n_3}\right) = \frac{1}{2 n_1 + n_2}.
\] Dividing both sides by the part in parentheses, we get \[
  \hat\theta = \frac{1}{(2 n_1 + n_2) \left(\frac{1}{2 n_1 + n_2} + \frac{1}{n_2 + 2 n_3}\right)},
\] which simplifies to \[
  \hat\theta = \frac{1}{1 + \frac{2 n_1 + n_2}{n_2 + 2 n_3}} = \frac{1}{\frac{2 n_3 + 2 n_1 + 2 n_2}{n_2 + 2 n_3}}.
\] Performing the division, we get the simplification \[
  \hat\theta = \frac{n_2 + 2 n_3}{2(n_3 + n_1 + n_2)}.
\]

\hypertarget{answer-17}{%
\subsubsection{ANSWER}\label{answer-17}}

Observe that \(n_1 + n_2 + n_3\) is \(n\), thus \[
  \hat\theta = \frac{n_2 + 2 n_3}{2 n}.
\]

\hypertarget{part-b-3}{%
\subsection{Part (b)}\label{part-b-3}}

\fbox{\begin{minipage}{.95\columnwidth}
Suppose we observe data $n_1 = 40$, $n_2 = 50$, $n_3 = 10$ from a sample of size $n = 100$.
Compute the mle $\hat\theta$ and the estimated category probabilities $\pi_0(\hat\theta)$.
\end{minipage}}

Using the MLE equation, we compute the result using R:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\DecValTok{40}\NormalTok{,}\DecValTok{50}\NormalTok{,}\DecValTok{10}\NormalTok{)}
\NormalTok{mle }\OtherTok{\textless{}{-}}\NormalTok{ (n[}\DecValTok{2}\NormalTok{] }\SpecialCharTok{+} \DecValTok{2}\SpecialCharTok{*}\NormalTok{n[}\DecValTok{3}\NormalTok{])}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(n)}
\end{Highlighting}
\end{Shaded}

\hypertarget{answer-18}{%
\subsubsection{ANSWER}\label{answer-18}}

We see that \[
  \hat\theta = 0.7.
\] Plugging in this result, \[
  \vec{\pi}_{o}(\hat\theta) = (
    (1-\hat\theta)^2,
    2\hat\theta(1-\hat\theta),
    \hat\theta^2)'
\] which we compute with R:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pi0.hats }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{((}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{mle)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{,}
            \DecValTok{2}\SpecialCharTok{*}\NormalTok{mle}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{mle),}
\NormalTok{            mle}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

We see that \(\vec{\pi}_{o}(\hat\theta) = (0.09, 0.42, 0.49)'\).

\hypertarget{part-c-3}{%
\subsection{Part (c)}\label{part-c-3}}

\fbox{\begin{minipage}{.95\columnwidth}
Compute the statistic $G^2$ and the $p$-value for testing the Hardy-Weinberg model.
Provide an interpretation of your result, stated in the context of the problem.
\end{minipage}}

\hypertarget{answer-19}{%
\subsubsection{ANSWER}\label{answer-19}}

The parameter space of the Hardy-Weinberg model is a function of a
single parameter \(\theta\) and thus has a dimension of \(1\). The
parameter space of the full model is \(2\). Thus, the reference
distribution is \(\chi^2\) with \(\operatorname{df} = 2 - 1 = 1\)
degrees of freedom.

The following R code computes the realization of \(G^2\), denoted by
\(G_0^2\), and its \(p\)-value:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hardy\_test }\OtherTok{\textless{}{-}} \FunctionTok{multinomial\_goodness\_of\_fit}\NormalTok{(}\AttributeTok{obs=}\NormalTok{n,}\AttributeTok{pi.0=}\NormalTok{pi0.hats,}\AttributeTok{t=}\DecValTok{1}\NormalTok{)}\SpecialCharTok{$}\NormalTok{G2}
\NormalTok{hardy\_test}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $stat
## [1] 104.983
## 
## $p
## [1] 1.231867e-24
## 
## $df
## [1] 1
\end{verbatim}

We see that \(G_0^2 = 104.983\) with a \(p\)-value less than \(0.001\),
which we consider to be very strong evidence against the Hardy-Weinberg.

\hypertarget{library-of-test-functions}{%
\section{Library of test functions}\label{library-of-test-functions}}

\inputminted{R}{test_functions.R}

\end{document}
