% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{amsmath}
\usepackage{mathtools}
\usepackage{amsthm}
\usepackage{multirow}
\usepackage{booktabs}
\usepackage{minted}
\usepackage{color}
\usepackage{xcolor}
\usepackage{tcolorbox}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Regression Analysis - STAT 482 - HW \#3},
  pdfauthor={Alex Towell (atowell@siue.edu)},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Regression Analysis - STAT 482 - HW \#3}
\author{Alex Towell
(\href{mailto:atowell@siue.edu}{\nolinkurl{atowell@siue.edu}})}
\date{}

\begin{document}
\maketitle

\newsavebox{\selvestebox}
\newenvironment{colbox}[1]
  {\newcommand\colboxcolor{#1}%
   \begin{lrbox}{\selvestebox}%
   \begin{minipage}{\dimexpr\columnwidth-2\fboxsep\relax}}
  {\end{minipage}\end{lrbox}%
   \begin{center}
   \colorbox[HTML]{\colboxcolor}{\usebox{\selvestebox}}
   \end{center}}

\newcommand{\ssx}{\rm{SS}_x}
\newcommand{\var}{\operatorname{V}}
\newcommand{\sd}{\operatorname{sd}}
\newcommand{\expect}{\operatorname{E}}
\newcommand{\corr}{\operatorname{Corr}}
\newcommand{\cov}{\operatorname{Cov}}
\newcommand{\ssr}{\operatorname{ssr}}
\newcommand{\se}{\operatorname{se}}
\newcommand{\mat}[1]{\mathbf{#1}}
\newcommand{\eval}[2]{\left. #1 \right\vert_{#2}}

Refer to the data from Exercise 1.20

Data has been collected on \(45\) calls for routine maintenance. The
goal is to explore the relationship between the number of copiers
serviced \((x)\) and the time in minutes spent to complete the service
\((y)\). Let \(x_h = 3\) copiers.

\hypertarget{part-1}{%
\section{Part (1)}\label{part-1}}

\fbox{Compute a confidence interval for $\mu_h$.}

\(\mu_h\) is the mean response \(\operatorname{E}(Y_h|x_h=3)\). A
confidence interval for \(\mu_h\) is given by \[
  \hat{Y}_h \pm t_{\alpha/2,n-2} \operatorname{se}(\hat{Y}_h).
\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{alpha }\OtherTok{=}\NormalTok{ .}\DecValTok{05}
\NormalTok{x.h }\OtherTok{=} \DecValTok{3}
\NormalTok{data }\OtherTok{=} \FunctionTok{read.table}\NormalTok{(}\StringTok{\textquotesingle{}CH01PR20.txt\textquotesingle{}}\NormalTok{)}
\FunctionTok{colnames}\NormalTok{(data)}\OtherTok{=}\FunctionTok{c}\NormalTok{(}\StringTok{"time"}\NormalTok{,}\StringTok{"copiers"}\NormalTok{)}
\NormalTok{mod }\OtherTok{=} \FunctionTok{lm}\NormalTok{(time}\SpecialCharTok{\textasciitilde{}}\NormalTok{copiers, }\AttributeTok{data=}\NormalTok{data)}
\FunctionTok{predict}\NormalTok{(mod,}\AttributeTok{level=}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{alpha,}\FunctionTok{data.frame}\NormalTok{(}\AttributeTok{copiers=}\NormalTok{x.h),}\AttributeTok{interval=}\StringTok{"confidence"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        fit     lwr      upr
## 1 44.52559 41.1476 47.90357
\end{verbatim}

We see that a CI for \(\mu_h\) is given by \([44.526,47.904]\).

\hypertarget{part-2}{%
\section{Part (2)}\label{part-2}}

\fbox{Compute a prediction interval for $Y_{h(new)}$.}

We denote \(Y|X=x_h\) by \(Y_h\). Assume \[
  Y_h \sim \mathcal{N}(\beta_0 + \beta_1 x_h, \sigma^2).
\] Then, if we wish to predict \(Y_h\) with \((\beta_0,\beta_1,\sigma)\)
known, the interval \[
  \beta_0 + \beta_1 x \pm z_{\alpha/2} \sigma.
\] includes the observed value of \(Y_h\) with probability \(1-\alpha\).
For predicting a single outcome \(Y_h\), the uncertainty of the
prediction is quantified by \(\operatorname{V}(Y_h) = \sigma^2\). For a
given \(\alpha\), the smaller the variance the smaller the interval.

However, if \((\beta_0,\beta_1,\sigma^2)'\) is unknown, we have the
additional source uncertainty due to a random sample \(\{(Y_h,x_h)\}\)
being used to estimate \((\beta_0,\beta_1,\sigma^2)'\).

Let \texttt{pred} = \(P_h = Y_{h(\rm{new})} - \hat{Y}_h\) denote the
random \emph{prediction error}. Then, \(\operatorname{E}(P_h) = 0\) and
\begin{align*}
  \operatorname{V}(P_h) &= \operatorname{V}(Y_{h(\rm{new})}) + \operatorname{V}(\hat{Y}_h)\\
            &= \sigma^2\left[1 + \frac{1}{n} + \frac{(x_h - \bar{x})^2}{\rm{SS}_x}\right].
\end{align*}

Since we do not know \(\sigma^2\), we estimate it with \(\rm{MSE}\) and
thus a prediction interval for \(Y_{h(\rm{new})}\) is given by \[
  \hat{Y}_h \pm t_{\alpha/2,n-2} \hat{\operatorname{sd}}(P_h)
\] where \[
  \hat{\operatorname{sd}}(P_h) = \sqrt{\rm{MSE}\left(1 + \frac{1}{n} + \frac{(x_h-\bar{x})^2}{\rm{SS}_x}\right)}.
\]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{predict}\NormalTok{(mod,}\FunctionTok{data.frame}\NormalTok{(}\AttributeTok{copiers=}\DecValTok{3}\NormalTok{),}\AttributeTok{level=}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{alpha,}\AttributeTok{interval=}\StringTok{"predict"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        fit      lwr      upr
## 1 44.52559 26.23515 62.81603
\end{verbatim}

We see that the PI for \(Y_{h(\rm{new})}\) is given by
\([26.235,62.816]\).

\hypertarget{part-3}{%
\section{Part (3)}\label{part-3}}

\fbox{\begin{minipage}{\textwidth}
Explain the difference between a confidence interval and a prediction interval,
stated in the context of the problem.
\end{minipage}}

A confidence interval is for the mean service time for all service calls
with \(3\) copiers to service.

A prediction interval is for the service time of a single service call
with \(3\) copiers to service.

\hypertarget{part-4}{%
\section{Part (4)}\label{part-4}}

\fbox{Let $m=10$. Compute a prediction interval for $\bar{Y}_{h(\rm{new})}$.}

Let \texttt{pred.mean} =
\(\bar{P}_h = \bar{Y}_{h(\rm{new})} - \hat{Y}_h\) denote the random
\emph{prediction error}. Then, \(\operatorname{E}(\bar{P}_h) = 0\) and
\begin{align*}
  \operatorname{V}(\bar{P}_h)
    &= \operatorname{V}(\bar{Y}_{h(\rm{new})}) + \operatorname{V}(\hat{Y}_h)\\
    &= \sigma^2 \left[\frac{1}{m} + \frac{1}{n} + \frac{(x_h - \bar{x})^2}{\rm{SS}_x}\right].
\end{align*}

Since we do not know \(\sigma^2\), we estimate it with \(\rm{MSE}\) and
thus a prediction interval for \(\bar{Y}_{h(\rm{new})}\) is given by \[
  \hat{Y}_h \pm t_{\alpha/2,n-2} \hat{\operatorname{sd}}(\bar{P}_h)
\] where \[
  \hat{\operatorname{sd}}(\bar{P}_h) = \sqrt{\rm{MSE}\left(\frac{1}{m} + \frac{1}{n} + \frac{(x_h-\bar{x})^2}{\rm{SS}_x}\right)}
\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{b0 }\OtherTok{=}\NormalTok{ mod}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{1}\NormalTok{]; }\FunctionTok{names}\NormalTok{(b0) }\OtherTok{=} \ConstantTok{NULL}
\NormalTok{b1 }\OtherTok{=}\NormalTok{ mod}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{2}\NormalTok{]; }\FunctionTok{names}\NormalTok{(b1) }\OtherTok{=} \ConstantTok{NULL}

\NormalTok{residual }\OtherTok{=}\NormalTok{ mod}\SpecialCharTok{$}\NormalTok{residuals}
\NormalTok{n }\OtherTok{=} \FunctionTok{length}\NormalTok{(residual)}
\NormalTok{sse }\OtherTok{=} \FunctionTok{sum}\NormalTok{(residual}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{mse }\OtherTok{=}\NormalTok{ sse }\SpecialCharTok{/}\NormalTok{ (n}\DecValTok{{-}2}\NormalTok{)}
\NormalTok{x }\OtherTok{=}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{copiers}

\NormalTok{x.bar }\OtherTok{=} \FunctionTok{mean}\NormalTok{(x)}
\NormalTok{ssx }\OtherTok{=} \FunctionTok{sum}\NormalTok{((x}\SpecialCharTok{{-}}\NormalTok{x.bar)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}

\NormalTok{y.hat }\OtherTok{=}\NormalTok{ b0 }\SpecialCharTok{+}\NormalTok{ b1}\SpecialCharTok{*}\NormalTok{x.h }
\NormalTok{m }\OtherTok{=} \DecValTok{10}
\NormalTok{var.pred.mean }\OtherTok{=}\NormalTok{ mse}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{/}\NormalTok{m }\SpecialCharTok{+} \DecValTok{1}\SpecialCharTok{/}\NormalTok{n }\SpecialCharTok{+}\NormalTok{ (x.h}\SpecialCharTok{{-}}\NormalTok{x.bar)}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{/}\NormalTok{ssx)}

\NormalTok{lower.ynew }\OtherTok{=}\NormalTok{ y.hat }\SpecialCharTok{{-}} \FunctionTok{qt}\NormalTok{(alpha}\SpecialCharTok{/}\DecValTok{2}\NormalTok{,n}\DecValTok{{-}2}\NormalTok{,}\AttributeTok{lower.tail=}\NormalTok{F)}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(var.pred.mean)}
\NormalTok{upper.ynew }\OtherTok{=}\NormalTok{ y.hat }\SpecialCharTok{+} \FunctionTok{qt}\NormalTok{(alpha}\SpecialCharTok{/}\DecValTok{2}\NormalTok{,n}\DecValTok{{-}2}\NormalTok{,}\AttributeTok{lower.tail=}\NormalTok{F)}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(var.pred.mean)}

\FunctionTok{c}\NormalTok{(lower.ynew,upper.ynew)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 37.91320 51.13798
\end{verbatim}

We see that the PI for \(\bar{Y}_{h(\rm{new})}\) is given by \[
  [37.913, 51.138].
\]

\hypertarget{part-5}{%
\section{Part (5)}\label{part-5}}

\fbox{Provide an interpretation of your result, stated in the context of the problem.}

We predict that the mean service time for \(10\) service calls with
\(3\) copiers each will be between \(37.913\) and \(51.138\).

\hypertarget{part-6}{%
\section{Part (6)}\label{part-6}}

\fbox{\begin{minipage}{\textwidth}
Show that $\operatorname{V}(\rm{pred.mean})$ converges to $\operatorname{V}(\hat{Y}_h)$ as $m \to \infty$.
Use this limit result to interpret the confidence interval for $\mu_h$ as a prediction.
\end{minipage}}

The variance of \texttt{pred.mean} = \(\bar{P}_h\) is given by \[
  \operatorname{V}(\bar{P}_h) = \sigma^2 \left(\frac{1}{m} + \frac{1}{n} + \frac{(x_h-\bar{x})^2}{\rm{SS}_x}\right)
\] which we may rewrite as \begin{align*}
  \operatorname{V}(\bar{P}_h)
    &= \frac{\sigma^2}{m} + \sigma^2\left(\frac{1}{n} + \frac{(x_h-\bar{x})^2}{\rm{SS}_x}\right)\\
    &= \operatorname{V}(\bar{Y}_{h(\rm{new})}) + \operatorname{V}(\hat{Y}_h).
\end{align*}

As \(m \to \infty\), \(\operatorname{V}(\bar{Y}_{h(\rm{new})}) \to 0\),
and thus \[
  \lim_{m \to \infty} \operatorname{V}(\bar{P}_h) = \operatorname{V}(\hat{Y}_h).
\]

A CI estimate of the mean service time \(\mu_h\) can be interpreted as a
prediction of the sample mean \(\bar{Y}_{h(\rm{new})}\) for a large
number of service time responses.

\end{document}
