% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{amsmath}
\usepackage{mathtools}
\usepackage{amsthm}
\usepackage{multirow}
\usepackage{booktabs}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Discrete Multivariate Analysis - 579 - HW \#9},
  pdfauthor={Alex Towell (atowell@siue.edu)},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Discrete Multivariate Analysis - 579 - HW \#9}
\author{Alex Towell
(\href{mailto:atowell@siue.edu}{\nolinkurl{atowell@siue.edu}})}
\date{}

\begin{document}
\maketitle

\newcommand{\var}{\operatorname{Var}}
\newcommand{\expect}{\operatorname{E}}
\newcommand{\corr}{\operatorname{Corr}}
\newcommand{\cov}{\operatorname{Cov}}
\newcommand{\ssr}{\operatorname{SSR}}
\newcommand{\se}{\operatorname{SE}}
\newcommand{\mat}[1]{\mathbf{#1}}
\newcommand{\RR}{\operatorname{RR}}
\newcommand{\eval}[2]{\left. #1 \right\vert_{#2}}

Refer to the calf infection study discussed in lecture. Let \(n_3\)
denote the number of calves with primary, secondary, and tertiary
infections, \(n_2\) the number with only primary and secondary
infections, \(n_1\) the number with only a primary infection, and
\(n_0\) the number that were never infected. Let \(\theta\) be the
probability of a primary infection. Consider a model where the rate of
infection is constant. That is, \[
  \Pr(\text{tertiary} | \text{secondary}, \text{primary}) = \Pr(\text{secondary} | \text{primary}) = \Pr(\text{primary}).
\]

\hypertarget{problem-1}{%
\section{Problem 1}\label{problem-1}}

\fbox{Derive the maximum likelihood estimator of $\theta$ under the constant infection rate model.}

We assume the data model is given by \[
  (n_0,n_1,n_2,n_3) \sim \operatorname{MULT}(n, \pi_0, \pi_1, \pi_2, \pi_3)
\] where \(n_j\) denotes the number of \(j\) infections observed and
\(\pi_j\) denotes the probability of \(j\) infections.

First, we assume \(\Pr(\text{primary}) = \theta\). Then, given that in
order for the secondary infection to occur, the primary infection must
occur and in order for the tertiary infection to occur, the secondary
infection must occur, consider the following.

Under the constant infection rate model, the probability of \(0\)
infections is the probability that the primary infection does not occur,
\(\pi_{0 0}(\theta) = 1-\theta\). The probability of \(1\) infection is
the probability the primary infection occurs and the secondary infection
does not occur, \(\pi_{1 0}(\theta) = \theta(1-\theta)\). The
probability of \(2\) infections is the probability the primary and
secondary infections occur and the tertiary infection does not occur,
\(\pi_{2 0}(\theta) = \theta^2(1-\theta)\). Finally, the probability of
\(3\) infections is the probability the primary, secondary, and tertiary
infections occur, \(\pi_{3 0}(\theta) = \theta^3\).

Thus, \[
  \{n_j\} \sim \operatorname{MULT}(n, \{\pi_{j 0}(\theta)\}).
\] Under the null model, the likelihood function is given by \[
  \operatorname{L}(\theta) \propto \prod_{j=0}^{3} \pi_{j 0}(\theta)^{n_j}
\] and the kernel of the log-likelihood function is given by
\begin{align*}
  \operatorname{\ell}(\theta)
    &= \sum_{j=0}^{3} n_j \log \pi_{j 0}(\theta)\\
    &= n_0 \log \pi_{0 0}(\theta) +
       n_1 \log \pi_{1 0}(\theta) +
       n_2 \log \pi_{2 0}(\theta) +
       n_3 \log \pi_{3 0}(\theta)\\
    &= n_0 \log (1-\theta) +
       n_1 \log \theta(1-\theta) +
       n_2 \log \theta^2(1-\theta) +
       n_3 \log \theta^3\\
    &= n_0 \log (1-\theta) +
       n_1 \log \theta + n_1 \log (1-\theta) +
       2 n_2 \log \theta + n_2 \log (1-\theta) +
       3 n_3 \log \theta\\
    &= (n_1 + 2 n_2 + 3 n_3) \log \theta + (n_0 + n_1 + n_2) \log (1-\theta).
\end{align*}

The derivative of the log-likelihood is thus given by \[
  \frac{d \operatorname{\ell}}{d \theta} =
    \frac{n_1 + 2 n_2 + 3 n_3}{\theta} - \frac{n_0 + n_1 + n_2}{1-\theta}.
\]

The ML estimate of \(\theta\) is given by \[
  \left. \frac{d \operatorname{\ell}}{d \theta} \right\vert_{\hat\theta} = 0.
\] Solving for \(\hat\theta\), we see that \[
  \frac{n_1 + 2 n_2 + 3 n_3}{\hat\theta} = \frac{n_0 + n_1 + n_2}{1-\hat\theta}.
\] Next, we take the reciprocal of both sides, \[
  \frac{\hat\theta}{n_1 + 2 n_2 + 3 n_3} = \frac{1-\hat\theta}{n_0 + n_1 + n_2}.
\] Expanding the RHS, we get \[
  \frac{\hat\theta}{n_1 + 2 n_2 + 3 n_3} = \frac{1}{n_0 + n_1 + n_2}-\frac{\hat\theta}{n_0 + n_1 + n_2}.
\] Adding \(\frac{\hat\theta}{n_0 + n_1 + n_2}\) to both sides, \[
  \hat\theta \left(\frac{1}{n_1 + 2 n_2 + 3 n_3} + \frac{1}{n_0 + n_1 + n_2}\right) = \frac{1}{n_0 + n_1 + n_2}.
\] Dividing both sides by the part in parantheses, we get \[
  \hat\theta = \frac{1}{(n_0 + n_1 + n_2) \left(\frac{1}{n_1 + 2 n_2 + 3 n_3} + \frac{1}{n_0 + n_1 + n_2}\right)},
\] which simplifies to \[
  \hat\theta = \frac{n_1 + 2 n_2 + 3 n_3}{n_0 + 2 n_1 + 3 n_2 + 3 n_3}.
\]

\hypertarget{problem-2}{%
\section{Problem 2}\label{problem-2}}

\fbox{\begin{minipage}{.8\textwidth}
We observe data $n_0 = 63$, $n_1 = 63$, $n_2 = 25$, $n_3 = 5$.
Compute the mle $\hat\theta$ and the estimated probabilities $\vec{\pi}_0(\hat\theta)$.
\end{minipage}}

Using the MLE equation, we compute the result using R:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n0 }\OtherTok{\textless{}{-}} \DecValTok{63}
\NormalTok{n1 }\OtherTok{\textless{}{-}} \DecValTok{63}
\NormalTok{n2 }\OtherTok{\textless{}{-}} \DecValTok{25}
\NormalTok{n3 }\OtherTok{\textless{}{-}} \DecValTok{5}
\NormalTok{mle }\OtherTok{\textless{}{-}}\NormalTok{ (n1 }\SpecialCharTok{+} \DecValTok{2}\SpecialCharTok{*}\NormalTok{n2 }\SpecialCharTok{+} \DecValTok{3}\SpecialCharTok{*}\NormalTok{n3)}\SpecialCharTok{/}\NormalTok{(n0 }\SpecialCharTok{+} \DecValTok{2}\SpecialCharTok{*}\NormalTok{n1 }\SpecialCharTok{+} \DecValTok{3}\SpecialCharTok{*}\NormalTok{n2 }\SpecialCharTok{+} \DecValTok{3}\SpecialCharTok{*}\NormalTok{n3)}
\NormalTok{mle}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.4587814
\end{verbatim}

Thus, we see that \[
  \hat\theta = 0.4587814.
\] Plugging in this result, \[
  \vec{\pi}_{0}(\hat\theta) = (1-\hat\theta,\hat\theta(1-\hat\theta),
        \hat\theta^2(1-\hat\theta),\hat\theta^3)
\] which we compute with R:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pihats }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{mle,mle}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{mle),mle}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{mle),mle}\SpecialCharTok{\^{}}\DecValTok{3}\NormalTok{)}
\FunctionTok{round}\NormalTok{(pihats,}\AttributeTok{digits=}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.541 0.248 0.114 0.097
\end{verbatim}

Thus, we see that
\(\vec{\pi}_{0}(\hat\theta) = (0.541,0.248,0.114,0.097)'\).

\hypertarget{problem-3}{%
\section{Problem 3}\label{problem-3}}

\hypertarget{part-a}{%
\subsection{Part (a)}\label{part-a}}

\fbox{Compute the statistic $G^2$ and the $p$-value for testing the constant infection rate model.}

We use the following R code to compute the observed statistic \(G_0^2\).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# below is code for testing a specified multinomial}
\CommentTok{\# data is entered as a vector of counts}
\NormalTok{obs }\OtherTok{=} \FunctionTok{c}\NormalTok{(n0,n1,n2,n3)}
\NormalTok{n }\OtherTok{=} \FunctionTok{sum}\NormalTok{(obs)}

\CommentTok{\# the null model is entered as a vector of hypothesized probabilities}
\CommentTok{\# expected counts under the null model are computed as n*prob}
\NormalTok{m }\OtherTok{=}\NormalTok{ n}\SpecialCharTok{*}\NormalTok{pihats}

\CommentTok{\# log{-}likelihood ratio test}
\NormalTok{G2 }\OtherTok{=} \DecValTok{2}\SpecialCharTok{*}\FunctionTok{sum}\NormalTok{(obs}\SpecialCharTok{*}\FunctionTok{log}\NormalTok{(obs}\SpecialCharTok{/}\NormalTok{m))}
\NormalTok{G2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 30.43096
\end{verbatim}

We see that \(G_0^2 = 30.43096\).

The reference distribution is the chi-squared distribution with
\(\mathrm{df}=c-1-1=2\) degrees of freedom. The following R code
computes the \(p\)-value:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pchisq}\NormalTok{(G2,}\DecValTok{2}\NormalTok{,}\AttributeTok{lower.tail=}\ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.466041e-07
\end{verbatim}

We see that \(p\)-value \(< 0.001\).

\hypertarget{part-b}{%
\subsection{Part (b)}\label{part-b}}

\fbox{Provide an interpretation of your result, stated in the context of the problem.}

We obtained a \(p\)-value less than \(0.001\), which we consider to be
very strong evidence against the constant infection rate model.

\hypertarget{problem-4}{%
\section{Problem 4}\label{problem-4}}

\hypertarget{part-a-1}{%
\subsection{Part (a)}\label{part-a-1}}

\fbox{Compute $\hat\pi$, the estimated probability vector under the full model.}

Recall that the data model is given by \[
  (n_0,n_1,n_2,n_3) \sim \operatorname{MULT}(n,\pi_0,\pi_1,\pi_2,\pi_3).
\] Under the full model, each \(\pi_j\) may be independently specified.

We simply let the data speak for itself and estimate \(\pi_j\) as \[
  \hat\pi_j^{F} = \frac{n_j}{n}.
\] We use the following R code to compute the probability vector:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pihats\_full }\OtherTok{=}\NormalTok{ obs}\SpecialCharTok{/}\NormalTok{n}
\FunctionTok{round}\NormalTok{(pihats\_full,}\AttributeTok{digits=}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.404 0.404 0.160 0.032
\end{verbatim}

\hypertarget{part-b-1}{%
\subsection{Part (b)}\label{part-b-1}}

\fbox{Compute the estimated conditional probabilities of further infection under the full model.}

The probability of a primary infection is \[
  \Pr(\text{primary}) = \pi_1 + \pi_2 + \pi_3,
\] the probability of a secondary infection given a primary infection is
\[
  \Pr(\text{secondary} \,\vert\, \text{primary}) = \frac{\pi_2 + \pi_3}{\pi_1 + \pi_2 + \pi_3},
\] and the probability of a tertiary infection given a secondary
infection is \[
  \Pr(\text{tertiary} \,\vert\, \text{secondary}) = \frac{\pi_3}{\pi_2 + \pi_3}.
\]

We estimate these probabilities by plugging in the MLEs:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{primary }\OtherTok{=} \FunctionTok{sum}\NormalTok{(pihats\_full[}\DecValTok{2}\SpecialCharTok{:}\DecValTok{4}\NormalTok{])}
\NormalTok{secondary }\OtherTok{=} \FunctionTok{sum}\NormalTok{(pihats\_full[}\DecValTok{3}\SpecialCharTok{:}\DecValTok{4}\NormalTok{]) }\SpecialCharTok{/}\NormalTok{ primary}
\NormalTok{tertiary }\OtherTok{=}\NormalTok{ pihats\_full[}\DecValTok{4}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ secondary}

\FunctionTok{round}\NormalTok{(}\FunctionTok{c}\NormalTok{(primary,secondary,tertiary),}\AttributeTok{digits=}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.596 0.323 0.099
\end{verbatim}

We see that the conditional probability vector is given by
\((0.596,0.323,0.099)'\).

\hypertarget{part-c}{%
\subsection{Part (c)}\label{part-c}}

\fbox{Provide an interpretation, stated in the context of the problem.}

The conditional probabilities for the infection rates are significantly
\emph{decreasing}, i.e., not constant. The constant infection rate model
was not able to capture this relationship in the data.

\end{document}
