% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{amsmath}
\usepackage{mathtools}
\usepackage{amsthm}
\usepackage{multirow}
\usepackage{booktabs}
\usepackage{minted}
\usepackage{color}
\usepackage{xcolor}
\usepackage{tcolorbox}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Regression Analysis - STAT 482 - HW \#4},
  pdfauthor={Alex Towell (atowell@siue.edu)},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Regression Analysis - STAT 482 - HW \#4}
\author{Alex Towell
(\href{mailto:atowell@siue.edu}{\nolinkurl{atowell@siue.edu}})}
\date{}

\begin{document}
\maketitle

\newcommand{\ssto}{\operatorname{SSTO}}
\newcommand{\ssx}{\operatorname{SS_X}}
\newcommand{\ssr}{\operatorname{SS_R}}
\newcommand{\msr}{\operatorname{MS_R}}
\newcommand{\mse}{\operatorname{MS_E}}
\newcommand{\var}{\operatorname{V}}
\newcommand{\sd}{\operatorname{sd}}
\newcommand{\expect}{\operatorname{E}}
\newcommand{\corr}{\operatorname{cor}}
\newcommand{\cov}{\operatorname{cov}}
\newcommand{\se}{\operatorname{se}}
\newcommand{\mat}[1]{\mathbf{#1}}
\newcommand{\eval}[2]{\left. #1 \right\vert_{#2}}

\hypertarget{problem-1}{%
\section{Problem 1}\label{problem-1}}

Refer to the data from Exercise 1.20

Data has been collected on \(45\) calls for routine maintenance. The
goal is to explore the relationship between the number of copiers
serviced \((x)\) and the time in minutes spent to complete the service
\((y)\).

\begin{tcolorbox}[split=\f]
Part (a)
\tcblower
Determine the boundary values of the confidence band for the regression function
$\mu(x)$ at $x=3$ copiers.
\end{tcolorbox}

In a confidence band, the error of interest is the maximum error across
the input space \(x_1,\ldots,x_n\). That is, we are interested in \[
  \max_x \frac{\left(\hat{y}(x)-\mu(x)\right)^2}{\hat{\operatorname{V}}(\hat{y}(x))} \sim 2 F(2,n-2).
\]

Thus, a confidence band estimate for \(\mu(x) = \beta_0 + \beta_1 x\)
for all \(x\) is defined by the functions \[
  L(x) = \hat{y}(x) - c \sqrt{\hat{\operatorname{V}}(\hat{y}(x))}
\] and \[
  U(x) = \hat{y}(x) + c \sqrt{\hat{\operatorname{V}}(\hat{y}(x))}
\] where \[
  c = \sqrt{2 F(1-\alpha,2,n-2)}.
\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{call.data }\OtherTok{=} \FunctionTok{read.table}\NormalTok{(}\StringTok{\textquotesingle{}CH01PR20.txt\textquotesingle{}}\NormalTok{)}
\FunctionTok{colnames}\NormalTok{(call.data) }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"time"}\NormalTok{,}\StringTok{"copiers"}\NormalTok{)}
\NormalTok{call.mod }\OtherTok{=} \FunctionTok{lm}\NormalTok{(time }\SpecialCharTok{\textasciitilde{}}\NormalTok{ copiers, }\AttributeTok{data=}\NormalTok{call.data)}

\NormalTok{b0 }\OtherTok{=}\NormalTok{ call.mod}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{1}\NormalTok{]; }\FunctionTok{names}\NormalTok{(b0) }\OtherTok{=} \ConstantTok{NULL}
\NormalTok{b1 }\OtherTok{=}\NormalTok{ call.mod}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{2}\NormalTok{]; }\FunctionTok{names}\NormalTok{(b1) }\OtherTok{=} \ConstantTok{NULL}

\NormalTok{e }\OtherTok{=}\NormalTok{ call.mod}\SpecialCharTok{$}\NormalTok{residuals}
\NormalTok{n }\OtherTok{=} \FunctionTok{length}\NormalTok{(e)}
\NormalTok{sse }\OtherTok{=} \FunctionTok{sum}\NormalTok{(e}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{dfe }\OtherTok{=}\NormalTok{ n}\DecValTok{{-}2}
\NormalTok{mse }\OtherTok{=}\NormalTok{ sse }\SpecialCharTok{/}\NormalTok{ dfe}

\NormalTok{x.all }\OtherTok{=} \DecValTok{1}\SpecialCharTok{:}\DecValTok{10}
\NormalTok{x.sample }\OtherTok{=}\NormalTok{ call.data}\SpecialCharTok{$}\NormalTok{copiers}
\NormalTok{x.bar }\OtherTok{=} \FunctionTok{mean}\NormalTok{(x.sample)}
\NormalTok{x.star }\OtherTok{=}\NormalTok{ x.sample }\SpecialCharTok{{-}}\NormalTok{ x.bar}
\NormalTok{ssx }\OtherTok{=} \FunctionTok{sum}\NormalTok{(x.star}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}

\NormalTok{x.h }\OtherTok{=} \DecValTok{3}
\NormalTok{y.h }\OtherTok{=}\NormalTok{ b0 }\SpecialCharTok{+}\NormalTok{ b1}\SpecialCharTok{*}\NormalTok{x.h}
\NormalTok{y.h.l }\OtherTok{=}\NormalTok{ y.h }\SpecialCharTok{{-}} \FunctionTok{sqrt}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\FunctionTok{qf}\NormalTok{(.}\DecValTok{95}\NormalTok{,}\DecValTok{2}\NormalTok{,dfe))}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(mse}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{/}\NormalTok{n}\SpecialCharTok{+}\NormalTok{(x.h}\SpecialCharTok{{-}}\NormalTok{x.bar)}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{/}\NormalTok{ssx))}
\NormalTok{y.h.u }\OtherTok{=}\NormalTok{ y.h }\SpecialCharTok{+} \FunctionTok{sqrt}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\FunctionTok{qf}\NormalTok{(.}\DecValTok{95}\NormalTok{,}\DecValTok{2}\NormalTok{,dfe))}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(mse}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{/}\NormalTok{n}\SpecialCharTok{+}\NormalTok{(x.h}\SpecialCharTok{{-}}\NormalTok{x.bar)}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{/}\NormalTok{ssx))}

\FunctionTok{c}\NormalTok{(y.h.l,y.h.u)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 40.27853 48.77265
\end{verbatim}

We see that the confidence band at \(x_h = 3\) is given by \[
  [40.2785284, 48.7726465].
\]

\begin{tcolorbox}[split=\f]
Part (b)
\tcblower
Explain why the confidence band at $x_h$ is wider than a confidence interval
for $\mu_h$.
\end{tcolorbox}

As we increase the scope of the estimation/prediction, we increase the
probability of data incompatible with a model. Thus, we need to increase
the range of compatibility.

I was amused by the quote ``The really unusual day would be one where
nothing unusual happens.''

A \(95\%\) confidence band is given by an upper and lower limit such
that, with repeated sampling, \(95\%\) of the time, none of the sample
points will be outside of these limits. This contrasts with a confidence
interval, where we are only interested in a single point. Thus, a
standard CI is too narrow and must be appropriately widened.

\begin{tcolorbox}[split=\f]
Part (c)
\tcblower
Plot the estimated regression function along with both the confidence band and
the confidence intervals on input space $x=1,2,\ldots,10$.
\end{tcolorbox}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{y.hat }\OtherTok{=}\NormalTok{ b0 }\SpecialCharTok{+}\NormalTok{ b1}\SpecialCharTok{*}\NormalTok{x.all}
\NormalTok{y.lower }\OtherTok{=}\NormalTok{ y.hat }\SpecialCharTok{{-}} \FunctionTok{sqrt}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\FunctionTok{qf}\NormalTok{(.}\DecValTok{95}\NormalTok{,}\DecValTok{2}\NormalTok{,dfe))}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(mse}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{/}\NormalTok{n}\SpecialCharTok{+}\NormalTok{(x.all}\SpecialCharTok{{-}}\NormalTok{x.bar)}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{/}\NormalTok{ssx))}
\NormalTok{y.upper }\OtherTok{=}\NormalTok{ y.hat }\SpecialCharTok{+} \FunctionTok{sqrt}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\FunctionTok{qf}\NormalTok{(.}\DecValTok{95}\NormalTok{,}\DecValTok{2}\NormalTok{,dfe))}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(mse}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{/}\NormalTok{n}\SpecialCharTok{+}\NormalTok{(x.all}\SpecialCharTok{{-}}\NormalTok{x.bar)}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{/}\NormalTok{ssx))}
\NormalTok{y.all }\OtherTok{=} \FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(y.hat,y.lower,y.upper),}\AttributeTok{ncol=}\DecValTok{3}\NormalTok{)}

\FunctionTok{colnames}\NormalTok{(y.all) }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"mean.y"}\NormalTok{,}\StringTok{"lower.limit"}\NormalTok{,}\StringTok{"upper.limit"}\NormalTok{)}
\CommentTok{\#cbind(x.all,y.all)}

\FunctionTok{matplot}\NormalTok{(x.all,y.all,}\AttributeTok{type=}\StringTok{"l"}\NormalTok{,}\AttributeTok{lty=}\DecValTok{1}\NormalTok{,}\AttributeTok{col=}\FunctionTok{c}\NormalTok{(}\StringTok{"black"}\NormalTok{,}\StringTok{"red"}\NormalTok{,}\StringTok{"red"}\NormalTok{),}
        \AttributeTok{xlab =} \StringTok{"copiers"}\NormalTok{,}\AttributeTok{ylab =} \StringTok{"time"}\NormalTok{)}

\NormalTok{call.ci }\OtherTok{=} \FunctionTok{predict}\NormalTok{(call.mod,}\FunctionTok{data.frame}\NormalTok{(}\AttributeTok{copiers=}\NormalTok{x.all),}\AttributeTok{interval =} \StringTok{"confidence"}\NormalTok{)}
\NormalTok{call.ci }\OtherTok{=} \FunctionTok{cbind}\NormalTok{(x.all,call.ci)}
\CommentTok{\#call.ci}

\NormalTok{y.lwr }\OtherTok{=}\NormalTok{ call.ci[,}\DecValTok{3}\NormalTok{]}
\NormalTok{y.upp }\OtherTok{=}\NormalTok{ call.ci[,}\DecValTok{4}\NormalTok{]}
\FunctionTok{points}\NormalTok{(x.all,y.lwr,}\AttributeTok{type=}\StringTok{"l"}\NormalTok{,}\AttributeTok{lty=}\DecValTok{2}\NormalTok{,}\AttributeTok{col=}\StringTok{"blue"}\NormalTok{)}
\FunctionTok{points}\NormalTok{(x.all,y.upp,}\AttributeTok{type=}\StringTok{"l"}\NormalTok{,}\AttributeTok{lty=}\DecValTok{2}\NormalTok{,}\AttributeTok{col=}\StringTok{"blue"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw4_files/figure-latex/unnamed-chunk-3-1.pdf}

\hypertarget{problem-2}{%
\section{Problem 2}\label{problem-2}}

Refer to the data from Exercise 1.27

A person's muscle mass is expected to decrease with age. To explore this
relationship in women, a nutritionist randomly selected \(15\) women for
each \(10\) year age group, beginning with \(40\) and ending with age
\(79\). The input variable \(x\) is age (in years), and the response
variable \(y\) is muscle mass (in muscle mass units).

\begin{tcolorbox}[split=\f]
Part (a)
\tcblower
State the equations for $\operatorname{E}(\operatorname{MS_R})$ and $\operatorname{E}(\operatorname{MS_E})$.
\end{tcolorbox}

Recall that \(\operatorname{E}(\operatorname{MS_E}) = \sigma^2\). The
expected value of the \(\operatorname{MS_R}\) is \[
  \operatorname{E}(\operatorname{MS_R}) = \sigma^2 + \operatorname{SS_X}\beta_1^2.
\]

\begin{tcolorbox}[split=\f]
Part (b)
\tcblower
Use part (a) to explain a motivation behind the $F$ test for input effects.
\end{tcolorbox}

If \(\beta_1 \approx 0\), then
\(\operatorname{E}(\operatorname{MS_R}) \approx \operatorname{E}(\operatorname{MS_E})\).

The test statistic is given by \[
  F^* = \frac{\operatorname{MS_R}}{\operatorname{MS_E}}
\] where a small \(F^*\) indicates data compatible with the null model
and a large \(F^*\) indicates data not compatible with the null model.

\begin{tcolorbox}[split=\f]
Part (c)
\tcblower
Compute the $F^*$ statistic and the $p$-value.
Provide an interpretation, stated in the context of the problem.
\end{tcolorbox}

Of \(\beta_1 = 0\) (no effect model), then \(F^* \sim F(1,n-2)\). The
\(p\)-value is given by \[
  \Pr\left[F(1,n-2) > F^*\right].
\]

We compute these results with:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mass.data }\OtherTok{=} \FunctionTok{read.table}\NormalTok{(}\StringTok{\textquotesingle{}CH01PR27.txt\textquotesingle{}}\NormalTok{)}
\FunctionTok{colnames}\NormalTok{(mass.data) }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"mass"}\NormalTok{,}\StringTok{"age"}\NormalTok{)}
\NormalTok{mass.mod }\OtherTok{=} \FunctionTok{lm}\NormalTok{(mass }\SpecialCharTok{\textasciitilde{}}\NormalTok{ age, }\AttributeTok{data=}\NormalTok{mass.data)}
\FunctionTok{anova}\NormalTok{(mass.mod)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: mass
##           Df  Sum Sq Mean Sq F value    Pr(>F)    
## age        1 11627.5 11627.5  174.06 < 2.2e-16 ***
## Residuals 58  3874.4    66.8                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

From the ANOVA table, we see that \(\operatorname{MS_R}= 11627.486\),
\(\operatorname{MS_E}= 66.8\), and
\(F^* = \operatorname{MS_R}/ \operatorname{MS_E}= 174.06\). This value
of the test statistic has a \(p\)-value given by \(.000\).

Interpretation: Since the data is not compatible with the no effect
model, we accept the model which includes age as a predictor.

\begin{tcolorbox}[split=\f]
Part (d)
\tcblower
Compute the coefficient of determination $r^2$.
Provide an interpretation, stated in the context of the problem.
\end{tcolorbox}

The coefficient of determination is the proportion of variation in the
response \(Y\) that is explained by input \(x\), \[
  r^2 = \frac{\operatorname{SS_R}}{\operatorname{SSTO}}.
\]

We compute the coefficient of determination with:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(mass.mod)}\SpecialCharTok{$}\NormalTok{r.squared}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.7500668
\end{verbatim}

We estimate that \(95\%\) of the variation in mass is explained by
elapsed molding time.

Since the sample correlation is given by \(r = \sqrt{r^2} = 0.87\),
these two variables appear to be significantly correlated.

\end{document}
