% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{amsmath}
\usepackage{mathtools}
\usepackage{amsthm}
\usepackage{multirow}
\usepackage{booktabs}
\usepackage{minted}
\usepackage{color}
\usepackage{xcolor}
\usepackage{tcolorbox}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Regression Analysis - STAT 482 - HW \#2},
  pdfauthor={Alex Towell (atowell@siue.edu)},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Regression Analysis - STAT 482 - HW \#2}
\author{Alex Towell
(\href{mailto:atowell@siue.edu}{\nolinkurl{atowell@siue.edu}})}
\date{}

\begin{document}
\maketitle

\newsavebox{\selvestebox}
\newenvironment{colbox}[1]
  {\newcommand\colboxcolor{#1}%
   \begin{lrbox}{\selvestebox}%
   \begin{minipage}{\dimexpr\columnwidth-2\fboxsep\relax}}
  {\end{minipage}\end{lrbox}%
   \begin{center}
   \colorbox[HTML]{\colboxcolor}{\usebox{\selvestebox}}
   \end{center}}

\newcommand{\var}{\operatorname{Var}}
\newcommand{\expect}{\operatorname{E}}
\newcommand{\corr}{\operatorname{Corr}}
\newcommand{\cov}{\operatorname{Cov}}
\newcommand{\ssr}{\operatorname{SSR}}
\newcommand{\se}{\operatorname{SE}}
\newcommand{\mat}[1]{\mathbf{#1}}
\newcommand{\RR}{\operatorname{RR}}
\newcommand{\eval}[2]{\left. #1 \right\vert_{#2}}

Refer to the data from Exercise 1.27

A person's muscle mass is expected to decrease with age. To explore this
relationship in women, a nutritionist randomly selected \(15\) women for
each \(10\) year age group, beginning with \(40\) and ending with age
\(79\). The input variable \(x\) is age (in years), and the response
variable \(y\) is muscle mass (in muscle mass units).

\hypertarget{part-1}{%
\section{Part (1)}\label{part-1}}

\fbox{Compute the $t$-statistic and $p$-value for testing $H_0 : \beta_1 = 0$.}

We assume a random sample \(\{\mathcal{D}_i\}\) where
\(\mathcal{D}_i = (X_i,Y_i)\) is generated by the linear model
\(Y_i = \beta_0 + \beta_1 X_i + \epsilon_i\). We are not particularly
interested in the distribution of \(X_i\) and instead seek to use it as
an explanatory variable (input) for response variable \(Y_i\) (output).

Thus, we are interested in estimating the parameters of the conditional
distribution \[
  Y_i | X_i = x_i \sim \mathcal{N}(\beta_0 + \beta_1 x_i, \sigma^2).
\]

We fit the given data \(\{\mathcal{d}_i\}\) where
\(\mathcal{d}_i = (x_i,y_i)\) to the linear regression model \[
  Y_i = \beta_0 + \beta_1 x_i + \epsilon_i
\] using the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mass.data }\OtherTok{=} \FunctionTok{read.table}\NormalTok{(}\StringTok{\textquotesingle{}CH01PR27.txt\textquotesingle{}}\NormalTok{)}
\FunctionTok{colnames}\NormalTok{(mass.data)}\OtherTok{=}\FunctionTok{c}\NormalTok{(}\StringTok{"mass"}\NormalTok{,}\StringTok{"age"}\NormalTok{)}
\NormalTok{mass.mod }\OtherTok{=} \FunctionTok{lm}\NormalTok{(mass }\SpecialCharTok{\textasciitilde{}}\NormalTok{ age, }\AttributeTok{data=}\NormalTok{mass.data)}
\end{Highlighting}
\end{Shaded}

We compute the \(t\)-statistic
\(t^* = \frac{b_1}{\operatorname{SE}(b_1)} \sim t(n-2)\) and the
\(p\)-value \(p = \Pr\{t(n-2) > |t_*|\}\) with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{beta1.stats }\OtherTok{=} \FunctionTok{summary}\NormalTok{(mass.mod)}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{2}\NormalTok{,]}
\NormalTok{beta1.stats}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Estimate    Std. Error       t value      Pr(>|t|) 
## -1.189996e+00  9.019725e-02 -1.319326e+01  4.123987e-19
\end{verbatim}

We see that \(t^* = -13.193\) which has a \(p\)-value less than
\(0.001\).

\hypertarget{part-2}{%
\section{Part (2)}\label{part-2}}

\fbox{Provide an interpretation of the above as a test for model compatibility.}

We think of the the null hypothesis as a simplification to the model,
which we \emph{a priori} prefer to the more complicated model (there is
a probabilistic justification for this bias), \[
  H_0 \colon \beta_1 = 0 \qquad \text{(age has no effect on muscle mass)}.
\]

We obtained a \(p\)-value of approximately \(.000\), and so the data is
not compatible with the no effect model; we accept the model which
includes age as a predictor for muscle mass.

\hypertarget{alterantive-formulation}{%
\subsection{Alterantive formulation}\label{alterantive-formulation}}

Can we say the null hypothesis \(H_0 : \beta_1 = 0\) is equivalent to \[
  H_0 : \text{no association between age and muscle mass}
\] since if \(\beta_1 = 0\) then \[
  Y_1,\ldots,Y_n \overset{\rm{iid}}{\sim} \mathcal{N}(\beta_0,\sigma^2)?
\]

However, I am concerned that I am going beyond the model since our model
is given by the conditional distribution of \(Y_i|X_i\). So, we may say
that \(x_i\) has no effect on \(Y_i\), but in general \(y_i\) may effect
\(X_i\). Clearly, in this case, we have scientific insight that one's
muscle mass does not effect one's age.

Also, I'm struggling with the wording \emph{compatibility}. I find
myself wanting to say that any outcome that has non-zero probability
under the model is compatible with the model. Is it simply too subtle to
say, ``Assuming the null hypothesis is true, then with probability \(p\)
the observed statistic or a more extreme value will have been
observed.'' This may in fact be a bit much, especially for the less
mathematically inclined, whom we wish to inform with our analysis. So,
perhaps we are better off using phrasing like ``fail to reject the null
hypothesis'' or ``the data is not compatible with the null model.'' I
must confess that I sort of prefer ``fail to reject the null
hypothesis,'' since it seems to be taking the stance that either model
may be correct, but we lack sufficient data to reject the null model,
which is some model we prefer for some reason, e.g., the null model is
often the simplest model in a family of models.

I'm still unsatisfied with my thoughts on this subject. On a related
note, I enjoyed your discussion last Spring on the Bayesian perspective.
When we combine this perspective with, say, a universal prior, perhaps
we are getting closer to a sort of formalism for the scientific method
(where the universal prior is a sort of formalism for Occam's razor).

\hypertarget{part-3}{%
\section{Part (3)}\label{part-3}}

\fbox{Provide an interpretation of the above as a test for sign / direction of
the effect.}

Since both \(t^* < 0\) and \(b_1 < 0\), the data supports the hypothesis
of a negative association between age and muscle mass, i.e., as age
increases muscle mass is expected to decrease.

\hypertarget{part-4}{%
\section{Part (4)}\label{part-4}}

\fbox{Compute an interval estimate for $\beta_1$.}

We compute a \(95\%\) confidence interval for \(\beta_1\) with:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{alpha }\OtherTok{=} \FloatTok{0.05}
\NormalTok{beta1.ci }\OtherTok{=} \FunctionTok{round}\NormalTok{(}\FunctionTok{confint}\NormalTok{(mass.mod, }\AttributeTok{level=}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{alpha)[}\DecValTok{2}\NormalTok{,],}\AttributeTok{digits=}\DecValTok{3}\NormalTok{)}
\NormalTok{beta1.ci}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  2.5 % 97.5 % 
## -1.371 -1.009
\end{verbatim}

We see that \(\beta_1\) has a \(95\%\) confidence interval given by \[
  [-1.371,-1.009].
\]

\hypertarget{part-5}{%
\section{Part (5)}\label{part-5}}

\fbox{Explain how an interval estimate provides additional information beyond the test result.}

We can say more about the size of the effect and a measure of the
estimation accuracy.

We make two observations about the CI for \(\beta_1\):

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  All the values in the CI are distant from \(0\), and thus we can say
  there is strong evidence that age has a large effect.
\item
  The CI represents a relatively small range of values, and thus we can
  say the model is accurate, i.e., the data has a significant amount of
  information about \(\beta_1\).
\end{enumerate}

\hypertarget{part-6}{%
\section{Part (6)}\label{part-6}}

\fbox{Compute an interval estimate for the centered model parameter $\beta_0^*$.}

\(\beta_0^*\) represents the mean muscle mass at the mean age in the
sample, \[
  E(Y|x=\bar{x}) = \beta_0^*,
\] and thus \[
  b_0^* = \frac{1}{n} \sum_{i=1}^{n} Y_i.
\]

To compute the confidence interval for \(b_0^*\), I refit the model
using the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x }\OtherTok{=}\NormalTok{ mass.data}\SpecialCharTok{$}\NormalTok{age}
\NormalTok{y }\OtherTok{=}\NormalTok{ mass.data}\SpecialCharTok{$}\NormalTok{mass}
\NormalTok{x.bar }\OtherTok{=} \FunctionTok{mean}\NormalTok{(x)}
\NormalTok{y.bar }\OtherTok{=} \FunctionTok{mean}\NormalTok{(y)}
\NormalTok{x.star }\OtherTok{=}\NormalTok{ x }\SpecialCharTok{{-}}\NormalTok{ x.bar}
\NormalTok{star.mod }\OtherTok{=} \FunctionTok{lm}\NormalTok{(y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x.star, }\AttributeTok{data=}\NormalTok{mass.data)}
\NormalTok{beta0.star.ci }\OtherTok{=} \FunctionTok{round}\NormalTok{(}\FunctionTok{confint}\NormalTok{(star.mod)[}\DecValTok{1}\NormalTok{,],}\AttributeTok{digits=}\DecValTok{3}\NormalTok{)}
\NormalTok{beta0.star.ci}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  2.5 % 97.5 % 
## 82.855 87.079
\end{verbatim}

We see that \(\beta_0^*\) has a \(95\%\) confidence interval given by \[
  [82.855,87.079].
\]

\hypertarget{part-7}{%
\section{Part (7)}\label{part-7}}

\fbox{Provide an interpretation for your result, stated in the context of the problem.}

We estimate that the mean muscle mass for all women at the center value
of age (\(\bar{x} = 59.983\)) is between 82.855 and 87.079.

\end{document}
