<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <meta name="author" content="Alex Towell (atowell@siue.edu)" />
  <title>STAT 581 - HW #1</title>
  <style>
    html {
      color: #1a1a1a;
      background-color: #fdfdfd;
    }
    body {
      margin: 0 auto;
      max-width: 36em;
      padding-left: 50px;
      padding-right: 50px;
      padding-top: 50px;
      padding-bottom: 50px;
      hyphens: auto;
      overflow-wrap: break-word;
      text-rendering: optimizeLegibility;
      font-kerning: normal;
    }
    @media (max-width: 600px) {
      body {
        font-size: 0.9em;
        padding: 12px;
      }
      h1 {
        font-size: 1.8em;
      }
    }
    @media print {
      html {
        background-color: white;
      }
      body {
        background-color: transparent;
        color: black;
        font-size: 12pt;
      }
      p, h2, h3 {
        orphans: 3;
        widows: 3;
      }
      h2, h3, h4 {
        page-break-after: avoid;
      }
    }
    p {
      margin: 1em 0;
    }
    a {
      color: #1a1a1a;
    }
    a:visited {
      color: #1a1a1a;
    }
    img {
      max-width: 100%;
    }
    h1, h2, h3, h4, h5, h6 {
      margin-top: 1.4em;
    }
    h5, h6 {
      font-size: 1em;
      font-style: italic;
    }
    h6 {
      font-weight: normal;
    }
    ol, ul {
      padding-left: 1.7em;
      margin-top: 1em;
    }
    li > ol, li > ul {
      margin-top: 0;
    }
    blockquote {
      margin: 1em 0 1em 1.7em;
      padding-left: 1em;
      border-left: 2px solid #e6e6e6;
      color: #606060;
    }
    code {
      font-family: Menlo, Monaco, Consolas, 'Lucida Console', monospace;
      font-size: 85%;
      margin: 0;
      hyphens: manual;
    }
    pre {
      margin: 1em 0;
      overflow: auto;
    }
    pre code {
      padding: 0;
      overflow: visible;
      overflow-wrap: normal;
    }
    .sourceCode {
     background-color: transparent;
     overflow: visible;
    }
    hr {
      background-color: #1a1a1a;
      border: none;
      height: 1px;
      margin: 1em 0;
    }
    table {
      margin: 1em 0;
      border-collapse: collapse;
      width: 100%;
      overflow-x: auto;
      display: block;
      font-variant-numeric: lining-nums tabular-nums;
    }
    table caption {
      margin-bottom: 0.75em;
    }
    tbody {
      margin-top: 0.5em;
      border-top: 1px solid #1a1a1a;
      border-bottom: 1px solid #1a1a1a;
    }
    th {
      border-top: 1px solid #1a1a1a;
      padding: 0.25em 0.5em 0.25em 0.5em;
    }
    td {
      padding: 0.125em 0.5em 0.25em 0.5em;
    }
    header {
      margin-bottom: 4em;
      text-align: center;
    }
    #TOC li {
      list-style: none;
    }
    #TOC ul {
      padding-left: 1.3em;
    }
    #TOC > ul {
      padding-left: 0;
    }
    #TOC a:not(:hover) {
      text-decoration: none;
    }
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    /* The extra [class] is a hack that increases specificity enough to
       override a similar rule in reveal.js */
    ul.task-list[class]{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      font-size: inherit;
      width: 0.8em;
      margin: 0 0.8em 0.2em -1.6em;
      vertical-align: middle;
    }
  </style>
  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="/usr/share/javascript/mathjax/MathJax.js"
  type="text/javascript"></script>
</head>
<body>
<header id="title-block-header">
<h1 class="title">STAT 581 - HW #1</h1>
<p class="author">Alex Towell (<a
href="mailto:atowell@siue.edu"><code>atowell@siue.edu</code></a>)</p>
</header>
<div class="snugshade">

</div>
<p>An experiment is designed to investigate whether the time to drill
holes in rock holes using wet or dry drilling. A completely randomized
design (CRD) is used. Each method is replicated on 12 rocks. The
drilling times (in 1 / 100 minutes) are observed to be</p>
<table>
<tbody>
<tr class="odd">
<td style="text-align: left;">dry</td>
<td style="text-align: right;">727</td>
<td style="text-align: right;">965</td>
<td style="text-align: right;">904</td>
<td style="text-align: right;">987</td>
<td style="text-align: right;">847</td>
<td style="text-align: right;">918</td>
<td style="text-align: right;">814</td>
<td style="text-align: right;">750</td>
<td style="text-align: right;">804</td>
<td style="text-align: right;">989</td>
<td style="text-align: right;">902</td>
<td style="text-align: right;">939</td>
</tr>
<tr class="even">
<td style="text-align: left;">wet</td>
<td style="text-align: right;">607</td>
<td style="text-align: right;">549</td>
<td style="text-align: right;">762</td>
<td style="text-align: right;">665</td>
<td style="text-align: right;">588</td>
<td style="text-align: right;">798</td>
<td style="text-align: right;">704</td>
<td style="text-align: right;">772</td>
<td style="text-align: right;">780</td>
<td style="text-align: right;">599</td>
<td style="text-align: right;">603</td>
<td style="text-align: right;">699</td>
</tr>
</tbody>
</table>
<h1 id="q1">Q1</h1>
<p>The hypothesis of interest is whether drilling time is effected by
the choice of wet or dry drilling. We may formulate this as a hypothesis
test of the form</p>
<p><span class="math display">\[\begin{aligned}
  H_0 &amp;: \mu_1 = \mu_2\\
  H_A &amp;: \mu_1 \neq \mu_2\,,
\end{aligned}\]</span> where <span class="math inline">\(\mu_1\)</span>
and <span class="math inline">\(\mu_2\)</span> are respectively the
expected drilling time for dry and wet drilling.</p>
<p>If <span class="math inline">\(H_0\)</span> is true, the drilling
method has <em>no</em> effect on drilling time. If <span
class="math inline">\(H_A\)</span> is true, the choice does have an
effect on drilling time.</p>
<h1 id="q2">Q2</h1>
<p>Two advantages of the completely randomized design (CRD) are:</p>
<ol>
<li><p>It is simple to implement and analyze.</p></li>
<li><p>It accounts for experimental unit variance, namely by controlling
for the type I error,</p>
<p><span class="math display">\[\alpha = \Pr(\text{decide} \, H_A | H_0
\, \text{true}),\]</span></p>
<p>where <span class="math inline">\(\alpha\)</span> is the probability
of a type I error. It may also be thought of as the type I <em>error
rate</em>, or <em>false positive rate</em>.</p></li>
</ol>
<h1 id="q3">Q3</h1>
<p>Two disadvantages of the completely randomized design (CRD) are:</p>
<ol>
<li><p>It does not account for type II error, <span
class="math display">\[\beta = \Pr(\text{decide} \, H_0 | H_A \,
\text{true}).\]</span> where <span class="math inline">\(\beta\)</span>
is the probability of a type II error.</p>
<blockquote>
<p><strong>Additional remarks</strong>: Since we may denote a type I
error a false positive, it may be appropriate to denote a type II error
a false negative, which implies the convention <span
class="math inline">\(H_0 \equiv \rm{negative}\)</span> and <span
class="math inline">\(H_A \equiv \rm{positive}\)</span>. Thus, <span
class="math inline">\(\beta\)</span> may be thought of as the false
negative rate.</p>
</blockquote>
<blockquote>
<p>Consider the unrelated <em>Bloom filter</em>, which is a
probabilistic data structure that models sets in which membership
queries have a controllable false positive rate <span
class="math inline">\(\epsilon\)</span> and a false negative rate <span
class="math inline">\(0\)</span>. If we take the complement of an object
representing such a Bloom filter, then membership queries on its
complement have a false positive rate <span
class="math inline">\(0\)</span> and a false negative rate <span
class="math inline">\(\epsilon\)</span>.</p>
</blockquote></li>
<li><p>It does not adjust for differences in experimental units nor
differences in any other factors.</p></li>
</ol>
<h1 id="q4">Q4</h1>
<div class="snugshade">
<div class="Highlighting">
<p>time.mean <span
style="color: 0.56,0.35,0.01">&lt;<span>-</span></span> <span
style="color: 0.13,0.29,0.53"><strong>round</strong></span>(<span
style="color: 0.13,0.29,0.53"><strong>c</strong></span>(<span
style="color: 0.13,0.29,0.53"><strong>mean</strong></span>(h1.time.dry),
<span
style="color: 0.13,0.29,0.53"><strong>mean</strong></span>(h1.time.wet)),<span
style="color: 0.13,0.29,0.53">digits=</span><span
style="color: 0.00,0.00,0.81">3</span>) time.var <span
style="color: 0.56,0.35,0.01">&lt;<span>-</span></span> <span
style="color: 0.13,0.29,0.53"><strong>round</strong></span>(<span
style="color: 0.13,0.29,0.53"><strong>c</strong></span>(<span
style="color: 0.13,0.29,0.53"><strong>var</strong></span>(h1.time.dry),
<span
style="color: 0.13,0.29,0.53"><strong>var</strong></span>(h1.time.wet)),<span
style="color: 0.13,0.29,0.53">digits=</span><span
style="color: 0.00,0.00,0.81">3</span>) time.sd <span
style="color: 0.56,0.35,0.01">&lt;<span>-</span></span> <span
style="color: 0.13,0.29,0.53"><strong>round</strong></span>(<span
style="color: 0.13,0.29,0.53"><strong>sqrt</strong></span>(time.var),<span
style="color: 0.13,0.29,0.53">digits=</span><span
style="color: 0.00,0.00,0.81">3</span>) n <span
style="color: 0.56,0.35,0.01">&lt;<span>-</span></span> <span
style="color: 0.13,0.29,0.53"><strong>c</strong></span>(<span
style="color: 0.13,0.29,0.53"><strong>length</strong></span>(h1.time.dry),
<span
style="color: 0.13,0.29,0.53"><strong>length</strong></span>(h1.time.wet))
time.sd.pooled <span
style="color: 0.56,0.35,0.01">&lt;<span>-</span></span> <span
style="color: 0.13,0.29,0.53"><strong>round</strong></span>(<span
style="color: 0.13,0.29,0.53"><strong>sqrt</strong></span>(((n[<span
style="color: 0.00,0.00,0.81">1</span>] <span
style="color: 0.81,0.36,0.00"><strong>-</strong></span> <span
style="color: 0.00,0.00,0.81">1</span>) <span
style="color: 0.81,0.36,0.00"><strong>*</strong></span> time.var[<span
style="color: 0.00,0.00,0.81">1</span>] <span
style="color: 0.81,0.36,0.00"><strong>+</strong></span> (n[<span
style="color: 0.00,0.00,0.81">2</span>] <span
style="color: 0.81,0.36,0.00"><strong>-</strong></span> <span
style="color: 0.00,0.00,0.81">1</span>) <span
style="color: 0.81,0.36,0.00"><strong>*</strong></span> time.var[<span
style="color: 0.00,0.00,0.81">2</span>]) <span
style="color: 0.81,0.36,0.00"><strong>/</strong></span> (<span
style="color: 0.13,0.29,0.53"><strong>sum</strong></span>(n)<span
style="color: 0.81,0.36,0.00"><strong>-</strong></span><span
style="color: 0.00,0.00,0.81">2</span>)), <span
style="color: 0.13,0.29,0.53">digits=</span><span
style="color: 0.00,0.00,0.81">3</span>)</p>
<p><span style="color: 0.13,0.29,0.53"><strong>c</strong></span>(<span
style="color: 0.31,0.60,0.02">"y.bar.1"</span> <span
style="color: 0.56,0.35,0.01">=</span> time.mean[<span
style="color: 0.00,0.00,0.81">1</span>], <span
style="color: 0.31,0.60,0.02">"y.bar.2"</span> <span
style="color: 0.56,0.35,0.01">=</span> time.mean[<span
style="color: 0.00,0.00,0.81">2</span>], <span
style="color: 0.31,0.60,0.02">"s.1"</span> <span
style="color: 0.56,0.35,0.01">=</span> time.sd[<span
style="color: 0.00,0.00,0.81">1</span>], <span
style="color: 0.31,0.60,0.02">"s.2"</span> <span
style="color: 0.56,0.35,0.01">=</span> time.sd[<span
style="color: 0.00,0.00,0.81">2</span>], <span
style="color: 0.31,0.60,0.02">"s.p"</span> <span
style="color: 0.56,0.35,0.01">=</span> time.sd.pooled)</p>
</div>
</div>
<pre><code>## y.bar.1 y.bar.2     s.1     s.2     s.p 
## 878.833 677.167  89.470  87.189  88.337</code></pre>
<p>We see that the sample means are <span
class="math display">\[(\bar{y}_1,\bar{y}_2) = (878.833,
677.167),\]</span> the standard deviations are <span
class="math display">\[(s_1,s_2) = (89.47, 87.189),\]</span> and the
pooled standard deviation is <span class="math display">\[s_p =
88.337.\]</span></p>
<h1 id="q5">Q5</h1>
<p>The test statistic is defined as <span class="math display">\[t_0 =
\frac{\bar{y}_1-\bar{y}_2}{s_p
\sqrt{\frac{1}{n_1}+\frac{1}{n_2}}}.\]</span> which is a drawn from a
<span class="math inline">\(t\)</span>-student distribution with <span
class="math inline">\(n_1+n_2-2\)</span> degrees of freedom under the
null model (reference distribution).</p>
<blockquote>
<p>Under the null model, <span class="math inline">\(\bar{y}_1\)</span>
and <span class="math inline">\(\bar{y}_2\)</span> are the means of two
samples respectively of size <span class="math inline">\(n_1\)</span>
and <span class="math inline">\(n_2\)</span> whose elements are drawn
from the same normal distribution.</p>
</blockquote>
<p>Denote this reference distribution by <span
class="math inline">\(T\)</span>. Under the null model, <span
class="math inline">\(t_0\)</span> is a realization of <span
class="math inline">\(T\)</span>. Our general approach is to compute the
test statistic <span class="math inline">\(t_0\)</span> for the given
samples and say it is compatible with the null model if it obtains a
value that is not too extreme under <span
class="math inline">\(T\)</span>, e.g., a <span
class="math inline">\(p\)</span>-value that is less than some
controllable parameter <span class="math inline">\(\alpha\)</span>.</p>
<p>The critical point (the minimum value that is considered to be too
extreme) is given by solving for <span
class="math inline">\(t^*\)</span> in <span
class="math display">\[\Pr\{-|t^*| &lt; T &lt; |t^*|\} =
\alpha,\]</span> which has the solution <span class="math inline">\(t^*
= t_{\rm{df}=n_1+n_2-2}(\alpha/2)\)</span>, and <span
class="math display">\[\begin{aligned}
  \text{$p$-value} &amp;= \Pr\{T \notin [-|t_0|,|t_0|]\}\\
                   &amp;= 2 \Pr\{T &gt; |t_0|\}\\
                   &amp;= 2(1-F_T(|t_0|)),
\end{aligned}\]</span> where <span class="math inline">\(F_T\)</span> is
the cdf of <span class="math inline">\(T\)</span>.</p>
<p>We compute these results in R with:</p>
<div class="snugshade">
<div class="Highlighting">
<p>se <span style="color: 0.56,0.35,0.01">&lt;<span>-</span></span>
time.sd.pooled<span
style="color: 0.81,0.36,0.00"><strong>*</strong></span><span
style="color: 0.13,0.29,0.53"><strong>sqrt</strong></span>(<span
style="color: 0.00,0.00,0.81">1</span><span
style="color: 0.81,0.36,0.00"><strong>/</strong></span>n[<span
style="color: 0.00,0.00,0.81">1</span>]<span
style="color: 0.81,0.36,0.00"><strong>+</strong></span><span
style="color: 0.00,0.00,0.81">1</span><span
style="color: 0.81,0.36,0.00"><strong>/</strong></span>n[<span
style="color: 0.00,0.00,0.81">2</span>]) t<span
style="color: 0.00,0.00,0.81">.0</span> <span
style="color: 0.56,0.35,0.01">&lt;<span>-</span></span> <span
style="color: 0.13,0.29,0.53"><strong>round</strong></span>((time.mean[<span
style="color: 0.00,0.00,0.81">1</span>]<span
style="color: 0.81,0.36,0.00"><strong>-</strong></span>time.mean[<span
style="color: 0.00,0.00,0.81">2</span>])<span
style="color: 0.81,0.36,0.00"><strong>/</strong></span>se,<span
style="color: 0.13,0.29,0.53">digits=</span><span
style="color: 0.00,0.00,0.81">3</span>) alpha <span
style="color: 0.56,0.35,0.01">&lt;<span>-</span></span> <span
style="color: 0.00,0.00,0.81">0.05</span> t.star <span
style="color: 0.56,0.35,0.01">=</span> <span
style="color: 0.13,0.29,0.53"><strong>round</strong></span>(<span
style="color: 0.13,0.29,0.53"><strong>qt</strong></span>(alpha<span
style="color: 0.81,0.36,0.00"><strong>/</strong></span><span
style="color: 0.00,0.00,0.81">2</span>,<span
style="color: 0.13,0.29,0.53">lower.tail=</span>F, <span
style="color: 0.13,0.29,0.53">df=</span>n[<span
style="color: 0.00,0.00,0.81">1</span>]<span
style="color: 0.81,0.36,0.00"><strong>+</strong></span>n[<span
style="color: 0.00,0.00,0.81">2</span>]<span
style="color: 0.81,0.36,0.00"><strong>-</strong></span><span
style="color: 0.00,0.00,0.81">2</span>),<span
style="color: 0.13,0.29,0.53">digits=</span><span
style="color: 0.00,0.00,0.81">3</span>) p.value <span
style="color: 0.56,0.35,0.01">=</span> <span
style="color: 0.00,0.00,0.81">2</span><span
style="color: 0.81,0.36,0.00"><strong>*</strong></span><span
style="color: 0.13,0.29,0.53"><strong>pt</strong></span>(<span
style="color: 0.13,0.29,0.53"><strong>abs</strong></span>(t<span
style="color: 0.00,0.00,0.81">.0</span>),<span
style="color: 0.13,0.29,0.53">df=</span>n[<span
style="color: 0.00,0.00,0.81">1</span>]<span
style="color: 0.81,0.36,0.00"><strong>+</strong></span>n[<span
style="color: 0.00,0.00,0.81">2</span>]<span
style="color: 0.81,0.36,0.00"><strong>-</strong></span><span
style="color: 0.00,0.00,0.81">2</span>,<span
style="color: 0.13,0.29,0.53">lower.tail=</span>F)</p>
<p><span style="color: 0.13,0.29,0.53"><strong>c</strong></span>(<span
style="color: 0.31,0.60,0.02">"t.0"</span><span
style="color: 0.56,0.35,0.01">=</span>t<span
style="color: 0.00,0.00,0.81">.0</span>,<span
style="color: 0.31,0.60,0.02">"t.*"</span><span
style="color: 0.56,0.35,0.01">=</span>t.star,<span
style="color: 0.31,0.60,0.02">"p.value"</span><span
style="color: 0.56,0.35,0.01">=</span>p.value)</p>
</div>
</div>
<pre><code>##          t.0          t.*      p.value 
## 5.592000e+00 2.074000e+00 1.272907e-05</code></pre>
<p>We see that <span class="math inline">\(t_0 = 5.592\)</span>, the
critical point <span class="math inline">\(t^*\)</span> for <span
class="math inline">\(\alpha = 0.05\)</span> is <span
class="math inline">\(2.074\)</span>, and the <span
class="math inline">\(p\)</span>-value is less than <span
class="math inline">\(.001\)</span>.</p>
<h1 id="q6">Q6</h1>
<p>The experiment finds that the wet drilling method leads to reduced
drilling times compared to the dry drilling method.</p>
<h1 id="q7">Q7</h1>
<div class="snugshade">

</div>
<p><embed src="hw1_files/figure-latex/unnamed-chunk-6-1.pdf" /></p>
<h1 id="q8">Q8</h1>
<p>No, not all dry drilling times exceed all wet drilling times.</p>
<p>However, the boxplot does show that the spread of the drilling times
area approximately the same between the two methods (providing
justification for assuming the two samples have the same variance) and
the mean drilling times are significantly different. As a result, most
of the time, the wet drilling time is going to be less than the dry
drilling time.</p>
<p>For instance, we see that the mean wet drilling time is less than the
best dry drilling time and we also see that the <span
class="math inline">\(25\)</span>-th percentile of the dry method’s
times is a bit larger than the wet method’s longest drilling time. Most
tellingly, we see that around <span class="math inline">\(67\%\)</span>
of the time, the wet drilling time is less than the smallest dry
drilling time.</p>
</body>
</html>
