% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  11pt,
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=.5in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{amsmath}
\usepackage{mathtools}
\usepackage{amsthm}
\usepackage{bm}
\usepackage{xcolor}
\usepackage{fbox}
\usepackage{amsmath}
\usepackage{hw4}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={STAT 581 - HW \#1},
  pdfauthor={Alex Towell (atowell@siue.edu)},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{STAT 581 - HW \#1}
\author{Alex Towell
(\href{mailto:atowell@siue.edu}{\nolinkurl{atowell@siue.edu}})}
\date{}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(}\StringTok{"readxl"}\NormalTok{)}

\CommentTok{\# read from directory the markdown file is located in}
\NormalTok{h1.data }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"./handout1data.xlsx"}\NormalTok{)}
\NormalTok{h1.data}\SpecialCharTok{$}\NormalTok{method }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(h1.data}\SpecialCharTok{$}\NormalTok{method)}

\NormalTok{h1.time.dry }\OtherTok{\textless{}{-}} \FunctionTok{na.omit}\NormalTok{(h1.data}\SpecialCharTok{$}\NormalTok{time[h1.data}\SpecialCharTok{$}\NormalTok{method}\SpecialCharTok{==}\StringTok{\textquotesingle{}d\textquotesingle{}}\NormalTok{])}
\NormalTok{h1.time.wet }\OtherTok{\textless{}{-}} \FunctionTok{na.omit}\NormalTok{(h1.data}\SpecialCharTok{$}\NormalTok{time[h1.data}\SpecialCharTok{$}\NormalTok{method}\SpecialCharTok{!=}\StringTok{\textquotesingle{}d\textquotesingle{}}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

An experiment is designed to investigate whether the time to drill holes
in rock holes using wet or dry drilling. A completely randomized design
(CRD) is used. Each method is replicated on 12 rocks. The drilling times
(in 1 / 100 minutes) are observed to be

\begin{longtable}[]{@{}lrrrrrrrrrrrr@{}}
\toprule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
dry & 727 & 965 & 904 & 987 & 847 & 918 & 814 & 750 & 804 & 989 & 902 &
939 \\
wet & 607 & 549 & 762 & 665 & 588 & 798 & 704 & 772 & 780 & 599 & 603 &
699 \\
\end{longtable}

\hypertarget{q1}{%
\section{Q1}\label{q1}}

\fbox{State the hypotheses of interest. Provide an interpretation, stated in the
context of the problem.}

The hypothesis of interest is whether drilling time is effected by the
choice of wet or dry drilling. We may formulate this as a hypothesis
test of the form

\begin{align*}
  H_0 &: \mu_1 = \mu_2\\
  H_A &: \mu_1 \neq \mu_2\,,
\end{align*} where \(\mu_1\) and \(\mu_2\) are respectively the expected
drilling time for dry and wet drilling.

If \(H_0\) is true, the drilling method has \emph{no} effect on drilling
time. If \(H_A\) is true, the choice does have an effect on drilling
time.

\hypertarget{q2}{%
\section{Q2}\label{q2}}

\fbox{Give two advantages of the completely randomized design.}

Two advantages of the completely randomized design (CRD) are:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  It is simple to implement and analyze.
\item
  It accounts for experimental unit variance, namely by controlling for
  the type I error,

  \[
      \alpha = \Pr(\text{decide} \, H_A | H_0 \, \text{true}),
  \]

  where \(\alpha\) is the probability of a type I error. It may also be
  thought of as the type I \emph{error rate}, or
  \emph{false positive rate}.
\end{enumerate}

\hypertarget{q3}{%
\section{Q3}\label{q3}}

\fbox{Give two disadvantages of the completely randomized design.}

Two disadvantages of the completely randomized design (CRD) are:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  It does not account for type II error, \[
      \beta = \Pr(\text{decide} \, H_0 | H_A \, \text{true}).
  \] where \(\beta\) is the probability of a type II error.

  \begin{quote}
  \textbf{Additional remarks}: Since we may denote a type I error a
  false positive, it may be appropriate to denote a type II error a
  false negative, which implies the convention
  \(H_0 \equiv \rm{negative}\) and \(H_A \equiv \rm{positive}\). Thus,
  \(\beta\) may be thought of as the false negative rate.
  \end{quote}

  \begin{quote}
  Consider the unrelated \emph{Bloom filter}, which is a probabilistic
  data structure that models sets in which membership queries have a
  controllable false positive rate \(\epsilon\) and a false negative
  rate \(0\). If we take the complement of an object representing such a
  Bloom filter, then membership queries on its complement have a false
  positive rate \(0\) and a false negative rate \(\epsilon\).
  \end{quote}
\item
  It does not adjust for differences in experimental units nor
  differences in any other factors.
\end{enumerate}

\hypertarget{q4}{%
\section{Q4}\label{q4}}

\fbox{Compute the sample means, the sample standard deviations, and the pooled
sample standard deviation.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{time.mean }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\FunctionTok{mean}\NormalTok{(h1.time.dry),}
               \FunctionTok{mean}\NormalTok{(h1.time.wet)),}\AttributeTok{digits=}\DecValTok{3}\NormalTok{)}
\NormalTok{time.var }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\FunctionTok{var}\NormalTok{(h1.time.dry),}
              \FunctionTok{var}\NormalTok{(h1.time.wet)),}\AttributeTok{digits=}\DecValTok{3}\NormalTok{)}
\NormalTok{time.sd }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(}\FunctionTok{sqrt}\NormalTok{(time.var),}\AttributeTok{digits=}\DecValTok{3}\NormalTok{)}
\NormalTok{n }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FunctionTok{length}\NormalTok{(h1.time.dry),}
       \FunctionTok{length}\NormalTok{(h1.time.wet))}
\NormalTok{time.sd.pooled }\OtherTok{\textless{}{-}}
  \FunctionTok{round}\NormalTok{(}\FunctionTok{sqrt}\NormalTok{(((n[}\DecValTok{1}\NormalTok{] }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ time.var[}\DecValTok{1}\NormalTok{] }\SpecialCharTok{+}\NormalTok{ (n[}\DecValTok{2}\NormalTok{] }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ time.var[}\DecValTok{2}\NormalTok{]) }\SpecialCharTok{/}\NormalTok{ (}\FunctionTok{sum}\NormalTok{(n)}\SpecialCharTok{{-}}\DecValTok{2}\NormalTok{)),}
        \AttributeTok{digits=}\DecValTok{3}\NormalTok{)}

\FunctionTok{c}\NormalTok{(}\StringTok{"y.bar.1"} \OtherTok{=}\NormalTok{ time.mean[}\DecValTok{1}\NormalTok{],}
  \StringTok{"y.bar.2"} \OtherTok{=}\NormalTok{ time.mean[}\DecValTok{2}\NormalTok{],}
  \StringTok{"s.1"} \OtherTok{=}\NormalTok{ time.sd[}\DecValTok{1}\NormalTok{],}
  \StringTok{"s.2"} \OtherTok{=}\NormalTok{ time.sd[}\DecValTok{2}\NormalTok{],}
  \StringTok{"s.p"} \OtherTok{=}\NormalTok{ time.sd.pooled)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## y.bar.1 y.bar.2     s.1     s.2     s.p 
## 878.833 677.167  89.470  87.189  88.337
\end{verbatim}

We see that the sample means are \[
  (\bar{y}_1,\bar{y}_2) = (878.833, 677.167),
\] the standard deviations are \[
  (s_1,s_2) = (89.47, 87.189),
\] and the pooled standard deviation is \[
  s_p = 88.337.
\]

\hypertarget{q5}{%
\section{Q5}\label{q5}}

\fbox{Compute the $t_0$ statistic, the critical point for a level
$\alpha = .05$ test, and the $p$-value.}

The test statistic is defined as \[
  t_0 = \frac{\bar{y}_1-\bar{y}_2}{s_p \sqrt{\frac{1}{n_1}+\frac{1}{n_2}}}.
\] which is a drawn from a \(t\)-student distribution with \(n_1+n_2-2\)
degrees of freedom under the null model (reference distribution).

\begin{quote}
Under the null model, \(\bar{y}_1\) and \(\bar{y}_2\) are the means of
two samples respectively of size \(n_1\) and \(n_2\) whose elements are
drawn from the same normal distribution.
\end{quote}

Denote this reference distribution by \(T\). Under the null model,
\(t_0\) is a realization of \(T\). Our general approach is to compute
the test statistic \(t_0\) for the given samples and say it is
compatible with the null model if it obtains a value that is not too
extreme under \(T\), e.g., a \(p\)-value that is less than some
controllable parameter \(\alpha\).

The critical point (the minimum value that is considered to be too
extreme) is given by solving for \(t^*\) in \[
  \Pr\{-|t^*| < T < |t^*|\} = \alpha,
\] which has the solution \(t^* = t_{\rm{df}=n_1+n_2-2}(\alpha/2)\), and
\begin{align*}
  \text{$p$-value} &= \Pr\{T \notin [-|t_0|,|t_0|]\}\\
                   &= 2 \Pr\{T > |t_0|\}\\
                   &= 2(1-F_T(|t_0|)),
\end{align*} where \(F_T\) is the cdf of \(T\).

We compute these results in R with:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{se }\OtherTok{\textless{}{-}}\NormalTok{ time.sd.pooled}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{1}\SpecialCharTok{/}\NormalTok{n[}\DecValTok{1}\NormalTok{]}\SpecialCharTok{+}\DecValTok{1}\SpecialCharTok{/}\NormalTok{n[}\DecValTok{2}\NormalTok{])}
\NormalTok{t}\FloatTok{.0} \OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{((time.mean[}\DecValTok{1}\NormalTok{]}\SpecialCharTok{{-}}\NormalTok{time.mean[}\DecValTok{2}\NormalTok{])}\SpecialCharTok{/}\NormalTok{se,}\AttributeTok{digits=}\DecValTok{3}\NormalTok{)}
\NormalTok{alpha }\OtherTok{\textless{}{-}} \FloatTok{0.05}
\NormalTok{t.star }\OtherTok{=} \FunctionTok{round}\NormalTok{(}\FunctionTok{qt}\NormalTok{(alpha}\SpecialCharTok{/}\DecValTok{2}\NormalTok{,}\AttributeTok{lower.tail=}\NormalTok{F, }\AttributeTok{df=}\NormalTok{n[}\DecValTok{1}\NormalTok{]}\SpecialCharTok{+}\NormalTok{n[}\DecValTok{2}\NormalTok{]}\SpecialCharTok{{-}}\DecValTok{2}\NormalTok{),}\AttributeTok{digits=}\DecValTok{3}\NormalTok{)}
\NormalTok{p.value }\OtherTok{=} \DecValTok{2}\SpecialCharTok{*}\FunctionTok{pt}\NormalTok{(}\FunctionTok{abs}\NormalTok{(t}\FloatTok{.0}\NormalTok{),}\AttributeTok{df=}\NormalTok{n[}\DecValTok{1}\NormalTok{]}\SpecialCharTok{+}\NormalTok{n[}\DecValTok{2}\NormalTok{]}\SpecialCharTok{{-}}\DecValTok{2}\NormalTok{,}\AttributeTok{lower.tail=}\NormalTok{F)}

\FunctionTok{c}\NormalTok{(}\StringTok{"t.0"}\OtherTok{=}\NormalTok{t}\FloatTok{.0}\NormalTok{,}\StringTok{"t.*"}\OtherTok{=}\NormalTok{t.star,}\StringTok{"p.value"}\OtherTok{=}\NormalTok{p.value)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          t.0          t.*      p.value 
## 5.592000e+00 2.074000e+00 1.272907e-05
\end{verbatim}

We see that \(t_0 = 5.592\), the critical point \(t^*\) for
\(\alpha = 0.05\) is \(2.074\), and the \(p\)-value is less than
\(.001\).

\hypertarget{q6}{%
\section{Q6}\label{q6}}

\fbox{Provide an interpretation, stated in the context of the problem.}

The experiment finds that the wet drilling method leads to reduced
drilling times compared to the dry drilling method.

\hypertarget{q7}{%
\section{Q7}\label{q7}}

\fbox{Create a boxplot as a graphical display of the data.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{method }\OtherTok{\textless{}{-}} \FunctionTok{na.omit}\NormalTok{(h1.data}\SpecialCharTok{$}\NormalTok{method)}
\NormalTok{times }\OtherTok{\textless{}{-}} \FunctionTok{na.omit}\NormalTok{(h1.data}\SpecialCharTok{$}\NormalTok{time)}
\FunctionTok{boxplot}\NormalTok{(times}\SpecialCharTok{\textasciitilde{}}\NormalTok{method,}\AttributeTok{names=}\FunctionTok{c}\NormalTok{(}\StringTok{"dry"}\NormalTok{,}\StringTok{"wet"}\NormalTok{),}\AttributeTok{xlab=}\StringTok{"method"}\NormalTok{,}\AttributeTok{ylab=}\StringTok{"time"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1_files/figure-latex/unnamed-chunk-6-1.pdf}

\hypertarget{q8}{%
\section{Q8}\label{q8}}

\fbox{\begin{minipage}{\textwidth}
Refering to the boxplot, is it true that all dry drilling times exceed all wet
drilling times?
In what sense can the experiment find that dry drilling takes longer than wet
drilling?
\end{minipage}}

No, not all dry drilling times exceed all wet drilling times.

However, the boxplot does show that the spread of the drilling times
area approximately the same between the two methods (providing
justification for assuming the two samples have the same variance) and
the mean drilling times are significantly different. As a result, most
of the time, the wet drilling time is going to be less than the dry
drilling time.

For instance, we see that the mean wet drilling time is less than the
best dry drilling time and we also see that the \(25\)-th percentile of
the dry method's times is a bit larger than the wet method's longest
drilling time. Most tellingly, we see that around \(67\%\) of the time,
the wet drilling time is less than the smallest dry drilling time.

\end{document}
