<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <meta name="author" content="Alex Towell (atowell@siue.edu)" />
  <title>Discrete Multivariate Analysis - 579 - HW #6</title>
  <style>
    html {
      color: #1a1a1a;
      background-color: #fdfdfd;
    }
    body {
      margin: 0 auto;
      max-width: 36em;
      padding-left: 50px;
      padding-right: 50px;
      padding-top: 50px;
      padding-bottom: 50px;
      hyphens: auto;
      overflow-wrap: break-word;
      text-rendering: optimizeLegibility;
      font-kerning: normal;
    }
    @media (max-width: 600px) {
      body {
        font-size: 0.9em;
        padding: 12px;
      }
      h1 {
        font-size: 1.8em;
      }
    }
    @media print {
      html {
        background-color: white;
      }
      body {
        background-color: transparent;
        color: black;
        font-size: 12pt;
      }
      p, h2, h3 {
        orphans: 3;
        widows: 3;
      }
      h2, h3, h4 {
        page-break-after: avoid;
      }
    }
    p {
      margin: 1em 0;
    }
    a {
      color: #1a1a1a;
    }
    a:visited {
      color: #1a1a1a;
    }
    img {
      max-width: 100%;
    }
    h1, h2, h3, h4, h5, h6 {
      margin-top: 1.4em;
    }
    h5, h6 {
      font-size: 1em;
      font-style: italic;
    }
    h6 {
      font-weight: normal;
    }
    ol, ul {
      padding-left: 1.7em;
      margin-top: 1em;
    }
    li > ol, li > ul {
      margin-top: 0;
    }
    blockquote {
      margin: 1em 0 1em 1.7em;
      padding-left: 1em;
      border-left: 2px solid #e6e6e6;
      color: #606060;
    }
    code {
      font-family: Menlo, Monaco, Consolas, 'Lucida Console', monospace;
      font-size: 85%;
      margin: 0;
      hyphens: manual;
    }
    pre {
      margin: 1em 0;
      overflow: auto;
    }
    pre code {
      padding: 0;
      overflow: visible;
      overflow-wrap: normal;
    }
    .sourceCode {
     background-color: transparent;
     overflow: visible;
    }
    hr {
      background-color: #1a1a1a;
      border: none;
      height: 1px;
      margin: 1em 0;
    }
    table {
      margin: 1em 0;
      border-collapse: collapse;
      width: 100%;
      overflow-x: auto;
      display: block;
      font-variant-numeric: lining-nums tabular-nums;
    }
    table caption {
      margin-bottom: 0.75em;
    }
    tbody {
      margin-top: 0.5em;
      border-top: 1px solid #1a1a1a;
      border-bottom: 1px solid #1a1a1a;
    }
    th {
      border-top: 1px solid #1a1a1a;
      padding: 0.25em 0.5em 0.25em 0.5em;
    }
    td {
      padding: 0.125em 0.5em 0.25em 0.5em;
    }
    header {
      margin-bottom: 4em;
      text-align: center;
    }
    #TOC li {
      list-style: none;
    }
    #TOC ul {
      padding-left: 1.3em;
    }
    #TOC > ul {
      padding-left: 0;
    }
    #TOC a:not(:hover) {
      text-decoration: none;
    }
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    /* The extra [class] is a hack that increases specificity enough to
       override a similar rule in reveal.js */
    ul.task-list[class]{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      font-size: inherit;
      width: 0.8em;
      margin: 0 0.8em 0.2em -1.6em;
      vertical-align: middle;
    }
  </style>
  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="/usr/share/javascript/mathjax/MathJax.js"
  type="text/javascript"></script>
</head>
<body>
<header id="title-block-header">
<h1 class="title">Discrete Multivariate Analysis - 579 - HW #6</h1>
<p class="author">Alex Towell (<a
href="mailto:atowell@siue.edu"><code>atowell@siue.edu</code></a>)</p>
</header>
<h1 id="problem-1">Problem 1</h1>
<p>If we have a non-linear function of some random variable, in the
delta method we use a Taylor approximation of the function centered
around the random variables expected value such that the approximate
variance of the function of the random variable is easily computed.</p>
<p>Let <span class="math inline">\(\operatorname{g}(\hat\pi) =
\log(\hat\pi/(1-\hat\pi))\)</span>. A linear approximation of <span
class="math inline">\(\operatorname{g}\)</span> is given by <span
class="math display">\[\operatorname{\hat g}(\hat\pi) =
\operatorname{g}(\pi) +\operatorname{g&#39;}(\pi)(\hat\pi -
\pi),\]</span> the derivative of <span
class="math inline">\(\operatorname{g}\)</span> is given by <span
class="math display">\[\operatorname{g&#39;}(\pi) =
\frac{1}{\pi(1-\pi)},\]</span> and the variance of <span
class="math inline">\(\operatorname{\hat g}(\hat\pi)\)</span> is given
by <span class="math display">\[\begin{aligned}
  \operatorname{Var}(\operatorname{\hat g}(\hat \pi))
    &amp;= \left(\operatorname{g&#39;}(\pi)\right)^2
\operatorname{Var}(\hat\pi)\\
    &amp;= \frac{1}{\pi^2(1-\pi)^2} \frac{\pi(1-\pi)}{n}\\
    &amp;= \frac{1}{\pi(1-\pi)} \frac{1}{n}.
\end{aligned}\]</span></p>
<p>Since we do not know <span class="math inline">\(\pi\)</span>, we
approximate it with <span class="math inline">\(\hat\pi\)</span>, thus
<span class="math display">\[\sigma^2(\log(\hat\pi/(1-\hat\pi))) =
\frac{1}{\hat\pi(1-\hat\pi)} \frac{1}{n}.\]</span> # Problem 2</p>
<p>Consider data from a retrospective study on the relationship between
daily alcohol consumption and the onset of esophagus cancer.</p>
<table>
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: right;"></th>
<th style="text-align: right;">cancer</th>
<th style="text-align: right;">no cancer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><span>3-4</span></td>
<td style="text-align: right;"><span class="math inline">\(&gt;
80\)</span>g</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">82</td>
</tr>
<tr class="even">
<td style="text-align: right;"></td>
<td style="text-align: right;"><span class="math inline">\(&lt;
80\)</span>g</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">441</td>
</tr>
<tr class="odd">
<td style="text-align: right;"></td>
<td style="text-align: right;">total</td>
<td style="text-align: right;">131</td>
<td style="text-align: right;">523</td>
</tr>
</tbody>
</table>
<h2 id="part-a">Part (a)</h2>
<p>In a retrospective study, the table draws samples from the
conditional probabilities <span class="math inline">\(\operatorname{P}(X
= i | Y = j)\)</span> and we denote <span
class="math inline">\(\operatorname{P}(X = 1 | Y = j)\)</span> by <span
class="math inline">\(p_j\)</span>.</p>
<p>The ML estimator of <span class="math inline">\(p_j\)</span> from the
data in a retrospective study is given by <span
class="math display">\[\hat p_j = \frac{n_{1 j}}{n_{+j}}.\]</span></p>
<p>In a retrospective study, an estimator of <span
class="math inline">\(\sigma(\log \hat\theta)\)</span> is given by <span
class="math display">\[\hat\sigma(\log \hat\theta) = \left[
    \left(\frac{1}{\hat{p}_1} +
\frac{1}{1-\hat{p}_1}\right)\frac{1}{n_{+1}} +
    \left(\frac{1}{\hat{p}_2} +
\frac{1}{1-\hat{p}_2}\right)\frac{1}{n_{+2}} +
    \right]^{1/2}.\]</span></p>
<h2 id="part-b">Part (b)</h2>
<p>It does not depend on the sampling scheme. When asymptotic normality
holds, replacing parameters with statistics invokes the likelihood
principle.</p>
<p>When we substitute the MLE <span class="math inline">\(\hat
p_j\)</span> into the equation for <span class="math inline">\(\hat
\sigma(\log \hat \theta)\)</span>, we get the result <span
class="math display">\[\hat\sigma(\log \hat\theta) = \left(\frac{1}{n_{1
1}} + \frac{1}{n_{2 1}} + \frac{1}{n_{1 2}} + \frac{1}{n_{2 2}}
\right)^{1/2},\]</span> which is the same as for retrospective studies
and cross-sectional studies.</p>
<h2 id="part-c">Part (c)</h2>
<p>Recall <span class="math inline">\(\theta = \frac{p_1 / (1 -
p_1)}{p_2 / (1 - p_2)}\)</span>. If we replace <span
class="math inline">\(p_j\)</span> by its ML estimator <span
class="math inline">\(\hat p_j\)</span>, then <span
class="math display">\[\hat p_1 = \frac{n_{1 1}}{n_{+1}} =
\frac{71}{131} \approx 0.542\]</span> and <span
class="math display">\[\hat p_2 = \frac{n_{1 2}}{n_{+2}} =
\frac{82}{523} \approx 0.157.\]</span> Thus, by the invariance property
of MLEs, <span class="math display">\[\hat\theta = \frac{\hat p_1 / (1 -
\hat p_1)}{\hat p_2 / (1 - \hat p_2)} \approx \frac{0.542 / 0.458}{0.157
/ 0.843} \approx 6.354\]</span> and therefore <span
class="math inline">\(\log \theta \approx \log 6.354 \approx
1.850\)</span>. Next, we need to find the standard deviation of the
<span class="math inline">\(\log \hat\theta\)</span>, <span
class="math display">\[\hat\sigma(\log \hat\theta) = \left[
    \left(\frac{1}{0.542} + \frac{1}{0.458}\right)\frac{1}{131} +
    \left(\frac{1}{0.157} + \frac{1}{0.843}\right)\frac{1}{523}
    \right]^{1/2} \approx 0.213.\]</span></p>
<p>Thus, a <span class="math inline">\(95\%\)</span> confidence interval
for <span class="math inline">\(\log \theta\)</span> is <span
class="math display">\[\log \hat \theta \pm 1.96 \hat\sigma(\log \hat
\theta).\]</span> Plugging in these computed values, we get the <span
class="math inline">\(95\%\)</span> confidence interval <span
class="math display">\[[1.850 - 0.417,1.850 + 0.417] =
[1.433,2.267].\]</span></p>
<h2 id="part-d">Part (d)</h2>
<p>Observe that <span class="math display">\[\hat\gamma =
\frac{\hat\theta-1}{\hat\theta+1}.\]</span> The MLE <span
class="math inline">\(\hat\theta \approx 6.354\)</span>. Thus, <span
class="math inline">\(\hat\gamma \approx \frac{6.354-1}{6.354+1} \approx
0.728\)</span>.</p>
<p>We estimate that there is a <em>large</em> size, positive association
between daily alcohol consumption and the onset of cancer.</p>
<h1 id="problem-3">Problem 3</h1>
<p>For the <em>counts</em> array, we populated it with the values <span
class="math inline">\((7,7,2,3,2,8,3,7,1,5,4,9,2,8,9,14)\)</span> and
ran the code.</p>
<pre><code>##       2.5%        25%        50%        75%      97.5% 
## 0.09879317 0.24392244 0.31425372 0.38217439 0.50166928</code></pre>
<p>Thus, a <span class="math inline">\(95\%\)</span> interval estimate
is approximately <span class="math inline">\([0.1,0.5]\)</span>.</p>
</body>
</html>
