% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{amsmath}
\usepackage{mathtools}
\usepackage{amsthm}
\usepackage{multirow}
\usepackage{booktabs}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Discrete Multivariate Analysis - 579 - HW \#6},
  pdfauthor={Alex Towell (atowell@siue.edu)},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Discrete Multivariate Analysis - 579 - HW \#6}
\author{Alex Towell
(\href{mailto:atowell@siue.edu}{\nolinkurl{atowell@siue.edu}})}
\date{}

\begin{document}
\maketitle

\newcommand{\var}{\operatorname{Var}}
\newcommand{\expect}{\operatorname{E}}
\newcommand{\corr}{\operatorname{Corr}}
\newcommand{\cov}{\operatorname{Cov}}
\newcommand{\ssr}{\operatorname{SSR}}
\newcommand{\se}{\operatorname{SE}}
\newcommand{\mat}[1]{\mathbf{#1}}
\newcommand{\RR}{\operatorname{RR}}
\newcommand{\eval}[2]{\left. #1 \right\vert_{#2}}

\hypertarget{problem-1}{%
\section{Problem 1}\label{problem-1}}

\fbox{
\begin{minipage}{.8\textwidth}
Suppose $n_1 \sim \rm{BIN}(n,\pi)$. Then, $\hat\pi = n_1/n$ has an asymptotic
normal distribution $\mathcal{N}(\pi,\pi(1-\pi)/n)$. Use the delta method
to determine $\sigma^2 \log(\hat\pi/(1-\hat\pi))$, the asymptotic variance
of the sample log odds.
\end{minipage}
}

If we have a non-linear function of some random variable, in the delta
method we use a Taylor approximation of the function centered around the
random variables expected value such that the approximate variance of
the function of the random variable is easily computed.

Let \(\operatorname{g}(\hat\pi) = \log(\hat\pi/(1-\hat\pi))\). A linear
approximation of \(\operatorname{g}\) is given by \[
  \operatorname{\hat g}(\hat\pi) = \operatorname{g}(\pi) +\operatorname{g'}(\pi)(\hat\pi - \pi),
\] the derivative of \(\operatorname{g}\) is given by \[
  \operatorname{g'}(\pi) = \frac{1}{\pi(1-\pi)},
\] and the variance of \(\operatorname{\hat g}(\hat\pi)\) is given by
\begin{align*}
  \operatorname{Var}(\operatorname{\hat g}(\hat \pi))
    &= \left(\operatorname{g'}(\pi)\right)^2 \operatorname{Var}(\hat\pi)\\
    &= \frac{1}{\pi^2(1-\pi)^2} \frac{\pi(1-\pi)}{n}\\
    &= \frac{1}{\pi(1-\pi)} \frac{1}{n}.
\end{align*}

Since we do not know \(\pi\), we approximate it with \(\hat\pi\), thus
\[
  \sigma^2(\log(\hat\pi/(1-\hat\pi))) = \frac{1}{\hat\pi(1-\hat\pi)} \frac{1}{n}.
\] \# Problem 2

Consider data from a retrospective study on the relationship between
daily alcohol consumption and the onset of esophagus cancer.

\begin{table}[h]
\centering
\begin{tabular}{@{}rrrr@{}}
\toprule
                                            &           & cancer&no cancer\\
\cmidrule{3-4}
\multirow{2}{*}{daily alcohol consumption}  & $> 80$g   & 71    & 82\\
                                            & $< 80$g   & 60    & 441\\
                                            & total     & 131   & 523\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{part-a}{%
\subsection{Part (a)}\label{part-a}}

\fbox{Provide an equation for $\hat\sigma(\log \hat\theta)$.}

In a retrospective study, the table draws samples from the conditional
probabilities \(\operatorname{P}(X = i | Y = j)\) and we denote
\(\operatorname{P}(X = 1 | Y = j)\) by \(p_j\).

The ML estimator of \(p_j\) from the data in a retrospective study is
given by \[
  \hat p_j = \frac{n_{1 j}}{n_{+j}}.
\]

In a retrospective study, an estimator of \(\sigma(\log \hat\theta)\) is
given by \[
  \hat\sigma(\log \hat\theta) = \left[
    \left(\frac{1}{\hat{p}_1} + \frac{1}{1-\hat{p}_1}\right)\frac{1}{n_{+1}} +
    \left(\frac{1}{\hat{p}_2} + \frac{1}{1-\hat{p}_2}\right)\frac{1}{n_{+2}} +
    \right]^{1/2}.
\]

\hypertarget{part-b}{%
\subsection{Part (b)}\label{part-b}}

\fbox{Does your answer in (a) depend on the sampling scheme? Explain.}

It does not depend on the sampling scheme. When asymptotic normality
holds, replacing parameters with statistics invokes the likelihood
principle.

When we substitute the MLE \(\hat p_j\) into the equation for
\(\hat \sigma(\log \hat \theta)\), we get the result \[
  \hat\sigma(\log \hat\theta) = \left(\frac{1}{n_{1 1}} + \frac{1}{n_{2 1}} + \frac{1}{n_{1 2}} + \frac{1}{n_{2 2}} \right)^{1/2},
\] which is the same as for retrospective studies and cross-sectional
studies.

\hypertarget{part-c}{%
\subsection{Part (c)}\label{part-c}}

\fbox{Compute a $95\%$ confidence interval for $\log \theta$.}

Recall \(\theta = \frac{p_1 / (1 - p_1)}{p_2 / (1 - p_2)}\). If we
replace \(p_j\) by its ML estimator \(\hat p_j\), then \[
  \hat p_1 = \frac{n_{1 1}}{n_{+1}} = \frac{71}{131} \approx 0.542
\] and \[
  \hat p_2 = \frac{n_{1 2}}{n_{+2}} = \frac{82}{523} \approx 0.157.
\] Thus, by the invariance property of MLEs, \[
  \hat\theta = \frac{\hat p_1 / (1 - \hat p_1)}{\hat p_2 / (1 - \hat p_2)} \approx \frac{0.542 / 0.458}{0.157 / 0.843} \approx 6.354
\] and therefore \(\log \theta \approx \log 6.354 \approx 1.850\). Next,
we need to find the standard deviation of the \(\log \hat\theta\), \[
  \hat\sigma(\log \hat\theta) = \left[
    \left(\frac{1}{0.542} + \frac{1}{0.458}\right)\frac{1}{131} +
    \left(\frac{1}{0.157} + \frac{1}{0.843}\right)\frac{1}{523}
    \right]^{1/2} \approx 0.213.
\]

Thus, a \(95\%\) confidence interval for \(\log \theta\) is \[
  \log \hat \theta \pm 1.96 \hat\sigma(\log \hat \theta).
\] Plugging in these computed values, we get the \(95\%\) confidence
interval \[
  [1.850 - 0.417,1.850 + 0.417] = [1.433,2.267].
\]

\hypertarget{part-d}{%
\subsection{Part (d)}\label{part-d}}

\fbox{
\begin{minipage}{.8\textwidth}
Compute $\hat\gamma$ for the $2\times 2$ table.
Provide an interpretation of the effect size, stated in the context of the problem.
\end{minipage}
}

Observe that \[
  \hat\gamma = \frac{\hat\theta-1}{\hat\theta+1}.
\] The MLE \(\hat\theta \approx 6.354\). Thus,
\(\hat\gamma \approx \frac{6.354-1}{6.354+1} \approx 0.728\).

We estimate that there is a \emph{large} size, positive association
between daily alcohol consumption and the onset of cancer.

\hypertarget{problem-3}{%
\section{Problem 3}\label{problem-3}}

For the \emph{counts} array, we populated it with the values
\((7,7,2,3,2,8,3,7,1,5,4,9,2,8,9,14)\) and ran the code.

\begin{verbatim}
##       2.5%        25%        50%        75%      97.5% 
## 0.09879317 0.24392244 0.31425372 0.38217439 0.50166928
\end{verbatim}

Thus, a \(95\%\) interval estimate is approximately \([0.1,0.5]\).

\end{document}
