% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{amsmath}
\usepackage{mathtools}
\usepackage{amsthm}
\usepackage{bm}
\usepackage{xcolor}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Computational Statistics - STAT 575 - HW \#1},
  pdfauthor={Alex Towell (atowell@siue.edu)},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Computational Statistics - STAT 575 - HW \#1}
\author{Alex Towell
(\href{mailto:atowell@siue.edu}{\nolinkurl{atowell@siue.edu}})}
\date{}

\begin{document}
\maketitle

\hypertarget{problem-1}{%
\section{Problem 1}\label{problem-1}}

This is a test

Write your own code and find solution to the equation
\(x^3 + x - 4 = 0\) using Newton's method and the secant method. Compare
the number of iterations needed for different starting values for the
two methods.

\hypertarget{solution-newtons-method}{%
\subsection{Solution: Newton's method}\label{solution-newtons-method}}

If we have some function \(f : \mathbb{R} \mapsto \mathbb{R}\) and we
wish to find a root of \(f\), i.e., an \(x\) such that \(f(x) = 0\), we
may use Newton's method.

We take an initial guess of the root as \(x_0\) and try to refine it
with a linear approximation of \(f\) given by \[
  L(f | x_0) = \lambda x.f(x_0) + f'(x_0)(x-x_0).
\]

Now, we may approximate a root of \(f\) with a root of \(L(f|x_0)\), \[
  L(f|x_0)(x) = 0,
\] which may be rewritten as \[
  f(x_0) + f'(x_0)(x-x_0) = 0.
\] Solving for a root \(x\) of \(L(f|x_0)\) we get the result \[
  x = x_0 - \frac{f(x_0)}{f'(x_0)}.
\]

Hoping that \(x\) results in a better approximation of the root of \(f\)
than \(x_0\), we approximate \(f\) with \(L(f|x)\) and repeat the
process.

Generalizing this result, we obtain the iterative procedure \[
  x_{i+1} = x_i - \frac{f(x_i)}{f'(x_i)}.
\] We continue this process until we obtain some stopping condition,
e.g., \(|x_{i+1} - x_i| < \epsilon\).

Letting \(f(x) = x^3 + x - 4\) and \(f'(x) = 3x^2 + 1\) and substituting
into the above result, we get the result \[
  x_{i+1} = x_i - \frac{x_i^3+x_i-4}{3x_i^2+1}.
\]

We implement a general procedure for Newton's method:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{newton\_method }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(f,dfdx,x0,}\AttributeTok{eps=}\FloatTok{1e{-}3}\NormalTok{, }\AttributeTok{debug=}\NormalTok{T)}
\NormalTok{\{}
\NormalTok{  n }\OtherTok{\textless{}{-}} \DecValTok{0}
  \ControlFlowTok{repeat}
\NormalTok{  \{}
\NormalTok{    x1 }\OtherTok{\textless{}{-}}\NormalTok{ x0 }\SpecialCharTok{{-}} \FunctionTok{f}\NormalTok{(x0) }\SpecialCharTok{/} \FunctionTok{dfdx}\NormalTok{(x0)}
\NormalTok{    n }\OtherTok{\textless{}{-}}\NormalTok{ n }\SpecialCharTok{+} \DecValTok{1}
   
    \ControlFlowTok{if}\NormalTok{ (debug}\SpecialCharTok{==}\NormalTok{T) \{ }\FunctionTok{cat}\NormalTok{(}\StringTok{"iteration="}\NormalTok{,n,}\StringTok{" x="}\NormalTok{,x1,}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{) \}}
    \ControlFlowTok{if}\NormalTok{(}\FunctionTok{abs}\NormalTok{(x1 }\SpecialCharTok{{-}}\NormalTok{ x0) }\SpecialCharTok{\textless{}}\NormalTok{ eps) \{ }\ControlFlowTok{break}\NormalTok{ \}}
\NormalTok{    x0 }\OtherTok{\textless{}{-}}\NormalTok{ x1}
\NormalTok{  \}}
  \FunctionTok{list}\NormalTok{(}\AttributeTok{root=}\NormalTok{x0,}\AttributeTok{iter=}\NormalTok{n)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

We take an initial guess of \(x_0 = 1\) and
\(\epsilon = 1 \times 10^{-6}\) and run the following R code to solve
for a root of \(f\) using Newton's method:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{f }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x) \{ x}\SpecialCharTok{\^{}}\DecValTok{3} \SpecialCharTok{+}\NormalTok{ x }\SpecialCharTok{{-}} \DecValTok{4}\NormalTok{ \}}
\NormalTok{dfdx }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x) \{ }\DecValTok{3}\SpecialCharTok{*}\NormalTok{x}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+} \DecValTok{1}\NormalTok{ \}}
\NormalTok{eps }\OtherTok{\textless{}{-}} \FloatTok{1e{-}6}
\NormalTok{x0 }\OtherTok{\textless{}{-}} \DecValTok{1}
\NormalTok{result }\OtherTok{\textless{}{-}} \FunctionTok{newton\_method}\NormalTok{(f,dfdx,x0,eps)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## iteration= 1  x= 1.5 
## iteration= 2  x= 1.387097 
## iteration= 3  x= 1.378839 
## iteration= 4  x= 1.378797 
## iteration= 5  x= 1.378797
\end{verbatim}

We obtain \(x \approx 1.3787967\) after \(5\) iterations. When we plug
that approximate root into \(f\) we obtain the result
\(f(1.3787967) = \ensuremath{7.3825959\times 10^{-9}}\), which is
approximately zero.

\hypertarget{solution-secant-method}{%
\subsection{Solution: Secant method}\label{solution-secant-method}}

In Newton's method, we linearize \(f\) using the derivative of \(f\).
If, instead, we use the secant of \(f\) with respect to two inputs
\(x_i\) and \(x_{i+1}\), as given by \[
  \frac{f(x_{i+1}) - f(x_i)}{x_{i+1}-x_i},
\] we get the iterative procedure \[
  x_{i+2} = x_{i+1} - f(x_{i+1})\frac{x_{i+1}-x_i}{f(x_{i+1}) - f(x_i)},
\] which requires two initial values \(x_0\) and \(x_1\).

We define the secant method as a function given by:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{secant\_method }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(f,x0,x1,eps,}\AttributeTok{debug=}\NormalTok{T)}
\NormalTok{\{}
\NormalTok{  n }\OtherTok{\textless{}{-}} \DecValTok{0}
  \ControlFlowTok{repeat}
\NormalTok{  \{}
\NormalTok{    x2 }\OtherTok{\textless{}{-}}\NormalTok{ x1 }\SpecialCharTok{{-}} \FunctionTok{f}\NormalTok{(x1) }\SpecialCharTok{*}\NormalTok{ (x1 }\SpecialCharTok{{-}}\NormalTok{ x0) }\SpecialCharTok{/}\NormalTok{ (}\FunctionTok{f}\NormalTok{(x1) }\SpecialCharTok{{-}} \FunctionTok{f}\NormalTok{(x0))}
\NormalTok{    n }\OtherTok{\textless{}{-}}\NormalTok{ n }\SpecialCharTok{+} \DecValTok{1}
    
    \ControlFlowTok{if}\NormalTok{ (debug}\SpecialCharTok{==}\NormalTok{T) \{ }\FunctionTok{cat}\NormalTok{(}\StringTok{"iteration="}\NormalTok{,n,}\StringTok{" x="}\NormalTok{,x2,}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{) \}}
    
    \ControlFlowTok{if}\NormalTok{(}\FunctionTok{abs}\NormalTok{(x2}\SpecialCharTok{{-}}\NormalTok{x1) }\SpecialCharTok{\textless{}}\NormalTok{ eps)}
\NormalTok{    \{}
      \ControlFlowTok{break}
\NormalTok{    \}}
\NormalTok{    x0 }\OtherTok{\textless{}{-}}\NormalTok{ x1}
\NormalTok{    x1 }\OtherTok{\textless{}{-}}\NormalTok{ x2}
\NormalTok{  \}}
  
  \FunctionTok{list}\NormalTok{(}\AttributeTok{root=}\NormalTok{x1,}\AttributeTok{iter=}\NormalTok{n)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

We let \(x_0 = 0\), \(x_1 = 1\), and keep everything else the same and
run the secant method with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x0 }\OtherTok{\textless{}{-}} \DecValTok{0}
\NormalTok{x1 }\OtherTok{\textless{}{-}} \DecValTok{1}
\NormalTok{result }\OtherTok{\textless{}{-}} \FunctionTok{secant\_method}\NormalTok{(f,x0,x1,eps,F)}
\end{Highlighting}
\end{Shaded}

We obtain \(x \approx 1.3787965\) after \(7\) iterations. When we plug
that approximate root into \(f\) we obtain the result
\(f(1.3787965) = \ensuremath{-1.268648\times 10^{-6}}\), which is
approximately zero.

Note that this is \(2\) more iterations than Newton's method.

\hypertarget{comparison-of-newtons-method-versus-secant-method}{%
\subsection{Comparison of Newton's method versus secant
method}\label{comparison-of-newtons-method-versus-secant-method}}

We perform \(10000\) trials to get a better view of how the two methods,
Newton and secant, compare over many different initial guesses.

We generate the data with:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{10000}
\NormalTok{from }\OtherTok{\textless{}{-}} \DecValTok{0}
\NormalTok{to }\OtherTok{\textless{}{-}} \DecValTok{4}
\NormalTok{by }\OtherTok{\textless{}{-}}\NormalTok{ (to}\SpecialCharTok{{-}}\NormalTok{from)}\SpecialCharTok{/}\NormalTok{n}
\NormalTok{newt\_sols }\OtherTok{\textless{}{-}} \FunctionTok{vector}\NormalTok{(}\AttributeTok{length=}\NormalTok{n)}
\NormalTok{sec\_sols }\OtherTok{\textless{}{-}} \FunctionTok{vector}\NormalTok{(}\AttributeTok{length=}\NormalTok{n)}
\NormalTok{i }\OtherTok{\textless{}{-}} \DecValTok{1}
\ControlFlowTok{for}\NormalTok{ (x0 }\ControlFlowTok{in} \FunctionTok{seq}\NormalTok{(}\AttributeTok{from=}\NormalTok{from, }\AttributeTok{to=}\NormalTok{to, }\AttributeTok{by=}\NormalTok{by))}
\NormalTok{\{}
\NormalTok{  newt\_sols[i] }\OtherTok{\textless{}{-}} \FunctionTok{newton\_method}\NormalTok{(f,dfdx,x0,eps,F)}\SpecialCharTok{$}\NormalTok{iter}
\NormalTok{  sec\_sols[i] }\OtherTok{\textless{}{-}} \FunctionTok{secant\_method}\NormalTok{(f,x0,x0}\SpecialCharTok{+}\DecValTok{1}\NormalTok{,eps,F)}\SpecialCharTok{$}\NormalTok{iter}
\NormalTok{  i }\OtherTok{\textless{}{-}}\NormalTok{ i }\SpecialCharTok{+} \DecValTok{1}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

We summarize the results and report them with:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"mean iterations}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{,}
    \StringTok{"newton =\textgreater{} "}\NormalTok{, }\FunctionTok{mean}\NormalTok{(newt\_sols), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{,}
    \StringTok{"secant =\textgreater{} "}\NormalTok{, }\FunctionTok{mean}\NormalTok{(sec\_sols), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## mean iterations
##  newton =>  5.819618 
##  secant =>  7.231077
\end{verbatim}

We see that Newton's method, on average, requires \(1.4114589\) fewer
iterations before the stopping condition is satisfied.

\hypertarget{problem-2}{%
\section{Problem 2}\label{problem-2}}

Poisson regression. The Ache hunting data set has \(n = 47\)
observations recording is the number of monkeys killed over a period of
days with each hunter along with hunter's age. It is of interest to
estimate and quantify the monkey kill rate as a function of hunter's
age. Hunting prowess confers elevated status among the group, so a
natural question is whether hunting ability improves with age, and at
which age hunting ability is best.

Hand-code Newton-Raphson in R to fit the Poisson regression model \[
  \texttt{monkeys}_i \sim \operatorname{Poi}\left(\exp(\log \texttt{days}_i  + \theta_1 + \theta_2 \texttt{age}_i + \theta_3 \texttt{age}_i^2)\right).
\]

Feel free to use jacobian and hessian in the numDeriv R package. You may
need a sets of crude starting values. I run a linear regression for the
``empirical log-rates'' and get starting values
\((5.99, 0.167, 0.001)\). Feel free to use those. Compare your result
with glm() function in R using

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{glm}\NormalTok{(monkeys}\SpecialCharTok{\textasciitilde{}}\NormalTok{age}\SpecialCharTok{+}\FunctionTok{I}\NormalTok{(age}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{), }\AttributeTok{family=}\StringTok{"poisson"}\NormalTok{, }\AttributeTok{offset=}\FunctionTok{log}\NormalTok{(days), }\AttributeTok{data=}\NormalTok{d)}
\end{Highlighting}
\end{Shaded}

\hypertarget{solution}{%
\subsection{Solution}\label{solution}}

We are given the following data:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d }\OtherTok{\textless{}{-}} \FunctionTok{read.table}\NormalTok{(}\StringTok{"ache.txt"}\NormalTok{, }\AttributeTok{header=}\NormalTok{T) }
\NormalTok{n }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(d}\SpecialCharTok{$}\NormalTok{age)}
\NormalTok{X }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{,n), d}\SpecialCharTok{$}\NormalTok{age, d}\SpecialCharTok{$}\NormalTok{age}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}

\NormalTok{loglike }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(theta)}
\NormalTok{\{}
  \FunctionTok{sum}\NormalTok{(}\FunctionTok{dpois}\NormalTok{(d}\SpecialCharTok{$}\NormalTok{monkeys,}\FunctionTok{exp}\NormalTok{(}\FunctionTok{log}\NormalTok{(d}\SpecialCharTok{$}\NormalTok{days)}\SpecialCharTok{+}\NormalTok{X}\SpecialCharTok{\%*\%}\NormalTok{theta),}\AttributeTok{log=}\NormalTok{T))}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

We generalize the univariate Newton's method in Problem 1 to the
multivariate case. We implement the multivariate Newton-Raphson method
with numerical hessian and jacobian with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(numDeriv)}
\NormalTok{newton\_raphson\_method }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x0,f,eps)}
\NormalTok{\{}
\NormalTok{  n }\OtherTok{\textless{}{-}} \DecValTok{0}
\NormalTok{  x1 }\OtherTok{\textless{}{-}}\NormalTok{ x0}
  \ControlFlowTok{repeat}
\NormalTok{  \{}
\NormalTok{      x1 }\OtherTok{\textless{}{-}}\NormalTok{ x0 }\SpecialCharTok{{-}} \FunctionTok{solve}\NormalTok{(}\FunctionTok{hessian}\NormalTok{(f,x0))}\SpecialCharTok{\%*\%}\FunctionTok{t}\NormalTok{(}\FunctionTok{jacobian}\NormalTok{(f,x0))}
\NormalTok{      n }\OtherTok{\textless{}{-}}\NormalTok{ n }\SpecialCharTok{+} \DecValTok{1}
      \ControlFlowTok{if}\NormalTok{ (n }\SpecialCharTok{\%\%} \DecValTok{7} \SpecialCharTok{==} \DecValTok{0}\NormalTok{) \{ }\FunctionTok{cat}\NormalTok{(}\StringTok{"iteration="}\NormalTok{,n,}\StringTok{" theta="}\NormalTok{,x1,}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{) \}}
      \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{max}\NormalTok{(}\FunctionTok{abs}\NormalTok{(x1 }\SpecialCharTok{{-}}\NormalTok{ x0)) }\SpecialCharTok{\textless{}}\NormalTok{ eps)}
\NormalTok{      \{}
        \ControlFlowTok{break}
\NormalTok{      \}}
\NormalTok{      x0 }\OtherTok{\textless{}{-}}\NormalTok{ x1}
\NormalTok{  \}}
  \FunctionTok{list}\NormalTok{(}\AttributeTok{root=}\NormalTok{x1,}\AttributeTok{iter=}\NormalTok{n)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

We use the multivariate Newton-Raphson method to find the MLE of
\(\theta\) in the poisson regression model:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{eps }\OtherTok{\textless{}{-}} \FloatTok{1e{-}6}
\NormalTok{theta0 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FloatTok{5.99}\NormalTok{, }\FloatTok{0.167}\NormalTok{, }\FloatTok{0.001}\NormalTok{) }\CommentTok{\# starting values}
\NormalTok{theta\_mle }\OtherTok{\textless{}{-}} \FunctionTok{newton\_raphson\_method}\NormalTok{(theta0,loglike,eps)}\SpecialCharTok{$}\NormalTok{root}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## iteration= 7  theta= -1.003658 0.1667888 0.001001747 
## iteration= 14  theta= -7.58365 0.1530251 0.00111402 
## iteration= 21  theta= 1.438523 -0.2696733 0.003827107 
## iteration= 28  theta= -5.484246 0.1246477 -0.001203418
\end{verbatim}

The MLE of \(\theta\) is given by:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{theta\_mle}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              [,1]
## [1,] -5.484245904
## [2,]  0.124647667
## [3,] -0.001203418
\end{verbatim}

We compare the results with the builtin method:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{glm}\NormalTok{(monkeys}\SpecialCharTok{\textasciitilde{}}\NormalTok{age}\SpecialCharTok{+}\FunctionTok{I}\NormalTok{(age}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{),}\AttributeTok{family=}\StringTok{"poisson"}\NormalTok{, }\AttributeTok{offset=}\FunctionTok{log}\NormalTok{(days),}\AttributeTok{data=}\NormalTok{d)}\SpecialCharTok{$}\NormalTok{coefficients}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  (Intercept)          age     I(age^2) 
## -5.484245904  0.124647667 -0.001203418
\end{verbatim}

The hand-coded approach and the builtin approach obtain the same point
estimate \(\hat\theta = (-5.4842, 0.1246, -0.0012)'\).

\hypertarget{problem-3}{%
\section{Problem 3}\label{problem-3}}

Logistic and Cauchy distributions are well-suited to the inverse
transform method. For each of the following, generate \(10,000\) random
variables using the inverse transform. Compare your program with the
built-in R functions rlogis() and rcauchy(), respectively:

\hypertarget{solution-part-a}{%
\subsection{Solution: part (a)}\label{solution-part-a}}

Standard logistic distribution \[
  F(x) = \frac{1}{1+e^{-x}}
\]

Solve for \(x\) in \[
  u = F(x)\\
\] \[
  u = \frac{1}{1+e^{-x}}\\
\] \[
  x = \log(u/(1-u)).
\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{10000}
\NormalTok{us }\OtherTok{\textless{}{-}} \FunctionTok{runif}\NormalTok{(n)}
\NormalTok{d1 }\OtherTok{\textless{}{-}} \FunctionTok{density}\NormalTok{(}\FunctionTok{log}\NormalTok{(us}\SpecialCharTok{/}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{us)))}
\NormalTok{d2 }\OtherTok{\textless{}{-}} \FunctionTok{density}\NormalTok{(}\FunctionTok{rlogis}\NormalTok{(n))}
\FunctionTok{plot}\NormalTok{(d1,}\AttributeTok{col=}\StringTok{"blue"}\NormalTok{,}\AttributeTok{main=}\StringTok{"comparison of density plots"}\NormalTok{)}
\FunctionTok{lines}\NormalTok{(d2,}\AttributeTok{col=}\StringTok{"red"}\NormalTok{)}
\FunctionTok{legend}\NormalTok{(}\AttributeTok{x=}\StringTok{"topright"}\NormalTok{,}\AttributeTok{legend=}\FunctionTok{c}\NormalTok{(}\StringTok{"inverse method"}\NormalTok{,}\StringTok{"built{-}in"}\NormalTok{),}\AttributeTok{col=}\FunctionTok{c}\NormalTok{(}\StringTok{"blue"}\NormalTok{,}\StringTok{"red"}\NormalTok{),}
       \AttributeTok{pch=}\FunctionTok{c}\NormalTok{(}\StringTok{"{-}"}\NormalTok{,}\StringTok{"{-}"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1.mod_files/figure-latex/unnamed-chunk-13-1.pdf}

\hypertarget{solution-part-b}{%
\subsection{Solution: part (b)}\label{solution-part-b}}

Standard Cauchy distribution \[
  F(x) = \frac{1}{2} + \frac{1}{\pi} \operatorname{arctan(x)}
\]

Solve for \(x\) in \[
  u = F(x)
\] \[
  u = \frac{1}{2} + \frac{1}{\pi} \operatorname{arctan(x)}
\] \[
  x = \tan(\pi(u-1/2)).
\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{1000}
\NormalTok{us }\OtherTok{\textless{}{-}} \FunctionTok{runif}\NormalTok{(n)}
\NormalTok{d1 }\OtherTok{\textless{}{-}} \FunctionTok{tan}\NormalTok{(pi}\SpecialCharTok{*}\NormalTok{(us}\FloatTok{{-}0.5}\NormalTok{))}
\NormalTok{d2 }\OtherTok{\textless{}{-}} \FunctionTok{rcauchy}\NormalTok{(}\AttributeTok{n=}\NormalTok{n)}

\NormalTok{d1 }\OtherTok{\textless{}{-}}\NormalTok{ d1[d1 }\SpecialCharTok{\textgreater{}} \SpecialCharTok{{-}}\DecValTok{20} \SpecialCharTok{\&}\NormalTok{ d1 }\SpecialCharTok{\textless{}} \DecValTok{20}\NormalTok{]}
\NormalTok{d2 }\OtherTok{\textless{}{-}}\NormalTok{ d2[d2 }\SpecialCharTok{\textgreater{}} \SpecialCharTok{{-}}\DecValTok{20} \SpecialCharTok{\&}\NormalTok{ d2 }\SpecialCharTok{\textless{}} \DecValTok{20}\NormalTok{]}

\NormalTok{c1 }\OtherTok{\textless{}{-}} \FunctionTok{rgb}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{255}\NormalTok{, }\AttributeTok{max =} \DecValTok{255}\NormalTok{, }\AttributeTok{alpha =} \DecValTok{50}\NormalTok{, }\AttributeTok{names =} \StringTok{"blue"}\NormalTok{)}
\NormalTok{c2 }\OtherTok{\textless{}{-}} \FunctionTok{rgb}\NormalTok{(}\DecValTok{255}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{, }\AttributeTok{max =} \DecValTok{255}\NormalTok{, }\AttributeTok{alpha =} \DecValTok{50}\NormalTok{, }\AttributeTok{names =} \StringTok{"red"}\NormalTok{)}

\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\FunctionTok{hist}\NormalTok{(d1,}\AttributeTok{col=}\NormalTok{c1,}\AttributeTok{freq=}\NormalTok{F,}\AttributeTok{breaks=}\DecValTok{50}\NormalTok{,}\AttributeTok{main=}\StringTok{"inverse{-}transform method vs built{-}in"}\NormalTok{)}
\FunctionTok{hist}\NormalTok{(d2,}\AttributeTok{col=}\NormalTok{c2,}\AttributeTok{add=}\NormalTok{T,}\AttributeTok{freq=}\NormalTok{F,}\AttributeTok{breaks=}\DecValTok{50}\NormalTok{)}
\FunctionTok{legend}\NormalTok{(}\AttributeTok{x=}\StringTok{"topright"}\NormalTok{,}\AttributeTok{legend=}\FunctionTok{c}\NormalTok{(}\StringTok{"inv"}\NormalTok{,}\StringTok{"builtin"}\NormalTok{),}\AttributeTok{col=}\FunctionTok{c}\NormalTok{(}\StringTok{"blue"}\NormalTok{,}\StringTok{"red"}\NormalTok{),}\AttributeTok{pch=}\FunctionTok{c}\NormalTok{(}\StringTok{"{-}"}\NormalTok{,}\StringTok{"{-}"}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{density}\NormalTok{(d1), }\AttributeTok{col=}\StringTok{"blue"}\NormalTok{,}\AttributeTok{main=}\StringTok{"density plot"}\NormalTok{)}
\FunctionTok{lines}\NormalTok{(}\FunctionTok{density}\NormalTok{(d2), }\AttributeTok{col=}\StringTok{"red"}\NormalTok{) }
\FunctionTok{legend}\NormalTok{(}\AttributeTok{x=}\StringTok{"topright"}\NormalTok{,}\AttributeTok{legend=}\FunctionTok{c}\NormalTok{(}\StringTok{"inv"}\NormalTok{,}\StringTok{"builtin"}\NormalTok{),}\AttributeTok{col=}\FunctionTok{c}\NormalTok{(}\StringTok{"blue"}\NormalTok{,}\StringTok{"red"}\NormalTok{),}\AttributeTok{pch=}\FunctionTok{c}\NormalTok{(}\StringTok{"{-}"}\NormalTok{,}\StringTok{"{-}"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1.mod_files/figure-latex/unnamed-chunk-14-1.pdf}

\hypertarget{problem-4}{%
\section{Problem 4}\label{problem-4}}

Generating \(10,000\) random variables from
\(\operatorname{Geometric}(p)\) distribution based off Bernoulli trials.

\hypertarget{solution-1}{%
\subsection{Solution}\label{solution-1}}

A random variable \(X \sim \operatorname{Geometric(p)}\) is given by the
number of i.i.d. trials needed to have a success where success occurs
with probability \(p\).

Thus, we may simulate this distribution with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# simulate n realizes of geometric(p)}
\NormalTok{rgeo }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(n,p)}
\NormalTok{\{}
\NormalTok{  outcomes }\OtherTok{\textless{}{-}} \FunctionTok{vector}\NormalTok{(}\AttributeTok{length=}\NormalTok{n)}
  \ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\NormalTok{n)}
\NormalTok{  \{}
\NormalTok{    trials }\OtherTok{\textless{}{-}} \DecValTok{0}
    \ControlFlowTok{while}\NormalTok{ (T)}
\NormalTok{    \{}
\NormalTok{      trials }\OtherTok{\textless{}{-}}\NormalTok{ trials }\SpecialCharTok{+} \DecValTok{1}
      \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{rbinom}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{,p) }\SpecialCharTok{==} \DecValTok{1}\NormalTok{)}
\NormalTok{      \{}
        \ControlFlowTok{break}
\NormalTok{      \}}
\NormalTok{    \}}
\NormalTok{    outcomes[i] }\OtherTok{\textless{}{-}}\NormalTok{ trials}
\NormalTok{  \}}
\NormalTok{  outcomes}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

When we use this function to draw a sample of \(n=10000\) geoemtrically
distributed random variables with \(p=0.2\), we obtain:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p }\OtherTok{\textless{}{-}}\NormalTok{ .}\DecValTok{2}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{10000}
\NormalTok{sample }\OtherTok{\textless{}{-}} \FunctionTok{rgeo}\NormalTok{(n,p)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"the mean should be approximate 1/p ="}\NormalTok{, }\DecValTok{1}\SpecialCharTok{/}\NormalTok{p, }\StringTok{" and we obtain a mean of "}\NormalTok{, }\FunctionTok{mean}\NormalTok{(sample))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## the mean should be approximate 1/p = 5  and we obtain a mean of  4.9891
\end{verbatim}

\hypertarget{problem-5}{%
\section{Problem 5}\label{problem-5}}

Generate random values from a Standard Half Normal distribution with
pdf, \[
f(x) = \frac{2}{\sqrt{2 \pi}} e^{-x^2/2} , x > 0.
\]

For the candidate pdf, choose the exponential density with rate \(1\).
Verify that your method works via a plot of the true density, and a
histogram of the generated values.

\hypertarget{solution-2}{%
\subsection{Solution}\label{solution-2}}

We are given the density of the standard half-normal distribution, \[
  \operatorname{dhalfnormal}(x) = \frac{2}{\sqrt{2 \pi}} e^{-x^2/2}, x > 0.
\]

We model this density with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# density for standard half{-}normal}
\NormalTok{dhalfnormal }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x) \{ }\DecValTok{2}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{pi)}\SpecialCharTok{*}\FunctionTok{exp}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{x}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{/}\DecValTok{2}\NormalTok{) \}}
\end{Highlighting}
\end{Shaded}

We sample from the exponential distribution
\(\operatorname{EXP}(\lambda=1)\), with density \(g\) and thus we first
find the \(c\) satisfying \[
  c = \max \left\{ \frac{\operatorname{dhalfnormal}(x)}{\operatorname{dexp}(x|\lambda=1)} | x \in \mathbb{R} \right\},
\] which is found to be approximately \(c = 1.315489247\).

We implement the standard half-normal sampler,
\(\operatorname{rhalfnormal}\), using the acceptance-rejection sampling
technique with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# accept{-}rejection sampling for standard half{-}normal}
\CommentTok{\# using exp(rate=1)}
\NormalTok{rhalfnormal }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(N)}
\NormalTok{\{}
\NormalTok{  c }\OtherTok{\textless{}{-}} \FloatTok{1.315489247}
\NormalTok{  xs }\OtherTok{\textless{}{-}} \FunctionTok{vector}\NormalTok{(}\AttributeTok{length=}\NormalTok{N)}
\NormalTok{  k }\OtherTok{\textless{}{-}} \DecValTok{1}
  \ControlFlowTok{while}\NormalTok{ (T)}
\NormalTok{  \{}
\NormalTok{    x }\OtherTok{\textless{}{-}} \FunctionTok{rexp}\NormalTok{(}\AttributeTok{n=}\DecValTok{1}\NormalTok{)}
    \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{runif}\NormalTok{(}\AttributeTok{n=}\DecValTok{1}\NormalTok{) }\SpecialCharTok{\textless{}} \FunctionTok{dhalfnormal}\NormalTok{(x)}\SpecialCharTok{/}\NormalTok{(c}\SpecialCharTok{*}\FunctionTok{dexp}\NormalTok{(x)))}
\NormalTok{    \{}
\NormalTok{      xs[k] }\OtherTok{\textless{}{-}}\NormalTok{ x}
\NormalTok{      k }\OtherTok{\textless{}{-}}\NormalTok{ k }\SpecialCharTok{+} \DecValTok{1}
      \ControlFlowTok{if}\NormalTok{ (k }\SpecialCharTok{==}\NormalTok{ N)}
\NormalTok{      \{}
        \ControlFlowTok{break}
\NormalTok{      \}}
\NormalTok{    \}}
\NormalTok{  \}}
\NormalTok{  xs}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

We simulate drawing \(n=100000\) samples from the standard half-normal
distribution and plotting a histogram of the sample with its density
overload in red on top of it with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{100000}
\NormalTok{sample }\OtherTok{\textless{}{-}} \FunctionTok{rhalfnormal}\NormalTok{(n)}
\FunctionTok{hist}\NormalTok{(sample,}\AttributeTok{freq=}\NormalTok{F,}\AttributeTok{breaks=}\DecValTok{50}\NormalTok{,}\AttributeTok{main=}\StringTok{"standard half{-}normal"}\NormalTok{)}
\FunctionTok{curve}\NormalTok{(}\FunctionTok{dhalfnormal}\NormalTok{(x),}\AttributeTok{add=}\ConstantTok{TRUE}\NormalTok{,}\AttributeTok{col=}\StringTok{"red"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1.mod_files/figure-latex/unnamed-chunk-19-1.pdf}

We see that the histogram is compatible with being drawn from the
overload density.

\hypertarget{problem-6}{%
\section{Problem 6}\label{problem-6}}

Use accept-reject to sample from this bimodal density: \[
  f(x) \propto 3 e^{-0.5(x+2)^2} + 7 e^{-0.5(x-2)^2}
\] The normalizing constant is \(25.066\). For your proposal \(g(·)\),
use a \(N(0, 2^2)\) distribution. Verify that your method works via a
plot of the true normalized density, and a histogram of the generated
values.

\hypertarget{solution-3}{%
\subsection{Solution}\label{solution-3}}

We are given the kernel of the bimodal distribution of interest, \[
  \operatorname{ker-bimodal}(x) = 3 e^{-0.5(x+2)^2} + 7 e^{-0.5(x-2)^2},
\] with the normalizing constant \(C = 25.0663\) and thus the pdf for
the bimodal is given by \[
  \operatorname{dbimodal}(x) = \frac{\operatorname{ker}(x)}{C}.
\]

We model these two functions with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# density for biomodal density}
\NormalTok{kerbimodal }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x) \{ }\DecValTok{3}\SpecialCharTok{*}\FunctionTok{exp}\NormalTok{(}\SpecialCharTok{{-}}\FloatTok{0.5}\SpecialCharTok{*}\NormalTok{(x}\SpecialCharTok{+}\DecValTok{2}\NormalTok{)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{) }\SpecialCharTok{+} \DecValTok{7}\SpecialCharTok{*}\FunctionTok{exp}\NormalTok{(}\SpecialCharTok{{-}}\FloatTok{0.5}\SpecialCharTok{*}\NormalTok{(x}\DecValTok{{-}2}\NormalTok{)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{) \}}
\NormalTok{kerbimodal.C }\OtherTok{\textless{}{-}} \FloatTok{25.0663}
\NormalTok{dbimodal }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x) \{ }\FunctionTok{kerbimodal}\NormalTok{(x) }\SpecialCharTok{/}\NormalTok{ kerbimodal.C \}}
\end{Highlighting}
\end{Shaded}

We sample from the normal distribution \(N(\mu=0,\sigma^2=2^2)\), with
density \(g\) and thus we first find the \(c\) satisfying \[
  c = \max \left\{ \frac{\operatorname{ker-bimodal}(x)}{g(x|\mu=0,\sigma^2=2^2)} | x \in \mathbb{R} \right\},
\] which is found to be approximately \(c = 68.35212\).

We implement the bimodal sampler, \(\operatorname{rbimodal}\), using the
acceptance-rejection sampling technique with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# accept{-}rejection sampling for bimodal distribution with density dbimodal}
\CommentTok{\# using normal(0,2\^{}2).}
\NormalTok{rbimodal }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(N)}
\NormalTok{\{}
\NormalTok{  c }\OtherTok{\textless{}{-}} \FloatTok{68.35212}
\NormalTok{  xs }\OtherTok{\textless{}{-}} \FunctionTok{vector}\NormalTok{(}\AttributeTok{length=}\NormalTok{N)}
\NormalTok{  k }\OtherTok{\textless{}{-}} \DecValTok{1}
  \ControlFlowTok{while}\NormalTok{ (T)}
\NormalTok{  \{}
\NormalTok{    x }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\AttributeTok{n=}\DecValTok{1}\NormalTok{,}\AttributeTok{mean=}\DecValTok{0}\NormalTok{,}\AttributeTok{sd=}\DecValTok{2}\NormalTok{)}
    \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{runif}\NormalTok{(}\AttributeTok{n=}\DecValTok{1}\NormalTok{) }\SpecialCharTok{\textless{}} \FunctionTok{kerbimodal}\NormalTok{(x)}\SpecialCharTok{/}\NormalTok{(c}\SpecialCharTok{*}\FunctionTok{dnorm}\NormalTok{(x,}\AttributeTok{mean=}\DecValTok{0}\NormalTok{,}\AttributeTok{sd=}\DecValTok{2}\NormalTok{)))}
\NormalTok{    \{}
\NormalTok{      xs[k] }\OtherTok{\textless{}{-}}\NormalTok{ x}
      \ControlFlowTok{if}\NormalTok{ (k }\SpecialCharTok{==}\NormalTok{ N)}
\NormalTok{      \{}
        \ControlFlowTok{break}
\NormalTok{      \}}
\NormalTok{      k }\OtherTok{\textless{}{-}}\NormalTok{ k }\SpecialCharTok{+} \DecValTok{1}
\NormalTok{    \}}
\NormalTok{  \}}
\NormalTok{  xs}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

We simulate drawing \(n=100000\) samples from the bimodal distribution
and plotting a histogram of the sample with its density overload in red
on top of it with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{100000}
\NormalTok{sample }\OtherTok{\textless{}{-}} \FunctionTok{rbimodal}\NormalTok{(n)}
\FunctionTok{hist}\NormalTok{(sample,}\AttributeTok{freq=}\NormalTok{F,}\AttributeTok{breaks=}\DecValTok{50}\NormalTok{,}\AttributeTok{main=}\StringTok{"bimodal"}\NormalTok{)}
\FunctionTok{curve}\NormalTok{(}\FunctionTok{dbimodal}\NormalTok{(x),}\AttributeTok{add=}\ConstantTok{TRUE}\NormalTok{,}\AttributeTok{col=}\StringTok{"red"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1.mod_files/figure-latex/unnamed-chunk-22-1.pdf}

We see that the histogram is compatible with being drawn from the
overload density.

\end{document}
