% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{amsmath}
\usepackage{mathtools}
\usepackage{amsthm}
\usepackage{multirow}
\usepackage{booktabs}
\usepackage{minted}
\usepackage{color}
\usepackage{xcolor}
\usepackage{tcolorbox}
\usepackage{enumerate}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Regression Analysis - STAT 482 - Probem Set 7},
  pdfauthor={Alex Towell (atowell@siue.edu)},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Regression Analysis - STAT 482 - Probem Set 7}
\author{Alex Towell
(\href{mailto:atowell@siue.edu}{\nolinkurl{atowell@siue.edu}})}
\date{}

\begin{document}
\maketitle

\newcommand{\sos}[1]{\mathrm{SS_{#1}}}
\newcommand{\ms}[1]{\mathrm{MS_{#1}}}
\newcommand{\sd}{\operatorname{sd}}
\newcommand{\var}{\operatorname{var}}
\newcommand{\expect}{\operatorname{E}}
\newcommand{\corr}{\operatorname{cor}}
\newcommand{\cov}{\operatorname{cov}}
\newcommand{\se}{\operatorname{se}}
\newcommand{\eval}[2]{\left. #1 \right\vert_{#2}}
\newcommand{\degf}[1]{\mathrm{df_{#1}}}
\newcommand{\entropy}{\operatorname{H}}

The goal is to study the relationship between patient satisfaction
(\(y\)) and patient's age (\(x_1\)), severity of illness (\(x_2\)), and
anxiety level (\(x_3\)). Refer to the data from Exercise 6.15.

\begin{tcolorbox}[split=\f]
Problem 1
\tcblower
Compute $t$ statistics for testing the effect of each input variable.
Explain what type of effect is being tested here.
\end{tcolorbox}

\hypertarget{computations}{%
\subsubsection{Computations}\label{computations}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{=} \FunctionTok{read.table}\NormalTok{(}\StringTok{\textquotesingle{}CH06PR15.txt\textquotesingle{}}\NormalTok{)}
\FunctionTok{names}\NormalTok{(data) }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"y"}\NormalTok{, }\StringTok{"x1"}\NormalTok{,}\StringTok{"x2"}\NormalTok{,}\StringTok{"x3"}\NormalTok{)}
\NormalTok{add.mod }\OtherTok{=} \FunctionTok{lm}\NormalTok{(y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x1 }\SpecialCharTok{+}\NormalTok{ x2 }\SpecialCharTok{+}\NormalTok{ x3, }\AttributeTok{data=}\NormalTok{data)}
\FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(add.mod))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                Estimate Std. Error    t value     Pr(>|t|)
## (Intercept) 158.4912517 18.1258887  8.7439162 5.260955e-11
## x1           -1.1416118  0.2147988 -5.3147960 3.810252e-06
## x2           -0.4420043  0.4919657 -0.8984452 3.740702e-01
## x3          -13.4701632  7.0996608 -1.8972967 6.467813e-02
\end{verbatim}

The \(t\) statistics are given by \begin{align*}
  t_1^* &= -5.315\\
  t_2^* &= -0.898\\
  t_3^* &= -1.897.
\end{align*}

\hypertarget{explanation}{%
\subsubsection{Explanation}\label{explanation}}

The statistic \(t_\ell^*\) is testing the partial effect of input
\(x_\ell\), accounting for the effects of all other inputs. (Recall that
in the additive model, \(\beta_\ell\) represents the \(\ell\)-th input
effect, with all other inputs held fixed.)

\begin{tcolorbox}[split=\f]
Problem 2
\tcblower
Compute the $F$ statistic for testing the multiple regression model against a no
effects model.
Explain what type of effect is being tested here.
\end{tcolorbox}

\hypertarget{computation}{%
\subsubsection{Computation}\label{computation}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{null.mod }\OtherTok{=} \FunctionTok{lm}\NormalTok{(y }\SpecialCharTok{\textasciitilde{}} \DecValTok{1}\NormalTok{, }\AttributeTok{data=}\NormalTok{data)}
\FunctionTok{anova}\NormalTok{(null.mod,add.mod)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Model 1: y ~ 1
## Model 2: y ~ x1 + x2 + x3
##   Res.Df     RSS Df Sum of Sq      F    Pr(>F)    
## 1     45 13369.3                                  
## 2     42  4248.8  3    9120.5 30.052 1.542e-10 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

We see that \(F^* = 30.052\).

\hypertarget{explanation-1}{%
\subsubsection{Explanation}\label{explanation-1}}

This is a test for the joint effect of \((x_1,x_2,x_3)\) on response
\(y\).

\begin{tcolorbox}[split=\f]
Probem 3
\tcblower
Compute the sequential sum of squares $\mathrm{SS_{R}}(X_1)$, $\mathrm{SS_{R}}(X_2|X_1)$, $\mathrm{SS_{R}}(X_3|X_1,X_2)$.
Explain what each sum of squares represents, stated in the context of the problem.
\end{tcolorbox}

\hypertarget{computation-1}{%
\subsubsection{Computation}\label{computation-1}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{anova}\NormalTok{(add.mod)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: y
##           Df Sum Sq Mean Sq F value    Pr(>F)    
## x1         1 8275.4  8275.4 81.8026 2.059e-11 ***
## x2         1  480.9   480.9  4.7539   0.03489 *  
## x3         1  364.2   364.2  3.5997   0.06468 .  
## Residuals 42 4248.8   101.2                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

We see that \begin{align*}
  \mathrm{SS_{R}}(X_1)         &= 8275.389,\\
  \mathrm{SS_{R}}(X_2|X_1)     &= 480.915,\\
  \mathrm{SS_{R}}(X_3|X_1,X_2) &= 364.160.
\end{align*}

\hypertarget{explanation-2}{%
\subsubsection{Explanation}\label{explanation-2}}

\(\mathrm{SS_{R}}(X_1)\) measures the variation in response
(satisfaction) explained by \(X_1\) (age), not accounting for
information on \(X_2\) (severity of illness) and \(X_3\) (anxiety
level); \(\mathrm{SS_{R}}(X_2|X_1)\) measures the variation in
satisfaction explained by \(X_2\) beyond that explained by \(X_1\) and
not accounting for information in \(X_3\); lastly,
\(\mathrm{SS_{R}}(X_3|X_1,X_2)\) measures the variation in satisfaction
explained by \(X_3\) beyond that explained by \(X_1\) and \(X_2\).

\hypertarget{additional-remarks}{%
\subsubsection{Additional remarks}\label{additional-remarks}}

Note that \[
  \mathrm{SS_{R}}(X_1,X_2,X_3) = \mathrm{SS_{R}}(X_1) + \mathrm{SS_{R}}(X_2|X_1) + \mathrm{SS_{R}}(X_3|X_1,X_2)
\] measures the variation in satisfaction explained by \(X_1\), \(X_2\),
and \(X_3\). The additive nature of \(\mathrm{SS_{R}}\) is reminiscent
of Shannon information \(\operatorname{H}\), where if \(X_1,X_2,X_3\)
are random variables, then \[
  \operatorname{H}(X_1,X_2,X_3) = \operatorname{H}(X_1) + \operatorname{H}(X_2|X_1) + \operatorname{H}(X_3|X_1,X_2).
\] If \(X_1\), \(X_2\), and \(X_3\) are independent, then
\(\operatorname{H}(X_1,X_2,X_3) = \operatorname{H}(X_1) + \operatorname{H}(X_2) + \operatorname{H}(X_3)\).
Likewise, if \(X_1\), \(X_2\), and \(X_3\) explain independent aspects
of the variation in the response, I speculate that
\(\mathrm{SS_{R}}(X_1,X_2,X_3) = \mathrm{SS_{R}}(X_1) + \mathrm{SS_{R}}(X_2) + \mathrm{SS_{R}}(X_3)\).
Unlike joint probabilities or relative likelihoods, which are
multiplicative, information (entropy) and \(\mathrm{SS_{R}}\) are
additive. This additive property of information is desirable since, for
instance, having \(k\) times as large of an i.i.d sample for, say,
estimating \(\theta\), should convey \(k\) times as much information
about \(\theta\) (i.e., less variance in an estimator of \(\theta\)
based on the information in such a sample).

That said, it is not clear to me how to fit \(\mathrm{SS_{R}}\) into
this conceptual framework, if indeed it would even be prudent to do so.

\begin{tcolorbox}[split=\f]
Problem 4
\tcblower
Consider testing for the effect of anxiety level on patient satisfaction.

\begin{enumerate}
  \item[(a)] Test for an effect of $X_3$ against a model which only includes
  $X_1$ (i.e., compute $F_{3|1}^*$ and its $p$-value).
  \item[(b)] Test for an effect of $X_3$ against a model which includes both
  $X_1$ and $X_2$ (i.e., compute $F_{3|1,2}^*$ and its $p$-value).
  \item[(c)] Explain the different motivations for the above tests, stated in
  the context of the problem.
\end{enumerate}
\end{tcolorbox}

\hypertarget{part-a}{%
\subsubsection{Part (a)}\label{part-a}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m1 }\OtherTok{=} \FunctionTok{lm}\NormalTok{(y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x1, }\AttributeTok{data=}\NormalTok{data)}
\NormalTok{m13 }\OtherTok{=} \FunctionTok{lm}\NormalTok{(y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x1}\SpecialCharTok{+}\NormalTok{x3, }\AttributeTok{data=}\NormalTok{data)}
\FunctionTok{anova}\NormalTok{(m1,m13)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Model 1: y ~ x1
## Model 2: y ~ x1 + x3
##   Res.Df    RSS Df Sum of Sq      F  Pr(>F)   
## 1     44 5093.9                               
## 2     43 4330.5  1    763.42 7.5804 0.00861 **
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

We see that \(F_{3|1}^* = 7.580 \; \text{($p$-value = $.009$)}\). When
we already have \(X_1\) in the model, adding \(X_3\) would be an
appropriate decision.

\hypertarget{part-b}{%
\subsubsection{Part (b)}\label{part-b}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m12 }\OtherTok{=} \FunctionTok{lm}\NormalTok{(y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x1}\SpecialCharTok{+}\NormalTok{x2, }\AttributeTok{data=}\NormalTok{data)}
\NormalTok{m123 }\OtherTok{=}\NormalTok{ add.mod}
\FunctionTok{anova}\NormalTok{(m12,m123)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Model 1: y ~ x1 + x2
## Model 2: y ~ x1 + x2 + x3
##   Res.Df    RSS Df Sum of Sq      F  Pr(>F)  
## 1     43 4613.0                              
## 2     42 4248.8  1    364.16 3.5997 0.06468 .
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

We see that \(F_{3|1,2}^* = 3.600 \; \text{($p$-value = $.065$)}\). When
we already include \(X_1\) and \(X_2\) in the model, the need for
\(X_3\) is not as great as before.

\hypertarget{part-c}{%
\subsubsection{Part (c)}\label{part-c}}

In part (a), we are testing for the effect of anxiety level on patient
satisfaction after accounting for the effect of patient age.

In part (b), we are testing for the effect of anxiety level on patient
satisfaction after accounting for both the effect of patient age and
severity of illness.

\end{document}
