---
title: "Lignite Converted"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data from Handout

In a study concerning coal conservation into oils, the hydrogenolysis of a Canadian lignite using carbon monoxide and hydrogen mixtures as reducing agents was investigated.

:


```{r}

#setwd("F:/Lexar/stat 482 data sets")
lignite.dat = read.csv('lignite.csv')
lignite.dat
cor(lignite.dat)

attach(lignite.dat)
lignite.mod = lm(conversion ~ temperature + molar.ratio + pressure + time)
summary(lignite.mod)
anova(lignite.mod)


x1 = 2*(temperature-mean(temperature))/ (range(temperature)[2]-range(temperature)[1])
x2 = 2*(molar.ratio-mean(molar.ratio))/ (range(molar.ratio)[2]-range(molar.ratio)[1])
x3 = 2*(pressure-mean(pressure))/ (range(pressure)[2]-range(pressure)[1])
x4 = 2*(time-mean(time))/ (range(time)[2]-range(time)[1])

cbind(x1,x2,x3,x4)

orthog.mod = lm(conversion ~ x1+x2+x3+x4)
summary(orthog.mod)

accepted.mod = lm(conversion ~ x1+x2+x3)
summary(accepted.mod)

```


