% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  11pt,
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage[]{mathpazo}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{alex}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Discrete Multivariate Analysis - 579 - Final Exam},
  pdfauthor={Alex Towell (atowell@siue.edu)},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Discrete Multivariate Analysis - 579 - Final Exam}
\author{Alex Towell
(\href{mailto:atowell@siue.edu}{\nolinkurl{atowell@siue.edu}})}
\date{}

\begin{document}
\maketitle

\hypertarget{part-1}{%
\section{Part 1}\label{part-1}}

A sample of elderly patients were given a psychiatric examination to
determine whether symptoms of senility are present. One explanatory
variable is a patient's score on the Wechsler Adult Intelligence Scale
(WAIS).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{wais.data }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{wais=}\FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{5}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{7}\NormalTok{,}\DecValTok{8}\NormalTok{,}\DecValTok{9}\NormalTok{,}\DecValTok{10}\NormalTok{,}\DecValTok{11}\NormalTok{,}\DecValTok{12}\NormalTok{,}\DecValTok{13}\NormalTok{,}\DecValTok{14}\NormalTok{,}\DecValTok{15}\NormalTok{,}\DecValTok{16}\NormalTok{,}\DecValTok{17}\NormalTok{,}\DecValTok{18}\NormalTok{),}
  \AttributeTok{n=}\FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{7}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{),}
  \AttributeTok{senile=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{))}

\FunctionTok{print}\NormalTok{(wais.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    wais n senile
## 1     4 2      1
## 2     5 1      1
## 3     6 2      1
## 4     7 3      2
## 5     8 2      2
## 6     9 6      2
## 7    10 6      2
## 8    11 6      1
## 9    12 2      0
## 10   13 6      1
## 11   14 7      2
## 12   15 3      0
## 13   16 4      0
## 14   17 1      0
## 15   18 1      0
\end{verbatim}

\hypertarget{problem-1}{%
\subsection{Problem 1}\label{problem-1}}

\fbox{\begin{minipage}{.9\textwidth}
Define the logistic regression model, including notation for the input matrix
$X$, the response vector $y$, the parameter vector $\beta$, and the
probability vector $\pi(\beta)$.
\end{minipage}}

The data is \((\v{x_1},y_1),(\v{x_2},y_2),\ldots,(\v{x_n},y_n)\) where
\(\v{x_j}\) is a column vector of explanatory variables and \(y_j\) is a
binary variable.

The probability model is given by \[
  y_i \sim \operatorname{BIN}(1,\pi(\v{x_i})).
\] That is, \(\pi(\v{x})\) models probability as a function of
\(\v{x}\).

The logistic regression model is given by \[
  \log \left(\frac{\pi(\v{x_i})}{1-\pi(\v{x_i})}\right) = \v{x_i}' \v{\beta},
\] such that if we solve for \(\pi(\v{x_i})\) we get the result \[
  \pi(\v{x_i}) = \frac{\exp(\v{x_i}' \v{\beta})}{1+\exp(\v{x_i}' \v{\beta})}
\] where \(\v{x_i}'\) denotes the transpose of \(\v{x_i}\).

The response vector \(\v{y}\) of dimension \(n \times 1\) is given by \[
\v{y} =
\begin{pmatrix}
  y_1\\
  y_2\\
  \vdots\\
  y_n
\end{pmatrix}.
\]

The input (design) martix \(\mat{X}\) of dimension \(n \times (p+1)\) is
given by \[
\mat{X} =
\begin{pmatrix}
  \v{x_1}'\\
  \v{x_2}'\\
  \vdots\\
  \v{x_n}'
\end{pmatrix}
=
\begin{pmatrix}
  1 & x_{1 1} & \cdots & x_{1 p}\\
  1 & x_{2 1} & \cdots & x_{2 p}\\
  \vdots  & \vdots & \ddots & \vdots\\
  1 & x_{n 1} & \cdots & x_{n p}
\end{pmatrix}.
\]

The parameter vector \(\v{\beta}\) of dimension \((p+1) \times 1\) is
given by \[
\v{\beta} =
\begin{pmatrix}
  \beta_0\\
  \beta_1\\
  \beta_2\\
  \vdots\\
  \beta_p
\end{pmatrix}
\] where \(\beta_0\) denotes the \emph{intercept} in the linear
predictor.

The probability vector \[
\v{\pi}(\v{\beta}) =
\begin{pmatrix}
  \pi(\v{x_1})\\
  \pi(\v{x_2})\\
  \vdots\\
  \pi(\v{x_n})\\
\end{pmatrix}
\] where \(\v{x_j}\) are the explanatory varibles as described
previously.

\hypertarget{problem-2}{%
\subsection{Problem 2}\label{problem-2}}

\hypertarget{part-a}{%
\subsubsection{Part (a)}\label{part-a}}

\fbox{\begin{minipage}{.9\textwidth}
State the likelihood equation for the MLE $\v{\hat{\beta}}$ as a normal equation.
\end{minipage}}

The normal equations for \(\hat{\v{\beta}}\) are given by \[
  \mat{X}'(\v{y} - \v{\pi}(\hat{\v{\beta}})) = \v{0}.
\]

\hypertarget{part-b}{%
\subsubsection{Part (b)}\label{part-b}}

\fbox{\begin{minipage}{.9\textwidth}
State the equation for $\hat{V} = \hat{\cov}(\hat{\beta})$, the estimated
variance matrix for $\hat{\beta}$.
\end{minipage}}

The equation for \(\hat{\mat{V}}\) is given by \[
  \hat{\mat{V}} = \hat{\operatorname{\mat{cov}}}(\v{\hat{\beta}}) = (\mat{X}' \hat{\mat{W}} \mat{X})^{-1},
\] which is a \((p+1) \times (p+1)\) covariance matrix (estimate) and
\(\hat{\mat{W}} = \operatorname{\mat{diag}}(\pi_i(1-\pi_i))\) is an
\(n \times n\) diagonal matrix.

\hypertarget{part-c}{%
\subsubsection{Part (c)}\label{part-c}}

\fbox{\begin{minipage}{.9\textwidth}
Compute $\hat{\beta}$ and $\hat{V}$ from the WAIS data.
\end{minipage}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{wais.mod }\OtherTok{=} \FunctionTok{glm}\NormalTok{(senile}\SpecialCharTok{/}\NormalTok{n }\SpecialCharTok{\textasciitilde{}}\NormalTok{ wais,}\AttributeTok{weights=}\NormalTok{n, }\AttributeTok{family=}\NormalTok{binomial, }\AttributeTok{data=}\NormalTok{wais.data)}

\CommentTok{\# define the intercept and slope parameter estimates}
\CommentTok{\# alpha}
\NormalTok{a }\OtherTok{=}\NormalTok{ wais.mod}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{1}\NormalTok{]}
\CommentTok{\# beta}
\NormalTok{b }\OtherTok{=}\NormalTok{ wais.mod}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{2}\NormalTok{] }

\CommentTok{\# this is beta = (a,b)\textquotesingle{}}
\FunctionTok{print}\NormalTok{(}\FunctionTok{c}\NormalTok{(a,b))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)        wais 
##   2.4810957  -0.3189723
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# compute the variance/covariance matrix for parameter estimates}
\NormalTok{V.hat }\OtherTok{=} \FunctionTok{vcov}\NormalTok{(wais.mod)}
\FunctionTok{print}\NormalTok{(V.hat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             (Intercept)        wais
## (Intercept)   1.4447178 -0.13154006
## wais         -0.1315401  0.01301779
\end{verbatim}

We see that \(\hat{\v{\beta}} = (2.481, -0.319)'\) and \[
  \hat{\mat{V}} =
  \begin{pmatrix}
    1.445 & -0.132\\
    -0.132 & 0.013
  \end{pmatrix}.
\]

\hypertarget{problem-3}{%
\subsection{Problem 3}\label{problem-3}}

\hypertarget{part-a-1}{%
\subsubsection{Part (a)}\label{part-a-1}}

\fbox{\begin{minipage}{.9\textwidth}
State the equation for a 95\% confidence interval for $\beta_j$.
\end{minipage}}

A \(95\%\) confidence interval for \(\beta_j\) is
\(\hat{\beta}_j \pm 1.96 \sqrt{\hat{V}_{j j}}\), where \(\hat{V}_{j j}\)
is the \(j\)-th element along the diagonal of \(\hat{\mat{V}}\).

\hypertarget{part-b-1}{%
\subsubsection{Part (b)}\label{part-b-1}}

\fbox{\begin{minipage}{.9\textwidth}
Compute a 95\% confidence interval for $\beta_1$ from the WAIS data, and provide
an interpretation in the context of the problem.
\end{minipage}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# compute the s.e. for beta.hat from the estimated variance/covariance matrix}
\NormalTok{se.b }\OtherTok{=} \FunctionTok{sqrt}\NormalTok{(V.hat[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{])}

\CommentTok{\# compute a 95\% confidence interval estimate for beta}
\NormalTok{L.beta }\OtherTok{=}\NormalTok{ b }\SpecialCharTok{{-}} \FloatTok{1.96}\SpecialCharTok{*}\NormalTok{se.b}
\NormalTok{U.beta }\OtherTok{=}\NormalTok{ b }\SpecialCharTok{+} \FloatTok{1.96}\SpecialCharTok{*}\NormalTok{se.b}
\FunctionTok{print}\NormalTok{(b)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       wais 
## -0.3189723
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{c}\NormalTok{(L.beta,U.beta))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       wais       wais 
## -0.5425995 -0.0953451
\end{verbatim}

We estimate that \(\beta_1\) is between \(-0.543\) and \(-0.095\).

Note that \(\beta_1\) can generally be thought of as an effect size for
the association between WAIS and senility, in particular the change in
the log odds with respect to a a change in the input level of WAIS.

We estimate that the log-odds of senility \emph{decreases} by \(0.319\)
units from a unit \emph{increase} in the WAIS measure, which makes
sense.

\hypertarget{problem-4}{%
\subsection{Problem 4}\label{problem-4}}

\hypertarget{part-a-2}{%
\subsubsection{Part (a)}\label{part-a-2}}

\fbox{\begin{minipage}{.9\textwidth}
State the equations for a 95\% confidence interval for odds ratio $\theta$.
\end{minipage}}

The \emph{odds} at \(\v{x}\) are given by \[
  \Omega(\v{x}) = \frac{\pi(\v{x})}{1-\pi(\v{x})} = \exp(\v{x}' \v{\beta}).
\]

Then, \[
  \log \Omega(\v{x}) = \log \left(\frac{\pi(\v{x})}{1-\pi(\v{x})}\right) = \v{x}' \v{\beta}.
\]

Let \(\v{u_j}\) be defined as a unit vector of dimension \(p+1\) such
that every element except the \(j\)-th element is zero.

Then \begin{align*}
  \beta_j &= \log \Omega(\v{x}+\v{u_j}) - \log \Omega(\v{x})\\
          &= \log \frac{\Omega(\v{x}+\v{u_j})}{\Omega(\v{x})},
\end{align*} which is the log odds ratio for comparing inputs \(\v{x}\)
and \(\v{x} + \v{u_j}\). So, \(\exp(\beta_j)\) is the odds ratio
\(\theta_j\) for comparing inputs \(\v{x}\) and \(\v{x} + \v{u_j}\).

\hypertarget{simple-logistic-regression}{%
\subsubsection{Simple logistic
regression}\label{simple-logistic-regression}}

Since \(p=2\), we only have one explanatory variable \(x\) and thus we
may rephrase this as \(\beta_1\) is the log odds ratio for comparing
input levels \(x\) and \(x+1\) and therefore \(\exp(\beta_1)\) is the
odds ratio \(\theta\) for comparing input levels \(x\) and \(x+1\).

A \(95\%\) confidence interval for \(\theta\) is given by \[
  \left[\exp(l_{\beta_1}),\exp(u_{\beta_1})\right]
\] where \(l_{\beta_1} = \hat{\beta}_1 - 1.96 \sqrt{\hat{V}_{1 1}}\) and
\(u_{\beta_1} = \hat{\beta}_1 + 1.96 \sqrt{\hat{V}_{1 1}}\).

Note that we use zero-based indexing, i.e., the first element in the
matrix is at index \((0,0)\) instead of \((1,1)\).

\hypertarget{part-b-2}{%
\subsubsection{Part (b)}\label{part-b-2}}

\fbox{\begin{minipage}{.9\textwidth}
Compute a 95\% confidence interval for $\theta$ from the WAIS data.
\end{minipage}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# compute an estimate of the odds ratio}
\NormalTok{theta }\OtherTok{\textless{}{-}} \FunctionTok{exp}\NormalTok{(b)}

\CommentTok{\# compute a 95\% confidence interval estimate for the odds ratio}
\NormalTok{L.theta }\OtherTok{=} \FunctionTok{exp}\NormalTok{(L.beta)}
\NormalTok{U.theta }\OtherTok{=} \FunctionTok{exp}\NormalTok{(U.beta)}

\CommentTok{\# print confidence interval}
\FunctionTok{print}\NormalTok{(}\FunctionTok{c}\NormalTok{(L.theta,U.theta))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      wais      wais 
## 0.5812354 0.9090592
\end{verbatim}

Since the log-odds is given by \(\beta_1\), the odds \(\theta\) is given
by \(\exp(\beta_1)\) with a point estimate
\(\hat{\theta} = \exp(\hat{\beta}_1)\) given by \[
  0.727.
\] From the R computation, we see that a \(95\%\) confidence interval
for \(\theta\) is given by \[
  (0.581, 0.909),
\] which is not symmetric around the point estimate.

\hypertarget{problem-5}{%
\subsection{Problem 5}\label{problem-5}}

\hypertarget{part-a-3}{%
\subsubsection{Part (a)}\label{part-a-3}}

\fbox{\begin{minipage}{.9\textwidth}
State the equations for a 95\% confidence interval for the logit $L_o$ at input level $x_o$:
\end{minipage}}

We estimate the logit with \[
  \hat{L}_o = \v{x}_o' \v{\hat{\beta}}
\] which has a variance \[
  \var(\hat{L}_o) = \v{x}_o' \mat{V} \v{x}_o
\] where \(\mat{V} = \mat{\cov}(\hat{\v{\beta}})\).

We do not know \(\mat{V}\), so we estimate \(\sigma_{\hat{L}_o}\) with
\[
  \hat{\sigma}(\hat{L}_o) = \sqrt{\v{x}_o' \hat{\mat{V}} \v{x}_o}.
\]

Thus, a \(95\%\) confidence interval for \(L_o\) is given by \[
  \hat{L}_o \pm 1.96 \hat{\sigma}(\hat{L}_o).
\]

\hypertarget{simple-logistic-regression-1}{%
\paragraph{Simple logistic
regression}\label{simple-logistic-regression-1}}

Since this is simple logistic regression with \(p=1\) explanatory
variables, we may simplify the presentation.

Let \(\v{x}_o' = (1,x_o)\). Then, these equations simplify to \[
  \hat{L}_o = \hat{\beta_0} + \hat{\beta_1} x_o,
\] and \[
  \var(\hat{L}_o) = \var(\hat{\beta_0}) +
    x_o^2 \var(\hat{\beta_1}) + 2x_0 \cov(\hat{\beta_1},\hat{\beta_1}).
\]

\begin{align*}
  \sigma_{\hat{L}_o}^2
    &= \hat{V}_{0 0} + x_o^2 \hat{V}_{1 1} + 2x_o \hat{V}_{0 1}.
\end{align*}

\begin{align*}
  \hat{\sigma}(\hat{L}_o)
    &= \sqrt{\var(\hat\beta_0) + x_o^2 \var() + 2x_o \hat{V}_{0 1}}\\
    &= \sqrt{\hat{V}_{0 0} + x_o^2 \hat{V}_{1 1} + 2x_o \hat{V}_{0 1}}.
\end{align*}

A \(95\%\) CI for \(L_o\) is given by \[
  (1,x_o)^t \beta \pm 1.96 \sqrt{(1,x_o) \hat{V} (1,x_o)^t}.
\]

\hypertarget{part-b-3}{%
\subsubsection{Part (b)}\label{part-b-3}}

\fbox{\begin{minipage}{.9\textwidth}
Compute a 95\% confidence interval for $L_o$ at input level $x_o = 10$ from the WAIS data.
\end{minipage}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{xo }\OtherTok{\textless{}{-}} \DecValTok{10}
\NormalTok{L.hat }\OtherTok{\textless{}{-}}\NormalTok{ a }\SpecialCharTok{+}\NormalTok{ b}\SpecialCharTok{*}\NormalTok{xo }\CommentTok{\# should agree with L0.hat below}

\NormalTok{x0 }\OtherTok{=} \FunctionTok{as.matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,xo))}
\FunctionTok{print}\NormalTok{(x0)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1]
## [1,]    1
## [2,]   10
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{beta.hat }\OtherTok{=} \FunctionTok{as.matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(a,b))}

\NormalTok{L0.hat }\OtherTok{=} \FunctionTok{t}\NormalTok{(x0) }\SpecialCharTok{\%*\%}\NormalTok{ beta.hat}
\NormalTok{se0 }\OtherTok{=} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{t}\NormalTok{(x0)}\SpecialCharTok{\%*\%}\NormalTok{V.hat}\SpecialCharTok{\%*\%}\NormalTok{x0)}
\FunctionTok{print}\NormalTok{(}\FunctionTok{c}\NormalTok{(L0.hat,se0))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.7086274  0.3401400
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{L.L0 }\OtherTok{=}\NormalTok{ L0.hat }\SpecialCharTok{{-}} \FloatTok{1.96}\SpecialCharTok{*}\NormalTok{se0}
\NormalTok{U.L0 }\OtherTok{=}\NormalTok{ L0.hat }\SpecialCharTok{+} \FloatTok{1.96}\SpecialCharTok{*}\NormalTok{se0}
\FunctionTok{print}\NormalTok{(}\FunctionTok{c}\NormalTok{(L.L0,U.L0))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -1.37530182 -0.04195301
\end{verbatim}

\hypertarget{problem-6}{%
\subsection{Problem 6}\label{problem-6}}

\hypertarget{part-a-4}{%
\subsubsection{Part (a)}\label{part-a-4}}

\fbox{\begin{minipage}{.9\textwidth}
State the equations for a 95\% confidence interval for the probability $\pi_o$ at
input level $x_o$.
\end{minipage}}

\hypertarget{part-b-4}{%
\subsubsection{Part (b)}\label{part-b-4}}

\fbox{\begin{minipage}{.9\textwidth}
Compute a 95\% confidence interval for $\pi_o$ at input level $x_o = 10$ from the
WAIS data, and provide an interpretation in the context of the problem.
\end{minipage}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pi.hat }\OtherTok{\textless{}{-}} \FunctionTok{exp}\NormalTok{(L.hat) }\SpecialCharTok{/}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{+}\FunctionTok{exp}\NormalTok{(L.hat))}
\CommentTok{\#print(pi.hat)}
\FunctionTok{print}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\FunctionTok{exp}\NormalTok{(L.L0) }\SpecialCharTok{/}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{+}\FunctionTok{exp}\NormalTok{(L.L0)),}\FunctionTok{exp}\NormalTok{(U.L0) }\SpecialCharTok{/}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{+}\FunctionTok{exp}\NormalTok{(U.L0))))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.2017646 0.4895133
\end{verbatim}

\hypertarget{part-2}{%
\section{Part 2}\label{part-2}}

Applicants for graduate school are classified according to department,
sex, and admission status. A goal of the study is to determine the role
an applicant's sex plays in the determination of admission status.

\hypertarget{problem-1-1}{%
\subsection{Problem 1}\label{problem-1-1}}

\fbox{\begin{minipage}{.9\textwidth}
Define a main effects logistic regression model $M$ having two binary input
variables.
Include notation for the design matrix $X$, and the parameter vector $\beta$.
Provide an interpretation for each of the effect parameters in $\beta$, stated
in the context of the problem.
\end{minipage}}

\(\operatorname{logit}(\pi)(x_1,x_2) = \beta_0 + \beta_1 x_1 + \beta_2 x_2\).

\[
\mat{X} = 
\begin{pmatrix}
  1 & x_{1 1} & x_{1 2}\\
  1 & x_{2 1} & x_{2 2}\\
  \vdots &\vdots & \vdots
  1 & x_{n 1} & x_{n 2}\\
\end{pmatrix}
\]

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# department and sex are defined through indicator variables}
\NormalTok{grad.data }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{dep=}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{),}
                        \AttributeTok{sex=}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{),}
                        \AttributeTok{yes=}\FunctionTok{c}\NormalTok{(}\DecValTok{235}\NormalTok{,}\DecValTok{38}\NormalTok{,}\DecValTok{122}\NormalTok{,}\DecValTok{103}\NormalTok{),}
                        \AttributeTok{no=}\FunctionTok{c}\NormalTok{(}\DecValTok{35}\NormalTok{,}\DecValTok{7}\NormalTok{,}\DecValTok{93}\NormalTok{,}\DecValTok{69}\NormalTok{))}

\CommentTok{\# define row sample sizes}
\NormalTok{grad.data}\SpecialCharTok{$}\NormalTok{n }\OtherTok{=}\NormalTok{ grad.data}\SpecialCharTok{$}\NormalTok{yes }\SpecialCharTok{+}\NormalTok{ grad.data}\SpecialCharTok{$}\NormalTok{no}

\CommentTok{\# define the interaction variable}
\NormalTok{grad.data}\SpecialCharTok{$}\NormalTok{dep.sex }\OtherTok{=}\NormalTok{ grad.data}\SpecialCharTok{$}\NormalTok{dep }\SpecialCharTok{*}\NormalTok{ grad.data}\SpecialCharTok{$}\NormalTok{sex}

\FunctionTok{print}\NormalTok{(grad.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   dep sex yes no   n dep.sex
## 1   0   0 235 35 270       0
## 2   0   1  38  7  45       0
## 3   1   0 122 93 215       0
## 4   1   1 103 69 172       1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#fit each of the candidate models}
\NormalTok{m.s }\OtherTok{=} \FunctionTok{glm}\NormalTok{(yes}\SpecialCharTok{/}\NormalTok{n }\SpecialCharTok{\textasciitilde{}}\NormalTok{ sex}\SpecialCharTok{+}\NormalTok{dep}\SpecialCharTok{+}\NormalTok{sex}\SpecialCharTok{*}\NormalTok{dep,}\AttributeTok{weights=}\NormalTok{n,}\AttributeTok{family=}\NormalTok{binomial,}\AttributeTok{data=}\NormalTok{grad.data)}
\NormalTok{m}\FloatTok{.12} \OtherTok{=} \FunctionTok{glm}\NormalTok{(yes}\SpecialCharTok{/}\NormalTok{n }\SpecialCharTok{\textasciitilde{}}\NormalTok{ sex}\SpecialCharTok{+}\NormalTok{dep,}\AttributeTok{weights=}\NormalTok{n,}\AttributeTok{family=}\NormalTok{binomial,}\AttributeTok{data=}\NormalTok{grad.data)}
\NormalTok{m}\FloatTok{.1} \OtherTok{=} \FunctionTok{glm}\NormalTok{(yes}\SpecialCharTok{/}\NormalTok{n }\SpecialCharTok{\textasciitilde{}}\NormalTok{ sex,}\AttributeTok{weights=}\NormalTok{n,}\AttributeTok{family=}\NormalTok{binomial,}\AttributeTok{data=}\NormalTok{grad.data)}
\NormalTok{m}\FloatTok{.2} \OtherTok{=} \FunctionTok{glm}\NormalTok{(yes}\SpecialCharTok{/}\NormalTok{n }\SpecialCharTok{\textasciitilde{}}\NormalTok{ dep,}\AttributeTok{weights=}\NormalTok{n,}\AttributeTok{family=}\NormalTok{binomial,}\AttributeTok{data=}\NormalTok{grad.data)}
\NormalTok{m}\FloatTok{.0} \OtherTok{=} \FunctionTok{glm}\NormalTok{(yes}\SpecialCharTok{/}\NormalTok{n }\SpecialCharTok{\textasciitilde{}} \DecValTok{1}\NormalTok{,}\AttributeTok{weights=}\NormalTok{n,}\AttributeTok{family=}\NormalTok{binomial,}\AttributeTok{data=}\NormalTok{grad.data)}



\CommentTok{\#compute probability estimates under each of the candidate models}
\NormalTok{pred.S }\OtherTok{=} \FunctionTok{predict}\NormalTok{(m.s,}\AttributeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{pred}\FloatTok{.12} \OtherTok{=} \FunctionTok{predict}\NormalTok{(m}\FloatTok{.12}\NormalTok{,}\AttributeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{pred}\FloatTok{.1} \OtherTok{=} \FunctionTok{predict}\NormalTok{(m}\FloatTok{.1}\NormalTok{,}\AttributeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{pred}\FloatTok{.2} \OtherTok{=} \FunctionTok{predict}\NormalTok{(m}\FloatTok{.2}\NormalTok{,}\AttributeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{pred}\FloatTok{.0} \OtherTok{=} \FunctionTok{predict}\NormalTok{(m}\FloatTok{.0}\NormalTok{,}\AttributeTok{type =} \StringTok{"response"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{problem-2-1}{%
\subsection{Problem 2}\label{problem-2-1}}

\fbox{\begin{minipage}{.9\textwidth}
Provide notation for the design matrix $X_S$ and parameter vector $\beta_S$
for the saturated model $M_S$.
Provide a brief description of an interaction effect.
\end{minipage}}

\hypertarget{problem-3-1}{%
\subsection{Problem 3}\label{problem-3-1}}

\fbox{\begin{minipage}{.9\textwidth}
For each of the models $M_O$, $M_1$, $M_2$, provide notation for the design
matrix and a brief description of the model effects, stated in the context of
the problem.
\end{minipage}}

\hypertarget{problem-4-1}{%
\subsection{Problem 4}\label{problem-4-1}}

\fbox{\begin{minipage}{.9\textwidth}
Compute the deviance statistic $D$, and give degrees of freedom $\delta df$, for
each of the models $M_O,M_1,M_2,M,M_S$ from the grad school data.
Provide a general form for the statistic $G^2$, and the degrees of freedom for
the reference chi-square distribution, for testing a reduced model $M_R$ against
a full model $M_F$.
\end{minipage}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# create a table for candidate model deviances}
\CommentTok{\# the rows represent the model, the deviance, and the degrees of freedom}
\NormalTok{deviance.table}\OtherTok{=}\FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}
  \DecValTok{0}\NormalTok{,m}\FloatTok{.12}\SpecialCharTok{$}\NormalTok{deviance,m}\FloatTok{.1}\SpecialCharTok{$}\NormalTok{deviance,m}\FloatTok{.2}\SpecialCharTok{$}\NormalTok{deviance,m}\FloatTok{.0}\SpecialCharTok{$}\NormalTok{deviance,}
  \DecValTok{0}\NormalTok{,m}\FloatTok{.12}\SpecialCharTok{$}\NormalTok{df.residual,m}\FloatTok{.1}\SpecialCharTok{$}\NormalTok{df.residual,m}\FloatTok{.2}\SpecialCharTok{$}\NormalTok{df.residual,m}\FloatTok{.0}\SpecialCharTok{$}\NormalTok{df.residual),}
  \AttributeTok{nrow=}\DecValTok{5}\NormalTok{)}
\FunctionTok{dimnames}\NormalTok{(deviance.table) }\OtherTok{=} \FunctionTok{list}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"MS"}\NormalTok{,}\StringTok{"M"}\NormalTok{,}\StringTok{"M1"}\NormalTok{,}\StringTok{"M2"}\NormalTok{,}\StringTok{"MO"}\NormalTok{),}\FunctionTok{c}\NormalTok{(}\StringTok{"deviance"}\NormalTok{,}\StringTok{"delta.df"}\NormalTok{))}
\FunctionTok{print}\NormalTok{(deviance.table)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      deviance delta.df
## MS  0.0000000        0
## M   0.4589638        1
## M1 67.8794451        2
## M2  0.6036551        2
## MO 73.1962870        3
\end{verbatim}

First, \(G^2(M\,|\,M_S) = D(M)\) is called the deviance of \(M\).

The likelihood ratio statistic \(G^2\) for testing a reduced model
\(M_R\) against a full model \(M_F\) is given by \begin{align}
  G^2(M_R\,|\,M_S)
    &= [-2 L_R]-[-2 L_F]\\
    &= \left([-2 L_R]-[-2 L_S]\right)-\left([-2 L_F]-[-2 L_S] \right)\\
    &= G^2(M_R\,|\,M_S)-G^2(M_F\,|\,M_S)\\
    &= D(M_R) - D(M_F).
\end{align}

The \(df\) is given by
\(df = P_F - P_R = (P_S - P_R) - (P_S - P_F) = \Delta df_R - \Delta df_F\),
and so the reference distribution if \(\chi^2\) with
\(df = \Delta df_R - \Delta df_F\) degrees of freedom.

\hypertarget{problem-5-1}{%
\subsection{Problem 5}\label{problem-5-1}}

\fbox{\begin{minipage}{.9\textwidth}
Compute the likelihood statistic $G^2$ for testing reduced model $M$ against
full model $M_S$ from the grad school data, and provide an interpretation in the
context of the problem.
\end{minipage}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# test the main effects model against the interaction (saturated) model}
\FunctionTok{anova}\NormalTok{(m}\FloatTok{.12}\NormalTok{,m.s,}\AttributeTok{test =} \StringTok{"LRT"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Deviance Table
## 
## Model 1: yes/n ~ sex + dep
## Model 2: yes/n ~ sex + dep + sex * dep
##   Resid. Df Resid. Dev Df Deviance Pr(>Chi)
## 1         1    0.45896                     
## 2         0    0.00000  1  0.45896   0.4981
\end{verbatim}

The statistic \(G^2(M\,|\,M_S) = 0.459\) which has a \(p\)-value of
\(0.498\). Thus, we conlcude the main effect model (no interaction on
inputs) is compatible with the observed data.

\hypertarget{problem-6-1}{%
\subsection{Problem 6}\label{problem-6-1}}

\fbox{\begin{minipage}{.9\textwidth}
Compute the likelihood statistic $G^2$ for testing reduced model $M_O$ against
full model $M_2$ from the grad school data, and provide an interpretation in the
context of the problem.
\end{minipage}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# test for the input 2 effect, first using a marginal effect test,}
\CommentTok{\# then using a partial effect test}
\FunctionTok{anova}\NormalTok{(m}\FloatTok{.0}\NormalTok{,m}\FloatTok{.2}\NormalTok{,}\AttributeTok{test =} \StringTok{"LRT"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Deviance Table
## 
## Model 1: yes/n ~ 1
## Model 2: yes/n ~ dep
##   Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    
## 1         3     73.196                          
## 2         2      0.604  1   72.593 < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{anova}\NormalTok{(m}\FloatTok{.1}\NormalTok{,m}\FloatTok{.12}\NormalTok{,}\AttributeTok{test =} \StringTok{"LRT"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Deviance Table
## 
## Model 1: yes/n ~ sex
## Model 2: yes/n ~ sex + dep
##   Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    
## 1         2     67.879                          
## 2         1      0.459  1    67.42 < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\hypertarget{problem-7}{%
\subsection{Problem 7}\label{problem-7}}

\fbox{\begin{minipage}{.9\textwidth}
Compute the likelihood statistic $G_2$ for testing reduced model $M_1$ against
full model $M$ from the grad school data, and provide an interpretation in the
context of the problem.
Include an explanation of how this test differs from that of the previous
problem.
\end{minipage}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#test the independence model against the main effects model}
\FunctionTok{anova}\NormalTok{(m}\FloatTok{.0}\NormalTok{,m}\FloatTok{.12}\NormalTok{,}\AttributeTok{test =} \StringTok{"LRT"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Deviance Table
## 
## Model 1: yes/n ~ 1
## Model 2: yes/n ~ sex + dep
##   Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    
## 1         3     73.196                          
## 2         1      0.459  2   72.737 < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#test for the input 1 effect, first using a marginal effect test, then using a partial effect test}
\FunctionTok{anova}\NormalTok{(m}\FloatTok{.0}\NormalTok{,m}\FloatTok{.1}\NormalTok{,}\AttributeTok{test =} \StringTok{"LRT"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Deviance Table
## 
## Model 1: yes/n ~ 1
## Model 2: yes/n ~ sex
##   Resid. Df Resid. Dev Df Deviance Pr(>Chi)  
## 1         3     73.196                       
## 2         2     67.879  1   5.3168  0.02112 *
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{anova}\NormalTok{(m}\FloatTok{.2}\NormalTok{,m}\FloatTok{.12}\NormalTok{,}\AttributeTok{test =} \StringTok{"LRT"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Deviance Table
## 
## Model 1: yes/n ~ dep
## Model 2: yes/n ~ sex + dep
##   Resid. Df Resid. Dev Df Deviance Pr(>Chi)
## 1         2    0.60366                     
## 2         1    0.45896  1  0.14469   0.7037
\end{verbatim}

\hypertarget{problem-8}{%
\subsection{Problem 8}\label{problem-8}}

\fbox{\begin{minipage}{.9\textwidth}
Compute estimates of the response probabilities based on model $M_1$ from the
grad school data, and provide an interpretation in the context of the problem.
\end{minipage}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#create a display a table for the probability estimates}
\NormalTok{prob.table }\OtherTok{=} \FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(pred.S,pred}\FloatTok{.12}\NormalTok{,pred}\FloatTok{.1}\NormalTok{,pred}\FloatTok{.2}\NormalTok{,pred}\FloatTok{.0}\NormalTok{),}\AttributeTok{nrow =} \DecValTok{4}\NormalTok{)}
\CommentTok{\#dimnames(prob.table) = list(c("female low","female high","male low","male high"),}
\CommentTok{\#                            c("prob.S","prob.12","prob.1","prob.2","prob.0"))}
                
\FunctionTok{print}\NormalTok{(prob.table,}\AttributeTok{digits =} \DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        [,1]   [,2]   [,3]   [,4]   [,5]
## [1,] 0.8704 0.8655 0.7361 0.8667 0.7094
## [2,] 0.8444 0.8737 0.6498 0.8667 0.7094
## [3,] 0.5674 0.5736 0.7361 0.5814 0.7094
## [4,] 0.5988 0.5912 0.6498 0.5814 0.7094
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(grad.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   dep sex yes no   n dep.sex
## 1   0   0 235 35 270       0
## 2   0   1  38  7  45       0
## 3   1   0 122 93 215       0
## 4   1   1 103 69 172       1
\end{verbatim}

\end{document}
