% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{amsmath}
\usepackage{mathtools}
\usepackage{amsthm}
\usepackage{bm}
\usepackage{xcolor}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Time Series Analysis - STAT 478 - HW \#5},
  pdfauthor={Alex Towell (atowell@siue.edu)},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Time Series Analysis - STAT 478 - HW \#5}
\author{Alex Towell
(\href{mailto:atowell@siue.edu}{\nolinkurl{atowell@siue.edu}})}
\date{}

\begin{document}
\maketitle

\newcommand{\var}{\operatorname{Var}}
\newcommand{\expect}{\operatorname{E}}
\newcommand{\corr}{\operatorname{Corr}}
\newcommand{\cov}{\operatorname{Cov}}
\newcommand{\ssr}{\operatorname{SSR}}
\newcommand{\se}{\operatorname{SE}}
\newcommand{\mat}[1]{\bm{#1}}
\newcommand{\eval}[2]{\left. #1 \right\vert_{#2}}
\newcommand{\argmin}{\operatorname{arg\,min}}

\hypertarget{problem-1}{%
\section{Problem 1}\label{problem-1}}

Consider the \(\operatorname{MA}(2)\) process, where all the \(\{e_t\}\)
values are independent white noise with variance \(\sigma^2\). \[
   Y_t = e_t − 0.5 e_{t−1} − 0.3 e_{t−2}
\]

\hypertarget{prelimary-analysis}{%
\subsection{Prelimary analysis}\label{prelimary-analysis}}

In general, a \(\operatorname{MA}(2)\) process has the form \[
   Y_t = \mu + e_t - \theta_1 e_{t-1} - \theta_2 e_{t-2}
\] where \(\{e_t\}\) is i.i.d. WN with mean \(0\) and variance
\(\sigma^2\).

We denote such a moving average process by
\(\operatorname{MA}(2 ; \mu,\theta_1,\theta_2,\sigma)\) which we model
with the following R function:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{MA2 }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(mu, theta1, theta2, }\AttributeTok{sigma=}\DecValTok{1}\NormalTok{)}
\NormalTok{\{}
   \FunctionTok{return}\NormalTok{(}\ControlFlowTok{function}\NormalTok{(N)}
\NormalTok{   \{}
\NormalTok{      et }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\AttributeTok{n=}\NormalTok{N}\SpecialCharTok{+}\DecValTok{2}\NormalTok{,}\AttributeTok{mean=}\DecValTok{0}\NormalTok{,}\AttributeTok{sd=}\NormalTok{sigma)}
\NormalTok{      yt }\OtherTok{\textless{}{-}}\NormalTok{ mu }\SpecialCharTok{+}
\NormalTok{            et[}\DecValTok{1}\SpecialCharTok{:}\NormalTok{N] }\SpecialCharTok{{-}}
\NormalTok{            theta1 }\SpecialCharTok{*}\NormalTok{ et[}\DecValTok{2}\SpecialCharTok{:}\NormalTok{(N}\SpecialCharTok{+}\DecValTok{1}\NormalTok{)] }\SpecialCharTok{{-}}
\NormalTok{            theta2 }\SpecialCharTok{*}\NormalTok{ et[}\DecValTok{3}\SpecialCharTok{:}\NormalTok{(N}\SpecialCharTok{+}\DecValTok{2}\NormalTok{)]}
      \FunctionTok{return}\NormalTok{(yt)}
\NormalTok{   \})}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

This function takes three parameters, \(\mu\), \(\theta_1\), and
\(\theta_2\), and optionally a fourth parameter \(\sigma\), and returns
an anonymous function that accepts a single parameter, \(n\), which
specifies the number of points to generate from the process.

Matching \(e_t − 0.5 e_{t−1} − 0.3 e_{t−2}\) and
\(\mu + e_t - \theta_1 e_{t-1} - \theta_2 e_{t-2}\) term by term, we see
that \(\mu = 0\), \(\theta_1 = 0.5\), and \(\theta_2 = 0.3\), or in
other words \[
   \{Y_t\} \sim \operatorname{MA2}(\mu=0,\theta_1=0.5,\theta_2=0.3,\sigma).
\]

\hypertarget{part-a}{%
\subsection{Part (a)}\label{part-a}}

\fbox{Find $\operatorname{E}(Y_t)$.}

A moving average process of order \(2\) with \(\mu = 0\) has an
expectation of zero. However, just this once, we will manually derive
the characteristic. By the linearity of expectation, \begin{align}
   \operatorname{E}(Y_t)
      &= \operatorname{E}(e_t) - 0.5 \operatorname{E}(e_{t-1}) - 0.3 \operatorname{E}(e_{t-2)}\\
      &= 0 - 0.5 (0) - 0.3 (0) = 0.
\end{align}

\hypertarget{part-b}{%
\subsection{Part (b)}\label{part-b}}

\fbox{Find $\operatorname{Cov}(Y_t,Y_t) = \operatorname{Var}(Y_t)$.}

Since
\(\{Y_t\} \sim \operatorname{MA}(2 ; \mu=0, \theta=0.5, \theta_2 = 0.3, \sigma)\),
the variance is given by \[
   \operatorname{Var}(Y_t) = \sigma^2(1 + \theta_1^2 + \theta_2^2) = \sigma^2(1 + 0.5^2 + 0.3^2) = 1.34 \sigma^2.
\]

However, we may manually derive it using the computational variance
formula, \begin{align*}
   \operatorname{Var}(Y_t) &= \operatorname{E}(Y_t^2) - \operatorname{E}^2(Y_t)\\
             &= \operatorname{E}(e_t − 0.5 e_{t−1} − 0.3 e_{t−2})^2\\
             &= \operatorname{E}\!\left(e_t^2 − e_t e_{t−1} − \frac{3}{5} e_t e_{t−2} + \frac{1}{4} e_{t-1}^2 + \frac{3}{10} e_{t-1} e_{t-2} + \frac{9}{100} e_{t-2}^2\right)\\
             &= \sigma^2 - 0 - \frac{3}{5} 0 + \frac{1}{4} \sigma^2 + \frac{3}{10} 0 + \frac{9}{100}\sigma^2\\
             &= \sigma^2 \left(1 + \frac{1}{4} \frac{9}{100}\right)\\
             &= 1.34 \sigma^2.
\end{align*}

\hypertarget{part-c}{%
\subsection{Part (c)}\label{part-c}}

\fbox{Find $\gamma_k = \operatorname{Cov}(Y_t,Y_{t+k})$. and, from this, find the ACF, $\rho_k$.}

Since
\(\{Y_t\} \sim \operatorname{MA}(2; \mu=0,\theta=0.5, \theta_2=0.3, \sigma)\),
the covariance of \(Y_t\) and \(Y_{t+k}\) is given by \begin{align}
   \operatorname{Cov}(Y_t,Y_{t+k}) =
   \begin{cases}
      \operatorname{Var}(Y_t)                               & k = 0,\\
      \sigma^2(-\theta_1 + \theta_1 \theta_2) & k = 1,\\
      \sigma^2(-\theta_2)                     & k = 2,\\
      0                                       & k > 2.
   \end{cases}
\end{align}

We already derived the variance of \(Y_t\) and, since \(\theta_1 = 0.5\)
and \(\theta_2 = 0.3\), we may rewrite the above as \begin{align}
   \gamma_k =
   \begin{cases}
      1.34 \sigma^2     & k = 0,\\
      -0.35 \sigma^2    & k = 1,\\
      -0.3 \sigma^2     & k = 2,\\
      0                 & k > 2
   \end{cases}
\end{align} and since \(\rho_k = \gamma_k / \gamma_0\), \begin{equation}
   \rho_k =
   \begin{cases}
      1           & k = 0,\\
      -0.261      & k = 1,\\
      -0.224      & k = 2,\\
      0           & k > 2.
   \end{cases}
\end{equation}

\hypertarget{part-d}{%
\subsection{Part (d)}\label{part-d}}

\fbox{
\begin{minipage}{.9\textwidth}
Generate time series datasets of length $n=200$ according to this
$\operatorname{MA}(2)$ process.
Plot the observed time series and the sample ACF and PACF.
Do the plots agree with what you know to be true?
\end{minipage}}

In code, we model
\(\{Y_t\} \sim \operatorname{MA2}(\theta_1=0.5, \theta_2 = 0.3, \mu = 0)\)
with:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Yt }\OtherTok{\textless{}{-}} \FunctionTok{MA2}\NormalTok{(}\AttributeTok{theta1=}\NormalTok{.}\DecValTok{5}\NormalTok{, }\AttributeTok{theta2=}\NormalTok{.}\DecValTok{3}\NormalTok{, }\AttributeTok{mu=}\DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

We sample \(n=200\) values from \(\{Y_t\}\) with

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{y200 }\OtherTok{\textless{}{-}} \FunctionTok{Yt}\NormalTok{(}\AttributeTok{N=}\DecValTok{200}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

We plot the realization of the time series with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(y200,}\AttributeTok{type=}\StringTok{"l"}\NormalTok{)}
\FunctionTok{points}\NormalTok{(y200)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw5_files/figure-latex/unnamed-chunk-4-1.pdf}

The mean appears to be centered around \(0\) with a constant variance,
as expected.

The sample ACF and PACF are given by:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{),}\AttributeTok{oma=}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{))}
\FunctionTok{acf}\NormalTok{(y200)}
\FunctionTok{pacf}\NormalTok{(y200)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw5_files/figure-latex/unnamed-chunk-5-1.pdf}

As expected, since \(\{Y_t\}\) models \(\operatorname{MA}(2)\), the
sample ACF cuts off after lag \(k=2\). The PACF is not as informative,
other than suggesting that \(\{Y_t\}\) is not a good fit for an
autoregressive model.

\hypertarget{problem-2}{%
\section{Problem 2}\label{problem-2}}

\fbox{\begin{minipage}{.9\textwidth}
Consider the $\operatorname{AR}(1)$ process: $Y_t = \phi Y_{t−1} + e_t$, where all the $\{e_t\}$ values are independent white noise with variance $\sigma^2$.
\end{minipage}}

\hypertarget{preliminary-analysis}{%
\subsection{Preliminary analysis}\label{preliminary-analysis}}

In general, a \(\operatorname{AR}(1)\) process is given by \[
   Y_t = \Delta + \phi Y_{t-1} + e_t
\] where \(\{e_t\}\) is i.i.d. WN with mean \(0\) and variance
\(\sigma^2\).

We denote such an autoregressive process by
\(\operatorname{AR}(1 ; \phi, \Delta, \sigma)\), which we model with the
following R function:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{AR1 }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(phi, delta, }\AttributeTok{sigma=}\DecValTok{1}\NormalTok{)}
\NormalTok{\{}
   \FunctionTok{return}\NormalTok{(}\ControlFlowTok{function}\NormalTok{(N)}
\NormalTok{   \{}
\NormalTok{      yt }\OtherTok{\textless{}{-}} \FunctionTok{vector}\NormalTok{(}\AttributeTok{length=}\NormalTok{N)}
\NormalTok{      yt[}\DecValTok{1}\NormalTok{] }\OtherTok{\textless{}{-}} \DecValTok{0} \CommentTok{\#rnorm(n=1,mean=0,sd=sigma)}
      \ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{2}\SpecialCharTok{:}\NormalTok{N)}
\NormalTok{      \{}
\NormalTok{          et }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\AttributeTok{n=}\DecValTok{1}\NormalTok{,}\AttributeTok{mean=}\DecValTok{0}\NormalTok{,}\AttributeTok{sd=}\NormalTok{sigma)}
\NormalTok{          yt[i] }\OtherTok{\textless{}{-}}\NormalTok{ delta}\SpecialCharTok{+}\NormalTok{phi}\SpecialCharTok{*}\NormalTok{yt[i}\DecValTok{{-}1}\NormalTok{]}\SpecialCharTok{+}\NormalTok{et}
\NormalTok{      \}}
      \FunctionTok{return}\NormalTok{(yt)}
\NormalTok{   \})}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

This function takes three parameters, \(\phi\), \(\Delta\), and
\(\sigma\), and returns an anonymous function that accepts a single
parameter, \(n\), which specifies the number of points to generate from
the process.

Observe that an autoregressive process
\(\operatorname{AR}(1; \phi, \Delta, \sigma^2)\) has a mean
\(\mu = \Delta / (1-\phi)\) and variance
\(\sigma_{Y_t}^2 = \sigma^2 / (1-\phi^2)\).

\hypertarget{part-a-1}{%
\subsection{Part (a)}\label{part-a-1}}

\fbox{Show that if $|\phi| = 1$, the process cannot be stationary.}

To be stationary, the variance must be constant. The variance of \(Y_t\)
when \(|\phi|=1\) is given by \begin{align*}
   \operatorname{Var}(Y_t)
      &= \operatorname{Var}(Y_{t−1}) + \sigma^2\\
      &= \operatorname{Var}(Y_{t−2}) + 2 \sigma^2\\
      &\vdots\\
      &= \operatorname{Var}(Y_{t-(t-2)}) + (t-2) \sigma^2\\
      &= \operatorname{Var}(Y_{t-(t-1)}) + (t-1) \sigma^2\\
      &= t \sigma^2.
\end{align*} Thus, if \(|\phi|=1\), \(Y_t\) has a variance of
\(t \sigma^2\), which is a function of time and is thus non-stationary.

\hypertarget{part-b-1}{%
\subsection{Part (b)}\label{part-b-1}}

\fbox{Take $\phi = −0.6$, calculate find the ACF, $\rho_k$.}

For a time series that models \(\operatorname{AR}(1)\), the
autocorrelation function \(\rho_k\) is given by \(\phi^k\). Thus, since
\(\{Y_t\}\) models
\(\operatorname{AR}(1 ; \phi=-0.6, \Delta = 0, \sigma^2)\), \(\{Y_t\}\)
has the autocorrelation function \[
   \rho_k = (-0.6)^k
\] for \(k = 0,1,2,\ldots\).

\hypertarget{part-c-1}{%
\subsection{Part (c)}\label{part-c-1}}

\fbox{\begin{minipage}{.9\textwidth}
Take $\phi = −0.6$.
Generate time series datasets of length $n = 200$ according to the $\operatorname{AR}(1)$ process.
Plot the observed time series and the sample ACF and PACF.
Do the plots agree with what you know to be true?
\end{minipage}}

First, we know that \(Y_t = \phi Y_{t−1} + e_t\). Matching this term by
term to Matching \(\Delta \phi Y_{t−1} + e_t\) shows that \(\Delta = 0\)
(and therefore \(\operatorname{E}(Y_t) = 0\)).

In code, we model
\(\{Y_t\} \sim \operatorname{AR1}(\phi=-0.6, \Delta = 0, \sigma=1)\)
with:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Yt }\OtherTok{\textless{}{-}} \FunctionTok{AR1}\NormalTok{(}\AttributeTok{phi=}\SpecialCharTok{{-}}\FloatTok{0.6}\NormalTok{, }\AttributeTok{delta=}\DecValTok{0}\NormalTok{, }\AttributeTok{sigma=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

We sample \(n=200\) values from \(\{Y_t\}\) with:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{y200 }\OtherTok{\textless{}{-}} \FunctionTok{Yt}\NormalTok{(}\AttributeTok{N=}\DecValTok{200}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

We plot the realization of the time series with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(y200,}\AttributeTok{type=}\StringTok{"l"}\NormalTok{)}
\FunctionTok{points}\NormalTok{(y200)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw5_files/figure-latex/unnamed-chunk-9-1.pdf}

The mean appears to be centered around \(0\) with a constant variance as
expected. Also, since \(\phi\) is negative, \(Y_t\) and \(Y_{t+1}\) are
negatively correlated and thus exhibits jittery up and down movements as
expected.

The sample ACF and PACF are given by:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{),}\AttributeTok{oma=}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{))}
\FunctionTok{acf}\NormalTok{(y200)}
\FunctionTok{pacf}\NormalTok{(y200)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw5_files/figure-latex/unnamed-chunk-10-1.pdf}

The sample PACF cuts off (with a single outlier) after lag \(1\), as
expected of a \(\operatorname{AR}(1)\) process.

\hypertarget{part-d-1}{%
\subsection{Part (d)}\label{part-d-1}}

\fbox{\begin{minipage}{.8\textwidth}
What happens when we increase the sample size? Repeat part (c) when $n = 1000$.
Comment on your findings.
\end{minipage}}

We sample \(n=1000\) values from \(\{Y_t\}\) with

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{y1000 }\OtherTok{\textless{}{-}} \FunctionTok{Yt}\NormalTok{(}\AttributeTok{N=}\DecValTok{1000}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

We plot the realization of the time series with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(y1000,}\AttributeTok{type=}\StringTok{"l"}\NormalTok{)}
\FunctionTok{points}\NormalTok{(y1000)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw5_files/figure-latex/unnamed-chunk-12-1.pdf}

The mean appears to be centered around \(0\) with a constant variance,
as expected.

The sample ACF and PACF are given by:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{),}\AttributeTok{oma=}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{))}
\FunctionTok{acf}\NormalTok{(y1000)}
\FunctionTok{pacf}\NormalTok{(y1000)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw5_files/figure-latex/unnamed-chunk-13-1.pdf}

We see the same general pattern as before in each case, except due to
the increased sample size the confidence intervals have narrowed.

\hypertarget{problem-3}{%
\section{Problem 3}\label{problem-3}}

A data set of \(57\) consecutive measurements from a machine tool are in
the \emph{deere3} object in the TSA package.

\hypertarget{preliminary-steps}{%
\subsection{Preliminary steps}\label{preliminary-steps}}

We load the requisite time series data with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(TSA)}
\FunctionTok{data}\NormalTok{(deere3)}
\end{Highlighting}
\end{Shaded}

\hypertarget{part-a-2}{%
\subsection{Part (a)}\label{part-a-2}}

\fbox{\begin{minipage}{.8\textwidth}
Plot the time series.
What basic pattern do you see from the plot?
Might a stationary model be appropriate for this plot?
\end{minipage}}

We plot the time series with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(deere3)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw5_files/figure-latex/unnamed-chunk-15-1.pdf}

A stationary model may be appropriate since it fluctuates randomly
around some central tendency and the fluctuates seem relatively constant
(albeit quite large).

\hypertarget{part-b-2}{%
\subsection{Part (b)}\label{part-b-2}}

\fbox{\begin{minipage}{.8\textwidth}
Plot the sample ACF and PACF.
Tentatively specify the type of model (AR, MA, or ARMA) as well as the order(s)
of the model.
Write up detailed notes that describe how you decided on the model.
\end{minipage}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{),}\AttributeTok{oma=}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{))}
\FunctionTok{acf}\NormalTok{(deere3)}
\FunctionTok{pacf}\NormalTok{(deere3)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw5_files/figure-latex/unnamed-chunk-16-1.pdf}

We seek a parsimonious model that sufficiently explains the data.
Tentatively, we choose a \(\operatorname{AR}(1)\) model.

The sample ACF decays and the sample PACF drops off to values compatible
with \(0\) after lag \(k=1\). Thus, the sample ACF and PACF are
compatible with a \(\operatorname{AR}(1)\) process. Due to its parsimony
and compatibility with the data, we choose \(\operatorname{AR}(1)\).

\hypertarget{part-c-2}{%
\subsection{Part (c)}\label{part-c-2}}

\fbox{\begin{minipage}{.8\textwidth}
Fit an $\operatorname{AR}(1)$ model using arima function in R and use it to
forecast the next ten values of the series, and provides the forecasted values.
\end{minipage}}

We seek to fit the time series to a first-order autoregressive model of
the form \[
   Y_t = \delta + \phi Y_{t-1} + e_t
\] where \(e_t\) is white noise with mean \(0\) and variance
\(\sigma^2\) and \(\delta = \mu(1-\phi)\).

We perform the fit using the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ar1 }\OtherTok{\textless{}{-}} \FunctionTok{arima}\NormalTok{(deere3,}\AttributeTok{order=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{)) }\CommentTok{\# fit an AR(1) model}
\NormalTok{ar1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## arima(x = deere3, order = c(1, 0, 0))
## 
## Coefficients:
##          ar1  intercept
##       0.5255   124.3832
## s.e.  0.1108   394.2066
## 
## sigma^2 estimated as 2069355:  log likelihood = -495.51,  aic = 995.02
\end{verbatim}

We see that \(\hat{\mu} = 124.3832\), \(\hat{\phi} = 0.5255\),
\(\hat{\sigma}^2 = 2069355\), and
\(\hat{\delta} = \hat{\mu}(1-\hat{\phi}) = 59.2\). Thus, we estimate
that \[
   \hat{Y}_t = 59.02 + 0.5255 \hat{Y}_{t-1} + e_t.
\]

We perform a \(10\)-step ahead forecast with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{predict}\NormalTok{(ar1,}\AttributeTok{n.ahead=}\DecValTok{10}\NormalTok{)}\SpecialCharTok{$}\NormalTok{pred}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Time Series:
## Start = 58 
## End = 67 
## Frequency = 1 
##  [1] -335.145917 -117.120758   -2.538374   57.680010   89.327578  105.959850
##  [7]  114.700885  119.294706  121.708973  122.977783
\end{verbatim}

For small look-aheads, since nearby values in the time series are
correlated, nearby previous values should have some measurable effect on
the forecast. However, we expect that, as the look-ahead time for the
forecast goes to infinity, the forecast converges to
\(\hat\mu = 124.3832\).

\hypertarget{additional-experimentation}{%
\subsection{Additional
experimentation}\label{additional-experimentation}}

For fun, we construct a generative autoregressive model of order \(1\)
with:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Xt }\OtherTok{\textless{}{-}} \FunctionTok{AR1}\NormalTok{(}\AttributeTok{phi=}\FloatTok{0.5255}\NormalTok{, }\AttributeTok{delta=}\FloatTok{59.0198284}\NormalTok{, }\AttributeTok{sigma=}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{2069355}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

If we sample a large number of points from this generative model and
then fit a \(\operatorname{AR}(1)\) model to it, we get estimates
similiar to before:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{arima}\NormalTok{(}\FunctionTok{Xt}\NormalTok{(}\AttributeTok{N=}\DecValTok{1000}\NormalTok{),}\AttributeTok{order=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## arima(x = Xt(N = 1000), order = c(1, 0, 0))
## 
## Coefficients:
##          ar1  intercept
##       0.5434   180.1728
## s.e.  0.0265    98.9118
## 
## sigma^2 estimated as 2044761:  log likelihood = -8684.51,  aic = 17373.02
\end{verbatim}

\hypertarget{problem-4}{%
\section{Problem 4}\label{problem-4}}

A data set of durations until payment for \(130\) consecutive orders
from a Winegrad distributor are in the days object in the TSA package.

\hypertarget{preliminary-steps-1}{%
\subsection{Preliminary steps}\label{preliminary-steps-1}}

We load the data with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(TSA)}
\FunctionTok{data}\NormalTok{(days)}
\end{Highlighting}
\end{Shaded}

\hypertarget{part-a-3}{%
\subsection{Part (a)}\label{part-a-3}}

\fbox{\begin{minipage}{.8\textwidth}
Plot the time series.
What basic pattern do you see from the plot?
Might a stationary model be appropriate for this plot?
\end{minipage}}

We plot the time series with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(days)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw5_files/figure-latex/unnamed-chunk-22-1.pdf}

A stationary model may be appropriate since it fluctuates randomly
around some central tendency and the fluctuates seem relatively constant
(albeit quite large).

\hypertarget{part-b-3}{%
\subsection{Part (b)}\label{part-b-3}}

\fbox{\begin{minipage}{.8\textwidth}
Plot the sample ACF and PACF.
Tentatively specify the type of model (AR, MA, or ARMA) as well as the order(s) of the model.
Write up detailed notes that describe how you decided on the model.
\end{minipage}}

The sample ACF and PACF are given by:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{),}\AttributeTok{oma=}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{))}
\FunctionTok{acf}\NormalTok{(days)}
\FunctionTok{pacf}\NormalTok{(days)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw5_files/figure-latex/unnamed-chunk-23-1.pdf}

There does not seem to be much of a pattern to the data. The ACF and
PACF suggest that the data is compatible with the hypothesis that the
values in the time series are linearly uncorrelated.

We choose a model that is a white noise process with a non-zero mean. We
might think of this as a degenerate case of the ARMA model denoted by
\(\operatorname{ARMA}(0,0)\).

\hypertarget{model-selection}{%
\subsubsection{Model selection}\label{model-selection}}

In what follows, we analyze model selection for this time series in more
depth. Given a set of candidate models that may hopefully sufficiently
explain the data, one strategy of model selection is to choose the model
with the lowest Akaike information criterion (AIC) on the given data
set.

In particular, suppose the set of candidate models \(M\) is given by \[
   M = \left\{ \operatorname{ARMA}(p,q) \, \vert \, p \in P, q \in Q \right\}
\] where \(P\) and \(Q\) are subsets of the natural numbers and we let
the selected model \(m^*\) be defined as \[
   m^* = \operatorname{arg\,min}_{m \in M} \operatorname{AIC}(m).
\]

If \(M\) is a relatively small set, we can simply perform a brute-force
exhaustive search through. We let \(P = \{0,1,2,3\}\) and
\(Q = \{0,1,2,3\}\) and thus \(|M|=16\). We perform the exhaustive
search with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{P }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{)}
\NormalTok{Q }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{)}
\NormalTok{aics }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\AttributeTok{nrow=}\FunctionTok{length}\NormalTok{(P)}\SpecialCharTok{*}\FunctionTok{length}\NormalTok{(Q),}\AttributeTok{ncol=}\DecValTok{3}\NormalTok{)}
\FunctionTok{colnames}\NormalTok{(aics) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"AIC"}\NormalTok{,}\StringTok{"p"}\NormalTok{,}\StringTok{"q"}\NormalTok{)}
\NormalTok{i }\OtherTok{\textless{}{-}} \DecValTok{1}
\ControlFlowTok{for}\NormalTok{ (p }\ControlFlowTok{in}\NormalTok{ P)}
\NormalTok{\{}
   \ControlFlowTok{for}\NormalTok{ (q }\ControlFlowTok{in}\NormalTok{ Q)}
\NormalTok{   \{}
\NormalTok{      aics[i,}\DecValTok{1}\NormalTok{] }\OtherTok{\textless{}{-}} \FunctionTok{arima}\NormalTok{(days,}\AttributeTok{order=}\FunctionTok{c}\NormalTok{(p,}\DecValTok{0}\NormalTok{,q))}\SpecialCharTok{$}\NormalTok{aic}
\NormalTok{      aics[i,}\DecValTok{2}\NormalTok{] }\OtherTok{\textless{}{-}}\NormalTok{ p}
\NormalTok{      aics[i,}\DecValTok{3}\NormalTok{] }\OtherTok{\textless{}{-}}\NormalTok{ q}
\NormalTok{      i }\OtherTok{\textless{}{-}}\NormalTok{ i }\SpecialCharTok{+} \DecValTok{1}
\NormalTok{   \}}
\NormalTok{\}   }
\NormalTok{aics }\OtherTok{\textless{}{-}}\NormalTok{ aics[}\FunctionTok{order}\NormalTok{(aics[,}\DecValTok{1}\NormalTok{],}\AttributeTok{decreasing=}\ConstantTok{FALSE}\NormalTok{),]}
\NormalTok{aics}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            AIC p q
##  [1,] 886.2239 1 2
##  [2,] 886.9111 0 0
##  [3,] 886.9546 0 2
##  [4,] 887.0030 2 1
##  [5,] 887.2617 3 0
##  [6,] 887.3115 2 0
##  [7,] 887.6010 1 0
##  [8,] 887.8065 0 3
##  [9,] 887.8736 0 1
## [10,] 887.9656 2 2
## [11,] 888.5414 3 1
## [12,] 888.8066 3 2
## [13,] 888.9095 1 1
## [14,] 890.0033 2 3
## [15,] 890.8047 3 3
## [16,] 890.8777 1 3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"m* = ARIMA("}\NormalTok{,aics[}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{],}\StringTok{","}\NormalTok{,aics[}\DecValTok{1}\NormalTok{,}\DecValTok{3}\NormalTok{],}\StringTok{")}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## m* = ARIMA( 1 , 2 )
\end{verbatim}

We see that \(m^* = \operatorname{ARMA}(1,2)\). However, the next best
model according to AIC on \(M\) is \(\operatorname{ARMA}(0,0)\). The
\emph{third} best model is \(\operatorname{ARMA}(0,2)\), which is
identical to \(\operatorname{MA}(2)\).

Given the simplicity of white noise (with a non-zero mean), as an ad hoc
decision I remain inclined to accept \(\operatorname{ARMA}(0,0)\) as the
most likely model for the data. In other words, my \emph{prior} on \(M\)
more heavily weighs the simpler models with smaller \(p\) and \(q\) than
simply choosing the minimum AIC on \(M\).

\hypertarget{part-c-3}{%
\subsection{Part (c)}\label{part-c-3}}

\fbox{\begin{minipage}{.8\textwidth}
Fit an $\operatorname{MA}(2)$ model using arima function in R and use it to forecast the next ten values of the series, and list the forecasted values.
\end{minipage}}

We seek to fit the time series to a second-order moving average model of
the form \[
   Y_t = \mu + e_t - \theta_1 e_{t-1} - \theta_2 e_{t-2}
\] where \(e_t\) is white noise with mean \(0\) and variance
\(\sigma^2\).

We perform the fit using the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ma2 }\OtherTok{\textless{}{-}} \FunctionTok{arima}\NormalTok{(days,}\AttributeTok{order=}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\NormalTok{ma2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## arima(x = days, order = c(0, 0, 2))
## 
## Coefficients:
##          ma1     ma2  intercept
##       0.1113  0.1557    28.6931
## s.e.  0.0894  0.0884     0.7946
## 
## sigma^2 estimated as 51.33:  log likelihood = -440.48,  aic = 886.95
\end{verbatim}

We see that \(\hat\mu = 28.6931\), \(\hat\theta_1 = 0.1113\), and
\(\hat\theta_2 = 0.1557\). Thus, we estimate that \[
   \hat{Y}_t = 28.6931 + e_t - 0.1113 e_{t-1} - 0.1557 e_{t-2}.
\]

We perform a \(10\)-step ahead forecast with the following R code:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{predict}\NormalTok{(ma2,}\AttributeTok{n.ahead=}\DecValTok{10}\NormalTok{)}\SpecialCharTok{$}\NormalTok{pred}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Time Series:
## Start = 131 
## End = 140 
## Frequency = 1 
##  [1] 33.43453 27.67666 28.69310 28.69310 28.69310 28.69310 28.69310 28.69310
##  [9] 28.69310 28.69310
\end{verbatim}

We see that the first two forecasts are a function of the last two
observations. After that, the forecast is \(\hat\mu = 28.6931\), which
is consistent with the assumption of a constant mean stationary process.

\hypertarget{additional-experimentation-1}{%
\subsection{Additional
experimentation}\label{additional-experimentation-1}}

For fun, we construct a generative moving average model of order \(2\)
with:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Zt }\OtherTok{\textless{}{-}} \FunctionTok{MA2}\NormalTok{(}\AttributeTok{mu=}\FloatTok{28.6931}\NormalTok{,}\AttributeTok{theta1=}\SpecialCharTok{{-}}\FloatTok{0.1113}\NormalTok{,}\AttributeTok{theta2=}\SpecialCharTok{{-}}\FloatTok{0.1557}\NormalTok{,}\AttributeTok{sigma=}\FloatTok{51.33}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

If we sample a large number of points from this generative model and
then fit a \(\operatorname{MA}(2)\) model to it, we get estimates
similiar to before:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{),}\AttributeTok{oma=}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{))}
\NormalTok{zt }\OtherTok{\textless{}{-}} \FunctionTok{Zt}\NormalTok{(}\AttributeTok{N=}\DecValTok{1000}\NormalTok{)}
\FunctionTok{acf}\NormalTok{(zt)}
\FunctionTok{pacf}\NormalTok{(zt)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw5_files/figure-latex/unnamed-chunk-28-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{arima}\NormalTok{(zt,}\AttributeTok{order=}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## arima(x = zt, order = c(0, 0, 2))
## 
## Coefficients:
##          ma1     ma2  intercept
##       0.0842  0.1451    27.4917
## s.e.  0.0313  0.0320     1.9668
## 
## sigma^2 estimated as 2562:  log likelihood = -5343.15,  aic = 10692.3
\end{verbatim}

\end{document}
